### ISSUE TITLE
iOS autodelete key values items after uninstall?

### ISSUE THREAD

**Issue by sefidgaran** [mogol/flutter_secure_storage#102]
First of all, thanks for this useful package.

I have tried to uninstall (delete) the app (iOS) which I have some key and values generated by secure flutter storage package. but unfortunately when I tried to reinstall the app (debug mode), those keys and values are still stored in the device.
Is there any good way to have all (flutter_secure_storage) keys and values deleted after deleting the app in iOS?

Thanks in advance

**Comment by YAPPDEF** [comment]
Same as https://github.com/mogol/flutter_secure_storage/issues/88

**Comment by mogol** [comment]
Close as duplicate
