### ISSUE TITLE
AndroidX incompatibility?

### ISSUE THREAD

**Issue by JillyTaboga** [mogol/flutter_secure_storage#103]
A problem occurred configuring root project 'flutter_secure_storage'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

I am getting erro trying to compile with AndroidX.

**Comment by titonton** [comment]
I'm also getting problems with AndroidX. Granted, I'm getting different errors but I think it stems from the same problem. Did you do the migration for your project?

**Comment by juliansteenbakker** [comment]
Please try again with latest code on develop branch and report if it's still not working
