### ISSUE TITLE
Add support for MacOS Keychain

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [mogol/flutter_secure_storage#106]

**Comment by enricotal70** [comment]
The flutter desktop adoption for Mac is getting hotter and hotter. Please consider taking a look at this https://developer.apple.com/documentation/security/keychain_services and implementing it Thanks

**Comment by fvisticot** [comment]
It would be very nice to have macos support. Please help us

**Comment by DhavalRKansara** [comment]
@mogol Do you have any Ppan to provide a MacOs  support?
