### ISSUE TITLE
A problem occurred configuring root project 'flutter_secure_storage'.

### ISSUE THREAD

**Issue by amankadam** [mogol/flutter_secure_storage#109]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_secure_storage'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin flutter_secure_storage could not be built due to the issue above.

**Comment by kurtiev** [comment]
@amankadam  Hi, did you manage to fix this? I faced the same issue.

**Comment by amankadam** [comment]
@kurtiev I didn't find any solution instead i used shared preference package.

**Comment by juliansteenbakker** [comment]
I'm closing this issue since it's quite old. Please check with latest version of package instead, and if the issue still exists i'll reopen this issue.
