### ISSUE TITLE
Is it possible that data is wiped across installs.

### ISSUE THREAD

**Issue by manujbahl** [mogol/flutter_secure_storage#11]
Data is available across installs. is there a way that data is not retained when app is uninstalled.

**Comment by mogol** [comment]
Android: data is stored in shared preferences 
You could check [stackoverflow question](https://stackoverflow.com/questions/15873066/how-to-remove-shared-preference-while-application-uninstall-in-android?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

iOS: data is stored in Keychain, it stores data between installs.

Try this approach:
* On each launch check flag isFreshInstall in [shared_preferences](https://pub.dartlang.org/packages/shared_preferences)
* If it's non false, delete all data from secure storage and set the flag to false
** for android you should turn off backup of preferences
