### ISSUE TITLE
How can read from a different app?

### ISSUE THREAD

**Issue by endritgojani** [mogol/flutter_secure_storage#114]
I have two apps that have common users and can go from one app to another. I need to save data like password and email so that I can access it from the other application. Is it possible and safe?

**Comment by mogol** [comment]
Hey @endritgojani, sorry for the late response. 
The plugin is a thin wrapper on top of iOS Keychain and KeyStore/SharedPref. So you need to check the capabilities of them. Afaik it's possible for iOS, but I am not sure about Android. 

Please use Stackoverflow for general questions.
