### ISSUE TITLE
Delay reading and showing Data on UI.

### ISSUE THREAD

**Issue by Harbdollar** [mogol/flutter_secure_storage#119]
Hi, Thanks for the Awesome plugin so far. I really appreciate your effort.
Am using the plugin to store data after I receive it from the API, The problem is wherever I try to read and display the data, I won't show the Data on UI until I hot reload or reload the App again.

`balance = await storage.read(key: Constants.walletbal);
   lastName = await storage.read(key: Constants.lname); //btcWallet
   btcWalletAdrress = await storage.read(key: Constants.unique_bcwallet);`

Wherever I print it on console, It will display null but after refresh or reload it will display the data

**Comment by mogol** [comment]
Hey @Harbdollar 
Please ask this question at StackOverflow.  You can tag the question with flutter-secure-storage

**Comment by Harbdollar** [comment]
Thanks
