### ISSUE TITLE
I found a problem with recovered application.

### ISSUE THREAD

**Issue by bunker89** [mogol/flutter_secure_storage#120]
Sorry for my low English level. I'm not good at English.

I really really thanks for this package.
This is very useful for me and hope to be maintained greatly.

What I found issue is hidden for special case.
I'm using google signing and deploy with app bundle. not apk.

If user recover our app from another device like Samsung smart switch then maybe app is recovered with SharedPreference but not contain keystore. 

case 1. Recovered app access keystore via this package is occur error.
case 2. User remove app and reinstall from playstore and do case 1. is occur error.
case 3. User reinstall using direct apk and do case 1. is going well.

Many of developers can't realize this problem. Because this is only caused by Play store with recovered app who are using app bundle.

I fixed this error to set 'allowBackup' false at manifest.

**Comment by mogol** [comment]
Hey @bunker89, is it the same config as [describe in Readme](https://github.com/mogol/flutter_secure_storage#configure-android-version) or different?

**Comment by bunker89** [comment]
oh... my...

I'm really sorry...
I missed disable autobackup in documnet TT
