### ISSUE TITLE
Data Persists after app deletion

### ISSUE THREAD

**Issue by kthirirania** [mogol/flutter_secure_storage#125]
I'm testing this package on an iOS device, and each time i delete and reinstall the app, previous data still persisting.

**Comment by mogol** [comment]
@kthirirania it's expected behaviour of iOS Keychain, e.g. take a look at #82

**Comment by kthirirania** [comment]
Any idea how can we fix this on the iOS part?

**Comment by PrismaSoftGC** [comment]
Same problem here. Any solution?

**Comment by mogol** [comment]
Please check #88
