### ISSUE TITLE
Support Background Isolates 

### ISSUE THREAD

**Issue by KLD** [mogol/flutter_secure_storage#126]
Is it possible to support background isolates on Android? 

I want to store some data with I receive a background notification via fcm. 

When I try to do so, I get 
`MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)`

There's a library that gives steps on how to setup custom Embedding, I'm not certain if it's possible it here: 
https://pub.dev/packages/android_alarm_manager#flutter-android-embedding-v1

Thank you, and keep up the awesome work

**Comment by KLD** [comment]
Ok. so after many trail and error, *MANY*  I managed to import the package and it worked in the isolate for android

here's my Application.kt
```kotlin
package YOUR.PAKAGE

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

// ##1## Added import based on pubspec.yaml's androidPackage & pluginClass
import com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin;

public class Application: FlutterApplication(), PluginRegistrantCallback {
  override fun onCreate() {
    super.onCreate()
    FlutterFirebaseMessagingService.setPluginRegistrant(this)
  }

  override fun registerWith(registry: PluginRegistry) {
    FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
    
// ##2## and registrar since type param was  PluginRegistrar (and not PluginRegistry)
FlutterSecureStoragePlugin.registerWith(registry.registrarFor("com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin"))
  }
}
```

**Comment by shantaly** [comment]
do you have an example for IOS?
