### ISSUE TITLE
Feature Request: containsKey

### ISSUE THREAD

**Issue by RyanVDW** [mogol/flutter_secure_storage#127]
Maybe add a containsKey method? Like SharedPreferences. I have a work around by pulling the value out and seeing if its not empty etc but maybe this could be added?

**Comment by dhughes72** [comment]
i needed a containskey element also, but thank you for providing your workaround... it helped me do what i need!

**Comment by RyanVDW** [comment]
For anyone else, this is how i did it:

`  Future<bool> hasKey(String key) async {
    String value = await _secureStorage.read(key: key);
    return value != null && value.isNotEmpty;
  }`

**Comment by jjsebastianfuertes** [comment]
containsKey should handle error; there is a platformException in some Android devices
`PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:O
PENSSL_internal:BAD_DECRYPT
I/flutter (30337):      at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
I/flutter (30337):      at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
I/flutter (30337):      at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:365)
I/flutter (30337):      at javax.crypto.Cipher.doFinal(Cipher.java:2055)
I/flutter (30337):      at c.h.a.b.b.b(Unknown Source:32)
I/flutter (30337):      at c.h.a.a.b(Unknown Source:11)
I/flutter (30337):      at c.h.a.a.d(Unknown Source:7)
I/flutter (30337):      at c.h.a.a.a(Unknown Source:0)
I/flutter (30337):      at c.h.a.a$b.run(Unknown Source:134)
I/flutter (30337):      at android.os.Handler.handleCallback(Handler.java:883)
I/flutter (30337):      at android.os.Handler.dispatchMessage(Handler.java:100)
I/flutter (30337):      at android.os.Looper.loop(Looper.java:214)
I/flutter (30337):      at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (30337): , null)`
