### ISSUE TITLE
Not Working in android 5.1.1 and 4.4.4

### ISSUE THREAD

**Issue by xzghx** [mogol/flutter_secure_storage#129]
The Error is :
E/flutter (18443): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)

I tried using secure storage on two real devices which are API above 18 : android 5.1.1 and 4.4.4 but it gives mentioned exception.

It is working fine in android 6.0.1.

**Comment by gutala** [comment]
I have the same issue on Android 4.4.4:
MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)

**Comment by hmawla** [comment]
Check here #132

**Comment by ftcvlad** [comment]
@hmawla Are you sure this is related to locales? My locale is English, im getting 

`Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@41adf408) but could not find and invoke the GeneratedPluginRegistrant.` and then `Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)` on **Android 4.4.4**

no exceptions on Android 9

**Comment by Ali1Ammar** [comment]
same here with  4.4.4 and 5.1.1

**Comment by juliansteenbakker** [comment]
Some fixes has been merged. Please try again using the develop branch of this repository.
