### ISSUE TITLE
RSACipher fails to generate keys when phone locale is Arabic in android

### ISSUE THREAD

**Issue by hmawla** [mogol/flutter_secure_storage#131]
Spent a while surfing the code in android and apparently KeyPairGenerator fails to generateKeyPair() when the phone is set to Arabic locale and I guess to any RTL locales.
This is due to a bug in google's own code in KeyPairGenerator when parsing the expiry DateTime according to the used locale.

I still haven't figure a way out of fixing this but will send a PR when I do.

Reference: [Here](https://issuetracker.google.com/issues/37095309)
Possible solution: [Here](https://stackoverflow.com/questions/35987510/illegalargumentexception-unparseable-date-during-androidkeystore-key-generatio/46602170#46602170)

**Comment by hmawla** [comment]
Created a workaround and made a PR
https://github.com/mogol/flutter_secure_storage/pull/132

**Comment by Omrankabalan** [comment]
Any updates ?

**Comment by juliansteenbakker** [comment]
A fix has been merged in #132.
