### ISSUE TITLE
How does this package store things on the Phone locally?

### ISSUE THREAD

**Issue by martingeidoblerUnpliant** [mogol/flutter_secure_storage#140]
I am confused as to where and how this stores things on the phone. usually i would need a pathprovider and whatnot to store things locally, but this just does `final _storage = FlutterSecureStorage();` and `_storage.write` which seems suspiciously simple, hence the question. Will this store things permanently and as long as the app is installed without doing anything else?

**Comment by hmawla** [comment]
I believe that it depends on the platform but basically it encrypts the data then uses shared preferences to store it, hence the data doesn't persist after uninstall unless it got backed up somehow

**Comment by mogol** [comment]
Please check the description of the plugin and the source code for the details
