### ISSUE TITLE
Cannot read secure_storage in native App

### ISSUE THREAD

**Issue by sh3rlock97** [mogol/flutter_secure_storage#142]
I'm adding a token using the following code:
`
      final storage = new FlutterSecureStorage();
      var iOptions = IOSOptions(groupId: "group.com.example.exampleApp");
      await storage.write(
          key: 'key', value: key, iOptions: iOptions);
`

When I try to read it in the native AppDelegate, I receive "nil"
AppDelegate:
`import UIKit
import Flutter
import KeychainAccess

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    var keychain = Keychain(accessGroup: "group.com.example.exampleApp");
    print("Notification key:");
    print(try? keychain.allKeys());
    print(try? keychain.getString("key"));
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`

I need this functionality to use the key in an Extension of the iOS-App

**Comment by chinnasamythought** [comment]
Any update on this issue ?

**Comment by chinnasamymca** [comment]
Any update on this issue, we encountered same issue.

**Comment by sh3rlock97** [comment]
This solved my issues but requires the "KeychainAccess"-Library:

`let keychain = Keychain.init(service: "flutter_secure_storage_service", accessGroup: "group.com.example.exampleApp");`
