### ISSUE TITLE
doesn't work on real device or emulator if i don't run cmd "flutter run"

### ISSUE THREAD

**Issue by YouSour** [mogol/flutter_secure_storage#147]
hi , everything it works when i run project by cmd "flutter run" but if i don't run that command , and i open my app that already install on emulator or real device it doesn't work , what should i do ? 🤔

**Comment by tibfox** [comment]
Same here but for me everything works on the emulator but not on my mobile.. still searching for a resolution

**Comment by juliansteenbakker** [comment]
Please try again with latest code on develop branch and report if it's still not working
