### ISSUE TITLE
[Request] Please make it possible to read and write more variable types

### ISSUE THREAD

**Issue by annalaufey** [mogol/flutter_secure_storage#149]
Is it possible to add read and write for different variable types? 
Similar to shared preferences where you have setInt, setBool, setDouble and setStringList.

**Comment by ljaniszewski** [comment]
I agree, this is a basic feature

**Comment by juliansteenbakker** [comment]
I am not gonna implement this because the encryption won't work on all devices with these kinds of types. Best thing you can do is parse it too and from string. This way we can ensure it's secure.
