### ISSUE TITLE
unchecked or unsafe operations

### ISSUE THREAD

**Issue by cbenhagen** [mogol/flutter_secure_storage#15]
`Note: /Users/ben/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.0/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java uses unchecked or unsafe operations.`

**Comment by xascis** [comment]
Same issue here: https://github.com/flutter/flutter/issues/10380

**Comment by mogol** [comment]
Fixed in 3.1.1
Thanks!
