### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by adityaanand13** [mogol/flutter_secure_storage#153]
For MacOs you can use keychain
https://developer.apple.com/documentation/security/keychain_services

For windows you can use CryptProtectedData
https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata

**Comment by hacker1024** [comment]
Duplicate (partly) of #106

**Comment by adityaanand13** [comment]
if flutter secure storage gets support for MacOS, Windows and Linux, the same source code can run be used to build native apps. right now developers have to change secure storage to other alternatives in there service or API layer to alternative library. which often breaks the application.

**Comment by rekire** [comment]
The Windows API Sample looks simple, great finding by the way. I'll check if I am able to create a pull request for it.

**Comment by rekire** [comment]
Today I got it managed to get a first interaction from the dart with the c++ code.

**Comment by rekire** [comment]
I don't think that that API is a good idea anymore. When I call the method I get this strange windows message. That is scary as hell lol.
![grafik](https://user-images.githubusercontent.com/4619618/94789037-b6d08100-03d4-11eb-9302-84cc8340f8bf.png)

**Comment by rekire** [comment]
Here is my WIP code if you want to try it yourself: https://github.com/rekire/flutter_secure_storage_windows
Please notice the warnings.

**Comment by JohnGalt1717** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata?redirectedfrom=MSDN

Combined with https://docs.microsoft.com/en-us/dotnet/standard/io/isolated-storage 

Should get the windows side done. Depending on how secure you want it, you could get away with the later and not the former.

**Comment by rekire** [comment]
I found today the Windows Hello API, not absolut related but might be a nice extension. You can use the API to get a secret (just a encrytion key I guess) via Biometrics or PIN (see the [documentation](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-overview), but to be honest I'm not sure if that is the best part of the documentation since this seems to be related to cloud projects)

It got the impression that this API required .net not sure if that is true. However I found this project which uses that API for a password manager which might be helpful: https://github.com/Angelelz/WinHelloUnlock

**Comment by rekire** [comment]
@JohnGalt1717 I am not really sure, but did you check my experimental code? I guess that this requires ugly dialog from my screenshot above. I think that is not a transparent API as the user of this plugin would expect. Even my windows hello API idea does not match the "transparent" usage requirement.

**Comment by JohnGalt1717** [comment]
@rekire Looks like this is the only way then:

https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.dataprotection.dataprotectionprovider?view=winrt-19041

Which is available through project reunion outside of UWP.

**Comment by rekire** [comment]
Can you link that project reunion? I know the .net framework from the past (I guess 3.x times) and I remember that it is easy to call win32 from .net, but I don't know the other way around.

**Comment by JohnGalt1717** [comment]
https://docs.microsoft.com/en-us/windows/apps/project-reunion/get-started-with-project-reunion

Note the section on c++ code

**Comment by JohnGalt1717** [comment]
Alternatively you can create a in memory file system on Windows that is actually backed by the real file system, and use that to write encrypted data that will automatically stream encrypted onto the real file system and visa-versa. Obviously it would be better if Windows did it itself.

**Comment by juliansteenbakker** [comment]
macOS will be tracked in #106
