### ISSUE TITLE
Unable to execute Dex

### ISSUE THREAD

**Issue by bilalsha** [mogol/flutter_secure_storage#158]
I am getting this issue while I am trying to build a project or APK. If I remove `flutter_secure_storage`, the project builds and APK is generated.

<img width="1181" alt="Screenshot 2020-09-15 at 2 33 05 PM" src="https://user-images.githubusercontent.com/6153951/93194067-19811600-f761-11ea-84c2-5dfb1c305668.png">

**Comment by juliansteenbakker** [comment]
Please try again with latest code on develop branch and report if it's still not working
