### ISSUE TITLE
Getting "Could not find method google() for arguments [] on repository container." error

### ISSUE THREAD

**Issue by alpeshgaglani** [mogol/flutter_secure_storage#16]
I am getting this error when building my flutter code for Android. Here's the verbose output:
[  +77 ms] [c:\Sources\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +97 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [c:\Sources\flutter\] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [c:\Sources\flutter\] git ls-remote --get-url origin
[  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [c:\Sources\flutter\] git log -n 1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [c:\Sources\flutter\] git log -n 1 --pretty=format:%ar
[  +39 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 6 weeks ago
[        ] [c:\Sources\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +43 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca37
[ +288 ms] C:\Users\alpes\AppData\Local\Android\Sdk\platform-tools\adb devices -l
[  +30 ms] Exit code 0 from: C:\Users\alpes\AppData\Local\Android\Sdk\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[ +161 ms] Found plugin flutter_secure_storage at c:\Sources\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.1.0\
[  +12 ms] Found plugin flutter_webview_plugin at c:\Sources\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.1.6\
[  +47 ms] Found plugin shared_preferences at c:\Sources\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.2.5\
[  +81 ms] C:\Users\alpes\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell getprop
[  +74 ms] ro.hardware = ranchu
[  +25 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[+1035 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +11 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Users\alpes\Downloads\flutter_template\android\gradlew.bat.
[ +117 ms] C:\Users\alpes\Downloads\flutter_template\android\gradlew.bat -v
[+1100 ms]
                   ------------------------------------------------------------
                   Gradle 3.3
                   ------------------------------------------------------------

                   Build time:   2017-01-03 15:31:04 UTC
                   Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

                   Groovy:       2.4.7
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b02)
                   OS:           Windows 10 10.0 amd64
[   +3 ms] Resolving dependencies...
[        ] [android\] C:\Users\alpes\Downloads\flutter_template\android\gradlew.bat app:properties
[+2712 ms] NDK is missing a "platforms" directory.
                   If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\alpes\AppData\Local\Android\sdk\ndk-bundle.
                   If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

                   NDK is missing a "platforms" directory.
                   If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\alpes\AppData\Local\Android\sdk\ndk-bundle.
                   If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

                   Incremental java compilation is an incubating feature.

                   BUILD FAILED

                   Total time: 2.504 secs

                   FAILURE: Build failed with an exception.

                   * Where:
                   Build file 'C:\Sources\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.1.0\android\build.gradle' line: 6

                   * What went wrong:
                   A problem occurred evaluating project ':flutter_secure_storage'.
                   > Could not find method google() for arguments [] on repository container.

                   * Try:
                   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[   +9 ms] * Error running Gradle:
           Exit code 1 from: C:\Users\alpes\Downloads\flutter_template\android\gradlew.bat app:properties:
           NDK is missing a "platforms" directory.
           If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\alpes\AppData\Local\Android\sdk\ndk-bundle.
           If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

           NDK is missing a "platforms" directory.
           If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\alpes\AppData\Local\Android\sdk\ndk-bundle.
           If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

           Incremental java compilation is an incubating feature.

           BUILD FAILED

           Total time: 2.504 secs

           FAILURE: Build failed with an exception.

           * Where:
           Build file 'C:\Sources\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.1.0\android\build.gradle' line: 6

           * What went wrong:
           A problem occurred evaluating project ':flutter_secure_storage'.
           > Could not find method google() for arguments [] on repository container.

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[  +36 ms] "flutter run" took 5,625ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:117)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:90)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:84)
<asynchronous suspension>
#4      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:88)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:272)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1501)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#17     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1126)
#21     _CustomZone.run (dart:async/zone.dart:1023)
#22     runZoned (dart:async/zone.dart:1501)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#26     new Future.sync (dart:async/future.dart:222)
#27     CommandRunner.run (package:args/command_runner.dart:109)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#35     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#36     run (package:flutter_tools/runner.dart:50)
#37     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#38     main (file:///C:/Sources/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Can someone please help?

**Comment by mogol** [comment]
Looks like you have outdated gradle plugin version `Gradle 3.3`.
For me
```
➜  android ./gradlew -v

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------
```

Please, check [android docs](https://developer.android.com/studio/releases/gradle-plugin#updating-plugin) and try to update gradle plugin.
