### ISSUE TITLE
minSdkVersion 

### ISSUE THREAD

**Issue by omerlewitz** [mogol/flutter_secure_storage#166]
Hey,

I encountered an issue with the minSdkVersion (I tried to play with the version but it did not helped)

The error

 Launching lib\main.dart on sdk gphone x86 in debug mode...
C:\Users\omerl\OneDrive\Desktop\blog-fronend-flutter\blog\android\app\src\debug\AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:flutter_secure_storage] C:\Users\omerl\OneDrive\Desktop\blog-fronend-flutter\blog\build\flutter_secure_storage\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 18,
		or use tools:overrideLibrary="com.it_nomads.fluttersecurestorage" to force usage (may lead to runtime failures)

**Comment by mogol** [comment]
Hi @omerlewitz 
The library requires minSdk 18 as mentioned in Readme.

**Comment by omerlewitz** [comment]
As i said its already 18

**Comment by p30arena** [comment]
@mogol 
Can't you lower it to 16?

**Comment by mogol** [comment]
No, I can not, due to lack of secure APIs before 18

**Comment by walinaqvi110** [comment]
Did you get any solutions yet?
