### ISSUE TITLE
A problem occurred configuring project ':flutter_secure_storage'. 

### ISSUE THREAD

**Issue by nonameclub** [mogol/flutter_secure_storage#167]
I cant build apk with release mode.

A problem occurred configuring project ':flutter_secure_storage'.       
> Failed to notify project evaluation listener.                         
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

**Comment by cheapestorderconcept** [comment]
I have the same issue. Any solution yet?

**Comment by cheapestorderconcept** [comment]
I have the same issue. Any solution yet?

**Comment by juliansteenbakker** [comment]
Please try again using the latest version v4.2.0. If it's still exists, feel free to comment.
