### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by jjsebastianfuertes** [mogol/flutter_secure_storage#168]
PlatformException(Exception encountered, read, java.lang.IllegalStateException: Cipher not initialized
I/flutter (32076): 	at javax.crypto.Cipher.checkCipherState(Cipher.java:1640)
I/flutter (32076): 	at javax.crypto.Cipher.doFinal(Cipher.java:2047)
I/flutter (32076): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:91)
I/flutter (32076): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:163)
I/flutter (32076): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:144)
I/flutter (32076): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$300(FlutterSecureStoragePlugin.java:29)
I/flutter (32076): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:197)
I/flutter (32076): 	at java.lang.Thread.run(Thread.java:919)
I/flutter (32076): , null)

**Comment by koskimas** [comment]
Are you running the latest version (3.3.5)? If not, could you try to update and see if the problem persists.

**Comment by TMSantos** [comment]
Had same error, and I confirm that 3.3.5 fixed it.

**Comment by jjsebastianfuertes** [comment]
Yes, 3.3.5 but still having some crashes due to this problem. If needed this is my setup

`[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-EC)
    • Flutter version 1.22.1 at /Users/jjsebastianfuertes/flutter
    • Framework revision f30b7f4db9 (13 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jjsebastianfuertes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • A2E16815-9D1A-42A1-9B46-9ED884E9FC92 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
`
