### ISSUE TITLE
Performance limits on Android

### ISSUE THREAD

**Issue by eimermusic** [mogol/flutter_secure_storage#171]
I have run into what seems like performance limits on Android. Are there any guidelines or safe rate limits that are known?

Here is what I have observed:

- Calling `await storage.read(key:myKey);` too often can occasionally return nonsense values or result in exceptions.
- Anecdotally this seems to be somewhat related to the general performance of the phone. Newer phones do better than older.
- Possibly, I have managed to call `read` while a `write` is still completing in some way. Difficult to be sure about async behavior.

I have not managed to log any similar events on iOS. It seems to be something related to the implementation on Android. The end result is that I can randomly get a bad response.

I imagine this could be caused by one of the limitations of SharedPreferences? 
https://github.com/flutter/flutter/issues/15307

Feels like shared prefs may not be suitable for "secure storage"? Or at least has different design and performance characteristics to iOS Keychain.

**Comment by koskimas** [comment]
Versions before 3.3.5 had thread safety issues that caused crashes, random results etc. if you happened to make two any kind of calls in parallel. Those issues were fixed in 3.3.5. Please make absolutely sure you are using the latest version (clear flutter caches, etc.) and try again.
