### ISSUE TITLE
item stored in secure storage is returning null after a period of time

### ISSUE THREAD

**Issue by GusRodrigues86** [mogol/flutter_secure_storage#173]
Probably not a bug or a true issue, but may need help to understand:
I'm storing in my app a token using secure_storage. 
From cycles of 2 hours after the last time the app was open/run when we read the key associated with the token, it returns null.

how could I prevent this from happening?

**Comment by GusRodrigues86** [comment]
Conflicting implementation causing memory to be flushed

**Comment by TMSantos** [comment]
Hey @GusRodrigues86 you closed this without further explanation, did you found what the problem is? I have this problem also, and is being hard to find the cause of it

**Comment by GusRodrigues86** [comment]
@TMSantos, ensure that you are calling the readAll() on initialization of your app.

```
Future<void> main() async {
  // Allow device information capturing
  WidgetsFlutterBinding.ensureInitialized();
  await SecureStorage().init();
```
and the init() is
````
await _storage.readAll();
````
just remember to follow some good practices of what and what you are storing as a DS for later use after reading from secure store.

**Comment by TMSantos** [comment]
@GusRodrigues86 thanks for your reply, do you know the reason behind that? it doesn't sound that readAll and read is that much different in the native methods

**Comment by GusRodrigues86** [comment]
My understanding is that without a initial readAll, you secure storage will never look into the keychain/keystore for values at all. So the initial condition for the reference is always {}.

but you need this call once the app is initialized. if you put on main, it will always work

**Comment by pkhivesara** [comment]
@GusRodrigues86 Did adding the ``await _storage.readAll();`` line fix the issue for you? We are having the same issue on both platforms. Using 3.3.5.

**Comment by GusRodrigues86** [comment]
> @GusRodrigues86 Did adding the `await _storage.readAll();` line fix the issue for you? We are having the same issue on both platforms. Using 3.3.5.

Yes. After getting the instance, readAll(), then check if it contains the desired key

**Comment by beerpcc** [comment]
I'm still have this problem. after a period of time (for me, like next day), open the app and data will be null. and after restart the app. the data can read. i need to open the app twice at first time of the day, every day.

Don't know how to fix. already add `await _storage.readAll();` in `main()`

**Comment by beerpcc** [comment]
> I'm still have this problem. after a period of time (for me, like next day), open the app and data will be null. and after restart the app. the data can read. i need to open the app twice at first time of the day, every day.
> 
> Don't know how to fix. already add `await _storage.readAll();` in `main()`

Fixed by this [https://github.com/mogol/flutter_secure_storage/issues/245](url)
