### ISSUE TITLE
Exception on Xiaomi devices after release to google store v3.3.5, 3.3.4

### ISSUE THREAD

**Issue by Pablo-Aldana** [mogol/flutter_secure_storage#174]
Hi,

I came to a weird error it took me a lot to debug as it only happens when you bundle the app, upload it into the store and upgrade the current installed versions. If you install it for the first time, works, if you run "flutter run --release" works, and any other possible combinations.  It works in any other Android and iOS device, just failing on Xiaomi

My thoughts is, after you install the app and the storage is created, if you upgrade to a new version of the app through play store, when running it tries to decypher the storage and fails for any reason. I couldn't see the error as it only happens when you run the app from the market and not debugging.  I used the storage for storing the login credentials so it breaks my app at starting. This is the current code:

Partial code of main.dart
```
 home: FutureBuilder(
          future: check,
          builder: (context, snapshot) {
            if (!snapshot.hasData) {
              print("no data");
              return Container(
                  decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage("assets/background.jpg"),
                  fit: BoxFit.cover,
                ),
              ));
            }

            if (snapshot.data) {
              return App();
            } else {
              return WelcomeScreen();
            }
          }),
    );
  }
}

Future<bool> get check async {
  return await init().catchError((e) {
    print("Got error: ${e.error}"); // Finally, callback fires.
    return false; // Future completes with 42.
  });
}

```

partial code of controller.dart
```
final storage = FlutterSecureStorage();
Future<bool> init() async {
  String jwt = await storage.read(key: "jwt");
  String user = await storage.read(key: "user");
  String password = await storage.read(key: "password");
  bool userLogged = false;
  if (jwt != null && jwt != "") {
    if (await login(user, password) == LOGGED) {
      userLogged = true;
      //await storage.delete(key: "jwt");
    }
  }
  return userLogged;
}
```

I cannot provide the error thrown as mentioned but I came around a workaround in case someone is facing the same issue and this hasn't been fixed it was as easiest as controlling the exception while reading the storage. Surprisingly when you upgrade now, the storage it is still there and user logins automatically so not really sure why exactly could throw an exception 

```
Future<bool> init() async {
  String jwt;
  String user;
  String password;
  bool userLogged = false;
  try {
    jwt = await storage.read(key: "jwt");
    user = await storage.read(key: "user");
    password = await storage.read(key: "password");
  } catch (error) {
    return userLogged;
  }

  if (jwt != null && jwt != "") {
    if (await login(user, password) == LOGGED) {
      userLogged = true;
      //await storage.delete(key: "jwt");
    }
  }
  return userLogged;
}
``` 

Do not hesitate to let me know if I can help you solving this issue happy to help :)

**Comment by juliansteenbakker** [comment]
Can you please try again with the develop branch of this plugin and comment if you are still having this issue.
