### ISSUE TITLE
Access flutter secure storage values from native android app service

### ISSUE THREAD

**Issue by OGmetamonkey** [mogol/flutter_secure_storage#178]
I am using flutter secure storage to write a value in Flutter like this:

`r = "whatever_string"`
`await storage.write(key: 'master', value: r);`

I can retrieve the value in flutter like this:

`await storage.read(key: 'master')`

... but I am launching an android service thread (kotlin code) and that thread is called by the native android autofill service.  I need that service thread to have access to the flutter secure storage value ('master') without launching the flutter engine. Can I do this?

**Comment by mogol** [comment]
Technically it's possible, you could try to use [FlutterSecureStoragePlugin.java](https://github.com/mogol/flutter_secure_storage/blob/develop/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java ) directly. However I didn't test such use case, some modification might be required

**Comment by rubenaster** [comment]
That's a great hint!

Is there a way to use the class directly from the imported library package? When I want to import the package or reference the class I don't get any options.
