### ISSUE TITLE
Add the ability to query wether StorageCipher is initialized

### ISSUE THREAD

**Issue by NANASHI0X74** [mogol/flutter_secure_storage#180]
I've noticed the same problem as #116 but in my app I immediately try to read a key from the storage as part of the initial setup before calling runApp to see if the user is logged in. If I were able to ask the FlutterSecureStorage wether it's been initialized I could skip the read if it isn't and maybe fire off a seperate thread that does the initialization in the background.

Would it make sense to try and add such a functionality?

This can be marked as an enhancement

**Comment by mogol** [comment]
@NANASHI0X74 do you read from Dart or Android code? 
If it's from Dart code, I believe, there is existing Flutter SDK API you can use - https://api.flutter.dev/flutter/widgets/WidgetsFlutterBinding/ensureInitialized.html

```
main(){
WidgetsFlutterBinding.ensureInitialized();
//.. access your storage

runApp(...);

}
```
