### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by sm2017** [mogol/flutter_secure_storage#182]
Is this warning important?

> Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.5\android\src\main\java\com\it_nomads\fluttersecurestorage\ciphers\RSACipher18Implementation.java uses or overrides a deprecated API.

**Comment by martinlaregina** [comment]
Hi,

I suppose soon will fixed when this change are merged.

https://github.com/mogol/flutter_secure_storage/commit/b8d92903e8ded04ce18eea97bedd66003f5bbd61
