### ISSUE TITLE
StorageCipher initialization failed on Android 11 (Pixel 5)

### ISSUE THREAD

**Issue by haydgately** [mogol/flutter_secure_storage#191]
I have seen reports of this being fixed in version 3.3.5 but am still seeing issues with this. 

E/FlutterSecureStoragePl(15899): java.security.InvalidKeyException: Keystore operation failed
E/FlutterSecureStoragePl(15899): 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1378)

`D/FlutterSecureStoragePl(15899): Initializing StorageCipher
[ +120 ms] E/FlutterSecureStoragePl(15899): StorageCipher initialization failed
[        ] E/FlutterSecureStoragePl(15899): java.security.InvalidKeyException: Keystore operation failed
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1378)
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1388)
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
[        ] E/FlutterSecureStoragePl(15899): 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
[        ] E/FlutterSecureStoragePl(15899): 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2877)
[        ] E/FlutterSecureStoragePl(15899): 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
[        ] E/FlutterSecureStoragePl(15899): 	at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
[        ] E/FlutterSecureStoragePl(15899): 	at javax.crypto.Cipher.init(Cipher.java:1143)
[        ] E/FlutterSecureStoragePl(15899): 	at javax.crypto.Cipher.init(Cipher.java:1084)
[        ] E/FlutterSecureStoragePl(15899): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.wrap(RSACipher18Implementation.java:44)
[        ] E/FlutterSecureStoragePl(15899): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:56)
[        ] E/FlutterSecureStoragePl(15899): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
[        ] E/FlutterSecureStoragePl(15899): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
[        ] E/FlutterSecureStoragePl(15899): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
[        ] E/FlutterSecureStoragePl(15899): 	at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/FlutterSecureStoragePl(15899): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/FlutterSecureStoragePl(15899): 	at android.os.Looper.loop(Looper.java:223)
[        ] E/FlutterSecureStoragePl(15899): 	at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] E/FlutterSecureStoragePl(15899): Caused by: android.security.KeyStoreException: Too many operations
[        ] E/FlutterSecureStoragePl(15899): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
[        ] E/FlutterSecureStoragePl(15899): 	... 20 more`

Has anyone managed to resolve this properly yet?

**Comment by GyuriMajercsik** [comment]
We are seeing this as well, using v3.3.5

**Comment by koskimas** [comment]
Reports like these are useless. You need to provide a way to reproduce the problem. At least provide the code or steps you took to get the error. The maintainers would have fixed this bug if they could just by reading stack traces.

**Comment by pedrovarela86** [comment]
> Reports like these are useless. You need to provide a way to reproduce the problem. At least provide the code or steps you took to get the error. The maintainers would have fixed this bug if they could just by reading stack traces.

It is not useless. it clearly says the reason

E/FlutterSecureStoragePl(15899): java.security.InvalidKeyException: Keystore operation failed
E/FlutterSecureStoragePl(15899): at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1378)

And it is true, it started failing without even changing my code.

**Comment by haydgately** [comment]
Yes it was working fine, but without doing any release or code changes it stopped working! Seems to be something system level that stops the library working, had the same behaviour at least from the NHS Covid app at the same time. Google did a security and bug fix update in December that after it, both apps seemed to work fine thereafter. 

However, issues on a Samsung Galaxy A21 still persist for some users, getting this error and a black screen when opening the app. No amount of clearing cache/storage and uninstalling works either, the app has now become impossible for them to launch sadly.

**Comment by rvoortman** [comment]
The problem @haydgately is describing ("a black screen when opening the app. No amount of clearing cache/storage and uninstalling works either, the app has now become impossible for them to launch") is probably also the problem we are facing with our app. 

Since we can't reproduce the problem ourselves, we can't provide steps to reproduce, but quite a few customers of ours seem to have this problem. It's hard for us to get logs, since the app can't send that information to us, since it won't start.

**Comment by Nailer** [comment]
Seconding this! Been using the library without any problems since early December. Suddenly it has stopped working. I have tested the same app on three different Pixel phones with stock android.
* Pixel 1 works (Android 10)  , 
* Pixel 2 works (Android 11, October 2020 security update), 
* Pixel 5 crashes (Android 11, December 2020 security update).

**Comment by Nailer** [comment]
I think I have narrowed it down to the fact that my Pixel 5 is reading old app data from my older phones, which means that the encryption details have changed. Preventing the stored data from being backed up and restored to the cloud should fix the problem. 

I would also probably clear that key-value pair whenever I get a bad decrypt error so that subsequent attempts would just return null. We use this library for storing auth -tokens, so it's not a big deal to have the user have to log in again after changing device.

**Comment by DanielNovak** [comment]
We are seeing the same issue on our internal application (unrelated to this github project) - it started happening on Android 11 on Pixel 4, but the same app works fine on Pixel 2 (Android 11). We even tried factory reset and it didn't help. I retrieve the error code -38 which should be in the list of error codes in Keystore.java - but the public sources do not contain this specific error code (https://android.googlesource.com/platform/frameworks/base/+/master/keystore/java/android/security/KeyStore.java#75), maybe Pixel phones have a different implementation? ... I will report back if we find something.

**Comment by matpag** [comment]
@DanielNovak Probably the error you are seeing is this one: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/security/keymaster/KeymasterDefs.java;l=283;drc=14a82f79831856b0619901b179df017c4062d9b5

**Comment by juliansteenbakker** [comment]
Some fixes have been merged. Please try again using latest version or using develop branch. If you still experience this issue, feel free to comment.
