### ISSUE TITLE
App crashes when doing any secure storage read or write operation on IOS simulator - No exception logged

### ISSUE THREAD

**Issue by atulmodi** [mogol/flutter_secure_storage#195]
My app is simply crashing and I get the message "Lost connection to device" on IOS simulator when I am doing a secure storage write or read. 

It works fine on Android. 

Is there any permission that I need to add to the app or anything else access ios keychain?

**Comment by atulmodi** [comment]
Issue was unrelated. Closing.

**Comment by PaRaDoX50** [comment]
Hello! Did you find any solution. Experiencing the same crash.
