### ISSUE TITLE
[Question]: Does this plugin create a separate secure storage for each app?

### ISSUE THREAD

**Issue by futurelucas4502** [mogol/flutter_secure_storage#196]
For example if I was to store a bunch of things in the store on one app then open another app that ran delete all would the items from the store of the other app also get deleted?

**Comment by ItzNotABug** [comment]
Every App, either in Android or iOS, have their own sandboxed preferences directory which, unless you have `superuser` / `root` access, cannot be touched by other apps.

So the answer to your question would be **No**.
If you run `deleteAll()` in an app called `B`, then that wouldn't delete your bunch of things in app `A`.

**Comment by futurelucas4502** [comment]
Okay cool I just wanted to make sure as I've not developed for mobile before thanks
