### ISSUE TITLE
Depreciated API warning

### ISSUE THREAD

**Issue by futurelucas4502** [mogol/flutter_secure_storage#197]
So I run my app in debug on a physical device and get the following output:
```
Launching lib\main.dart on SM A705FN in debug mode...
lib\main.dart:1
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.5\android\src\main\java\com\it_nomads\fluttersecurestorage\ciphers\RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
App compiles fine and works fine but it's interesting as running it on a pixel 3 emulator doesn't give me the depreciated API warning

**Comment by fsayfitdinov** [comment]
I do have the same issue, any workarounds?

**Comment by futurelucas4502** [comment]
@fsayfitdinov mine still builds correctly it's just a depreciation warning not an error so for now its okay for users of the library to ignore it but I posted an issue in case the dev was unaware of the depreciation

**Comment by futurelucas4502** [comment]
Same as issue #162  I didn't notice it when creating this issue
