### ISSUE TITLE
Why not use apply instead of commit?

### ISSUE THREAD

**Issue by feinstein** [mogol/flutter_secure_storage#202]
The SharedPreferences editor apply() is more performant than commit(), so why not use it when we don't need the value being returned?

**Comment by mogol** [comment]
Hey @feinstein 
I don't have answer on top of my mind. Why is the problem ?

**Comment by feinstein** [comment]
Commit waits, apply is async.. Its on the android docs.

**Comment by phijma** [comment]
`commit()` returns a boolean value indicating if the write was (un)successful. `apply()` doesn't return anything. As the return value of commit() is not used at all at this point, I agree with @feinstein.
