### ISSUE TITLE
Use EncryptedSharedPreferences instead of SharedPreferences for Android

### ISSUE THREAD

**Issue by nilsmagnus** [mogol/flutter_secure_storage#203]
The current implementation for android uses SharedPreferences, wich will store the key in plaintext. If this is replaced with EncryptedSharedPreferences instead, the keys would also be encrypted. 

About storing data securely on android:
https://developer.android.com/topic/security/data

About EncryptedSharedPreferences:
https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences

**Comment by nilsmagnus** [comment]
I created a gist here to create an instance of EncryptedSharedPreferences:

https://gist.github.com/nilsmagnus/006d9e7ce3b99913df64aa86f8924fe8

**Comment by matpag** [comment]
While I think this is a good proposal, it has 2 problems:
1) Would break compatibility with currently installed keys
2) Security library is still in alpha

**Comment by mogol** [comment]
@nilsmagnus :+1: thanks

what's your opinion on the @matpag 's points?

**Comment by nilsmagnus** [comment]
@mogol / @matpag I agree in both points. It would be a breaking change, so maybe it fits for the next major version and when the the security library is out of alpha?

 However, I need this functionality so I will probably be using a fork of this library as long as the key is not encrypted.

**Comment by mogol** [comment]
One way of implementing is to add an option for initialization, e.g. use EncryptedSharedPreferences or Keystore

**Comment by nilsmagnus** [comment]
@mogol @matpag: I updated the pr with option to use encryptedSharedPreferences. The security-library is still in alpha, but I cannot do anything about that now.

**Comment by matpag** [comment]
You increased minSDK to 23 while seecurity library can operate with minSDK 21, but for API 21-22 library will not use the AndroidKeyStore because it seems a bit unsecure as per the description here: https://developer.android.com/jetpack/androidx/releases/security#security-crypto-1.1.0-alpha01

**Comment by matpag** [comment]
After 2 years Security 1.0.0 is finally stable: https://developer.android.com/jetpack/androidx/releases/security#1.0.0

**Comment by juliansteenbakker** [comment]
This has been implemented in #259
