### ISSUE TITLE
flutter_secure_storage package and AppStore Export Compliance 

### ISSUE THREAD

**Issue by andriy-gulak-ew** [mogol/flutter_secure_storage#205]
I'm using flutter_secure_storage in my app and I want to clarify one moment regarding AppStore Export Compliance. 
Do I need to choose 'Yes' here if I use flutter_secure_storage?
![image](https://user-images.githubusercontent.com/42183561/107875897-2d28d800-6ecb-11eb-945d-f64fc24a9d18.png)

**Comment by mogol** [comment]
Hey @andriy-gulak-ew 
The data is stored in iOS Keychain, according to https://developer.apple.com/forums/thread/47634 and https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations looks like it is exempt from export documentation upload requirements.

**Comment by andriy-gulak-ew** [comment]
Hey @mogol 
Got it, good news then :) 

Thanks for your feedback!
