### ISSUE TITLE
Application crashes since yesterday  on  android-arm64 • Android 11 (API 30)

### ISSUE THREAD

**Issue by davidgregorGIS** [mogol/flutter_secure_storage#206]
`E/FlutterFcmService( 9406): Fatal: failed to find callback
D/FlutterSecureStoragePl( 9406): Initializing StorageCipher
I/fluttersecurestorage( 9406): Creating keys!
I/fluttersecurestorage( 9406): Initializing
I/fluttersecurestorage( 9406): Generating key pair
E/KeyStore( 9406): generateKeyInternal failed on request -68
Syncing files to device Mi A3...                                   742ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Mi A3 is available at: http://127.0.0.1:57234/NhkXRSgj-Z4=/
E/StorageCipher18Impl( 9406): unwrap key failed
E/StorageCipher18Impl( 9406): java.security.InvalidKeyException: Failed to unwrap key
E/StorageCipher18Impl( 9406):   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:682)
E/StorageCipher18Impl( 9406):   at javax.crypto.Cipher.unwrap(Cipher.java:2440)
E/StorageCipher18Impl( 9406):   at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.unwrap(RSACipher18Implementation.java:54)
E/StorageCipher18Impl( 9406):   at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:44)
E/StorageCipher18Impl( 9406):   at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
E/StorageCipher18Impl( 9406):   at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
E/StorageCipher18Impl( 9406):   at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
E/StorageCipher18Impl( 9406):   at android.os.Handler.handleCallback(Handler.java:938)
E/StorageCipher18Impl( 9406):   at android.os.Handler.dispatchMessage(Handler.java:99)
E/StorageCipher18Impl( 9406):   at android.os.Looper.loop(Looper.java:223)
E/StorageCipher18Impl( 9406):   at android.os.HandlerThread.run(HandlerThread.java:67)
E/StorageCipher18Impl( 9406): Caused by: javax.crypto.IllegalBlockSizeException
E/StorageCipher18Impl( 9406):   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
E/StorageCipher18Impl( 9406):   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:680)
E/StorageCipher18Impl( 9406):   ... 10 more
E/StorageCipher18Impl( 9406): Caused by: android.security.KeyStoreException: Unknown error
E/StorageCipher18Impl( 9406):   at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
E/StorageCipher18Impl( 9406):   at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:176)
E/StorageCipher18Impl( 9406):   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
E/StorageCipher18Impl( 9406):   ... 11 more
D/FlutterSecureStoragePl( 9406): StorageCipher initialization complete
I/runeantwort.fm( 9406): Waiting for a blocking GC ProfileSaver
E/flutter ( 9406): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E/flutter ( 9406):      at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
E/flutter ( 9406):      at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
E/flutter ( 9406):      at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
E/flutter ( 9406):      at javax.crypto.Cipher.doFinal(Cipher.java:2055)
E/flutter ( 9406):      at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:91)
E/flutter ( 9406):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:162)
E/flutter ( 9406):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:143)
E/flutter ( 9406):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$300(FlutterSecureStoragePlugin.java:30)
E/flutter ( 9406):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:196)
E/flutter ( 9406):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 9406):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 9406):      at android.os.Looper.loop(Looper.java:223)
E/flutter ( 9406):      at android.os.HandlerThread.run(HandlerThread.java:67)
E/flutter ( 9406): , null)
E/flutter ( 9406): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 9406): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 9406): <asynchronous suspension>
E/flutter ( 9406): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 9406): #3      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:45:41)
E/flutter ( 9406): #4      Authorization.init (package:fmr/network_utils/authorization.dart:35:36)
E/flutter ( 9406): #5      FmrApp.build (package:fmr/main.dart:31:32)
E/flutter ( 9406): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
E/flutter ( 9406): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
E/flutter ( 9406): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9406): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 9406): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9406): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9406): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 9406): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9406): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9406): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 9406): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9406): #17     _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:285:11)
E/flutter ( 9406): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9406): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 9406): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9406): #21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 9406): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9406): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 9406): #24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter ( 9406): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9406): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9406): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 9406): #28     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
E/flutter ( 9406): #29     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
E/flutter ( 9406): #30     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
E/flutter ( 9406): #31     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
E/flutter ( 9406): #32     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
E/flutter ( 9406): #33     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
E/flutter ( 9406): #34     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
E/flutter ( 9406): #35     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 9406): #36     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9406): #37     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 9406): #38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 9406): #39     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 9406): #40     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9406): #41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter ( 9406): #42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 9406): #43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter ( 9406): #44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter ( 9406): #45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 9406):`

**Comment by Peet-A** [comment]
same is here ,  any update !

**Comment by marcobraghim** [comment]
Some news on it? Same issue here...

```
D/FlutterSecureStoragePl( 7579): Initializing StorageCipher
I/fluttersecurestorage( 7579): Creating keys!
I/fluttersecurestorage( 7579): Initializing
I/fluttersecurestorage( 7579): Generating key pair
E/KeyStore( 7579): generateKeyInternal failed on request -68
E/FlutterSecureStoragePl( 7579): StorageCipher initialization failed
E/FlutterSecureStoragePl( 7579): java.security.ProviderException: android.security.keystore.StrongBoxUnavailableException: Failed to generate key pair
E/FlutterSecureStoragePl( 7579): 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:487)
E/FlutterSecureStoragePl( 7579): 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createKeys(RSACipher18Implementation.java:177)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:120)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:38)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
E/FlutterSecureStoragePl( 7579): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
E/FlutterSecureStoragePl( 7579): 	at android.os.Handler.handleCallback(Handler.java:938)
E/FlutterSecureStoragePl( 7579): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/FlutterSecureStoragePl( 7579): 	at android.os.Looper.loopOnce(Looper.java:201)
E/FlutterSecureStoragePl( 7579): 	at android.os.Looper.loop(Looper.java:288)
E/FlutterSecureStoragePl( 7579): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/FlutterSecureStoragePl( 7579): Caused by: android.security.keystore.StrongBoxUnavailableException: Failed to generate key pair
E/FlutterSecureStoragePl( 7579): 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:584)
E/FlutterSecureStoragePl( 7579): 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:475)
E/FlutterSecureStoragePl( 7579): 	... 13 more
E/FlutterSecureStoragePl( 7579): Caused by: android.security.KeyStoreException: No StrongBox available
E/FlutterSecureStoragePl( 7579): 	... 15 more

```

**Comment by hsul4n** [comment]
Any updates??

**Comment by PieterAelse** [comment]
Since recently I'm also running into this issue on a device and app where the package was working fine before.. Very suspicious.
But even worse, because of the crash the app doesn't load past the splashscreen! 💥 

@mogol Do you have any idea what might be causing this issue? How to fix? (or workaround)

Stacktrace:

> 2021-04-04 15:10:16.358 30269-30333/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
>         at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
>         at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
>         at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
>         at javax.crypto.Cipher.doFinal(Cipher.java:2055)
>         at d.g.a.b.b.b(Unknown Source:32)
>         at d.g.a.a.b(Unknown Source:11)
>         at d.g.a.a.d(Unknown Source:7)
>         at d.g.a.a.a(Unknown Source:0)
>         at d.g.a.a$b.run(Unknown Source:160)
>         at android.os.Handler.handleCallback(Handler.java:938)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>     , null)
>     #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
>     #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
>     <asynchronous suspension>
>     #2      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:45)
>     <asynchronous suspension>
>     #3      [myClass.myMethod] (package:[myFile).dart:20) (redacted)
>     <asynchronous suspension>
>     #4      Cast.cast.<anonymous closure> (package:utils/src/futures.dart)
>     <asynchronous suspension>

**Comment by juliansteenbakker** [comment]
A fix has been merged. Please try again using latest code on develop branch.
