### ISSUE TITLE
Need help: Migration from existing app to flutter

### ISSUE THREAD

**Issue by HannesVDB** [mogol/flutter_secure_storage#211]
We're migrating an existing iOS and Android app to a Flutter application.
Therefore we want to read existing information from the Keychain inside our new application.
When I try to fetch the value with the existing key. I don't get any results.
Is this even possible from within the package?

**Comment by mogol** [comment]
It should be possible after this MR would be merged #184 -> will do it this weekend

**Comment by mogol** [comment]
@HannesVDB please try the latest develop branch, it should support your case. You need to set accountName in IOSOptions to either a name of your account/service or null to access all entities (aka wildcard).

**Comment by mogol** [comment]
Closing the issue, @HannesVDB please re-open if it doesn't work for your case
