### ISSUE TITLE
Storing JWT token returns null?!

### ISSUE THREAD

**Issue by jbiddulph** [mogol/flutter_secure_storage#218]
I am using flutter_secure_storage and when I try to save write my JWT token to it, when I read it back, it comes back as null?!

```
secureStorage.writeSecureData('token', value.token);
                                    secureStorage.readSecureData('token').then((savedToken) => {
                                      Savedtoken = savedToken
                                    });
```

I know that value.token returns a JWT token at this point

**Comment by mogol** [comment]
@jbiddulph Does example app work for you?
