### ISSUE TITLE
 Read: key exists => Running ensureInitStorageCipher StorageCipher already initialized

### ISSUE THREAD

**Issue by chitgoks** [mogol/flutter_secure_storage#226]
After upgrading to the latest version i get this in a loop

any idea what is wrong?

**Comment by bohdan1krokhmaliuk** [comment]
same issue

**Comment by devaronius** [comment]
have the same problem.

`D/FlutterSecureStoragePl(12716): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(12716): StorageCipher already initialized`

**Comment by devaronius** [comment]
after a small search, this log row comes from the `FlutterSecureStoragePlugin.ensureInitStorageCipher()` and FlutterSecureStoragePlugin.run()
that is called inside each method type like write, read and delete.

that log   Log.d(TAG, "Read: key exists => Running ensureInitStorageCipher");
and checkeds if (storageCipher == null) else Log.d(TAG, "StorageCipher already initialized");

**Comment by juliansteenbakker** [comment]
Please try again using the latest branch. The master branch is not updated yet so please use develop.
