### ISSUE TITLE
No implementation found for method READ and WRITE in Flutter Secure Storage

### ISSUE THREAD

**Issue by whydea** [mogol/flutter_secure_storage#229]
Hello guys, I've been experiencing a problem for a few days now, I updated the flutter to version 2.0.3 and my flutter secure storage stopped working, even if I try to use the flutter keychain it doesn't work, I'm having read and write errors use in the project, I've tried everything I saw on the internet and I couldn't solve it in any way, has anyone had this problem and managed to solve it in some way?

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

• No issues found!

Errors:
E/flutter ( 6795): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
E/flutter ( 6795): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6795): <asynchronous suspension>
E/flutter ( 6795): #1      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50:27)
E/flutter ( 6795): <asynchronous suspension>
E/flutter ( 6795): #2      _MyLoginPageState.checkUserStatus (package:projeto_suinos/login.dart:38:21)
E/flutter ( 6795): <asynchronous suspension>

and

E/flutter ( 6397): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
E/flutter ( 6397): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6397): <asynchronous suspension>
E/flutter ( 6397): #1      _MyLoginPageState.build.<anonymous closure> (package:projeto_suinos/login.dart:125:29)

The implementation:

`final storage = new FlutterSecureStorage();`

```
void checkUserStatus() async {
    String userId = await storage.read(key: 'userId');

    if (userId != null) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => Menu(),
        ),
      );
    }
  }
```

```
if (newUser != null) {
                            await storage.write(
                              key: 'userId',
                              value: newUser.user.uid,
                            );

                            Toast.show(
                              "Sucesso",
                              context,
                              duration: Toast.LENGTH_SHORT,
                              gravity: Toast.CENTER,
                              backgroundColor: Colors.blueAccent,
                              textColor: Colors.white,
                            );
                            setState(() {
                              showProgress = false;
                            });

                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => Menu(),
                              ),
                            );
                          }
```

Pubspec:

flutter_secure_storage: ^4.1.0

**Comment by juliansteenbakker** [comment]
Have you solved this issue? Otherwise please try again with version 4.2.0 and comment if it's still an issue.

**Comment by htrampe** [comment]
Error is still there. Any ideas?

**Comment by mu7mmd** [comment]
Same error now in web, any one solved this?
