### ISSUE TITLE
Read: key exists => Running ensureInitStorageCipher and StorageCipher already initialized infinite logs

### ISSUE THREAD

**Issue by bismarabia** [mogol/flutter_secure_storage#231]
Too many appearance of these logs is very annoying

D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized
D/FlutterSecureStoragePl(16650): Read: key exists => Running ensureInitStorageCipher
D/FlutterSecureStoragePl(16650): StorageCipher already initialized

how can we prevent those logs from being logged in the logs?

**Comment by caseyryan** [comment]
The same on android 11 sdk API 30

**Comment by gmhz** [comment]
Same here. Would be great the author adds the ability to disable unnecessary logs

**Comment by juliansteenbakker** [comment]
This is not something i have encountered. Can everyone with this problem please post output of `flutter doctor -v`?

**Comment by caseyryan** [comment]
> This is not something i have encountered. Can everyone with this problem please post output of `flutter doctor -v`?

It doesn't matter, the bug does not depend on the version of flutter, I caught it in every possible version I used. 
I don't know exactly why and when it happens, but sometimes it happened when I installed a debug version over the version installed from Firebase and vice versa. I believe it's somehow related to the app certificate (but I'm not sure). This bug happened so often that I even had to replace this plugin with SharedPreferences

**Comment by juliansteenbakker** [comment]
With #270 you can now use the following code to enable EncryptedSharedPreferences:

```dart
  AndroidOptions _getAndroidOptions() => const AndroidOptions(
        encryptedSharedPreferences: true,
      );
```

This method doesn't use the custom StorageCipher but rather a Jetpack Compose library that automatically encrypts the data. Please note that on API < 23 it will fall back to the 'regular' secure storage.

Can you please try this after it has been merged?
