### ISSUE TITLE
error: package com.it_nomads.fluttersecurestorage does not exist

### ISSUE THREAD

**Issue by cyberboy2012** [mogol/flutter_secure_storage#237]
Hi, I met a problem where when I build the application, it shows there is error where the package is not exists. I am using the example code that provided at pub dev of the dependency ```flutter_secure_storage```. I have already change the ```minSdkVersion``` to 18.

Can I know is there any ways to fix this problem?

```
android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:16: error: package com.it_nomads.fluttersecurestorage does not exist
    flutterEngine.getPlugins().add(new com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin());
                                                                         ^
1 error
```

**Comment by MilesAdamson** [comment]
It is likely not an issue with this plug, but with how flutter registers plugins 
 
https://github.com/flutter/flutter/issues/66833#issuecomment-786646405

**Comment by juliansteenbakker** [comment]
This doesn't seem like an issue with the plugin so i'm closing it for now.
