### ISSUE TITLE
Android Keystore entry is deleted when app is uninstalled?

### ISSUE THREAD

**Issue by systemcode** [mogol/flutter_secure_storage#238]
Hi
Thanks for the plugin. I have been using it successfully on iOS for 6 months. Now trying to release an Android version and I find the behaviour is different.  I am new to Android and tried research on this, but it may be a dumb question. Should the key-value be retained after the app has been uninstalled?

Use-case:

1. Install App
2. Read key. If null then write key value.
3. Uninstall app.
4. Read key.   On iOS I get the saved value returned. On Android it returns null.

So should the key-value be retained after the app has been uninstalled?

**Comment by systemcode** [comment]
Ok so I have delved further into this and see that Android Keystore does get wiped on app deletion. 
Thus the plugin does exhibit different behaviour on iOS and Android so maybe that should be highlighted in the help or readme. 

Having said that... does anyone know how to securely persist a value across delete & reinstall?

**Comment by AliEasy** [comment]
@systemcode 
So what is your solution to store a value which persists after uninstall

**Comment by systemcode** [comment]
On ios this plugin is ok. On Android, I have failed to find a good method so had to rework my app.

**Comment by begandroide** [comment]
same problem here, at remove app on Android i need go to settings -> apps -> <my app> -> remove storage & cache, and again works. 

@systemcode  What you did it? 😮

**Comment by systemcode** [comment]
> 
> @systemcode  What you did it? 😮 

No I didn't

**Comment by begandroide** [comment]
I added a try catch when exception is triggered by uninstall and re-install application. if exception occurs so I instantiate the lib and remove all content from secure-storage, until issue is handled (anyway I don't believe that occurs)

**Comment by juliansteenbakker** [comment]
This is expected behavior on Android.

> Having said that... does anyone know how to securely persist a value across delete & reinstall?

You should encrypt your data and store it on the filesystem. However for now this is out of the scope of this package.

**Comment by AliEasy** [comment]
@juliansteenbakker 

> You should encrypt your data and store it on the filesystem

Could you please share a link about how we can do this
