### ISSUE TITLE
Unable to access keychain values from prior native app

### ISSUE THREAD

**Issue by danallen88** [mogol/flutter_secure_storage#241]
We have a native application used in production today that stores certain values that we want to be able to access in our Flutter app.  We're writing the Flutter app to be an update to the production app, so it uses the same exact bundle id, and when installed, overwrites the app as an update (rather than creating a second app).  I'm not sure it matters, but it is also using the same keychain-access-group.  I'm using the same keys for lookups in our Flutter app that the production application stores the values under in the keychain, but flutter_secure_storage does not return anything for those keys.  I confirmed the keys still exist in the keychain by uninstalling the Flutter app and reinstalling the native production app.

Is this use case supported by this plugin, and if so, is there additional configuration required to be able to access these values?

**Comment by danallen88** [comment]
I discovered that this was due to not supplying the `accountName` in the `IOSOptions` object, which defaulted to `flutter_secure_storage_service`.  Once I aligned that with our production application, I can see the keychain content.  Sorry for the distraction - but this may be a good item for documentation if others have this use case.

**Comment by pmas19** [comment]
"Hi @danallen88 , I have the same need as you, but I'm going crazy trying to figure out how to configure the iOSOptions. How should I set accountName and groupId? Where i find this data?"

**Comment by hungbv-0181** [comment]
@danallen88 could you please tell me how to find accountName in your native app?
