### ISSUE TITLE
In iOS Data Persists after uninstalling the application 

### ISSUE THREAD

**Issue by kotlincodes** [mogol/flutter_secure_storage#243]
Hi,

I am using this plugin and found that the Data stored are persisting after uninstalling the application from the device. In android data gets cleared after uninstall but in **iOS** it persists. How can I resolve this issue, I need to clear all the stored data once app is uninstalled from the **iOS** device.

Details

Device : iOS simulator -iOS 7 plus
flutter_secure_storage : 4.2.0

Expecting a Solution ASAP. Thanks.

**Comment by raphagodoi** [comment]
Same here

**Comment by juliansteenbakker** [comment]
Duplicate of #125
