### ISSUE TITLE
Specify the importance of IOSAccessibility options in the readme

### ISSUE THREAD

**Issue by ZaraclaJ** [mogol/flutter_secure_storage#245]
We encountered some unexpected behaviors on our iOS app in production because sometimes some keys stored in the secure storage return null. However we were sure that the value has been set before...
It took us a long time to understand why. Here is the reason : some users lock there phone before the app can access to the data.

 Indeed, by default, the IOSAccessibility option is set to :
 ```
// The data in the keychain item can be accessed only while the device is unlocked by the user.
IOSAccessibility.unlocked
```

That means that if you want to access secure storage when your app is in the backgroud or avoid problems when the user locks their phone, I recommend using another option :
 ```
// The data in the keychain item can be accessed only while the device is unlocked by the user.
// Items with this attribute do not migrate to a new device.
IOSAccessibility.first_unlock
```

It is clear that this option is less restrictive (less secure) but in my opinion it can be safer for most use cases.

I think the readme should explain in more detail the importance of this option so that the users of the package can choose the most suitable option for their need when installing the package.

**Comment by juliansteenbakker** [comment]
The readme has been updated in #244
