### ISSUE TITLE
CBC Ciphers

### ISSUE THREAD

**Issue by chrisDK1977** [mogol/flutter_secure_storage#249]
From an audit we got the response that our app which uses flutter_secure_storage uses weak ciphers as our app uses  CBC with PKCS5/PKCS7 padding and that this configuration is vulnerable padding oracle attacks and we should remove CBC ciphers..
Is there any solution we can implement using flutter_secure_storage?

**Comment by juliansteenbakker** [comment]
With #270 you can now use the following code to enable EncryptedSharedPreferences:

```dart
  AndroidOptions _getAndroidOptions() => const AndroidOptions(
        encryptedSharedPreferences: true,
      );
```

This method doesn't use the custom StorageCipher but rather a Jetpack Compose library that automatically encrypts the data. Please note that on API < 23 it will fall back to the 'regular' secure storage.
