### ISSUE TITLE
Repository maintainer

### ISSUE THREAD

**Issue by juliansteenbakker** [mogol/flutter_secure_storage#250]
It seems like there isn't much activity in this repository. Maybe it's an idea to add a maintainer to this repository @mogol, or we can fork this and fix all open issues.

**Comment by mogol** [comment]
I will be more than happy to get some help from the community. So I am open to idea of additional maintainers.

**Comment by juliansteenbakker** [comment]
@mogol I'm happy to be maintainer! I have experience with several other packages like qr_code_scanner and flutter_login.

**Comment by mogol** [comment]
It sounds perfect. Could you please drop email to discuss details to german dot saprykin at pm dot me?

**Comment by juliansteenbakker** [comment]
I have sent you an email.
