### ISSUE TITLE
java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key

### ISSUE THREAD

**Issue by DangLin012** [mogol/flutter_secure_storage#258]
I am using Redmi Note 8 Pro, after the mobile phone system is upgraded to MIUI 12.5.1, StorageCipher initialization failed will be reported.

07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:263)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:303)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:324)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:388)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:105)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at java.security.KeyStore.getKey(KeyStore.java:1062)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at d.d.a.b.a.b(Unknown Source:12)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at d.d.a.b.a.<init>(Unknown Source:28)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at d.d.a.b.b.<init>(Unknown Source:12)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at d.d.a.a.p(Unknown Source:8)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at d.d.a.a.a(Unknown Source:0)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at d.d.a.a$b.run(Unknown Source:148)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.os.Handler.handleCallback(Handler.java:938)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.os.Looper.loop(Looper.java:236)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: Caused by: android.security.KeyStoreException: Invalid key blob
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
07-26 17:49:01.702 20767 20823 E FlutterSecureStoragePl: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:265)

**Comment by DangLin012** [comment]
Reporting this error will cause the original data to be inaccessible. Someone has encountered a similar problem.

**Comment by juliansteenbakker** [comment]
I think the issue is that the OS upgrade tampered with the key, so it can't recover it anymore. I don't know how we can prevent this from happening.

**Comment by yfer** [comment]
i have the exact same problem with MIUI 12.5.2, Redmi Note 8 Pro.

**Comment by juliansteenbakker** [comment]
There are other problems reported with xiaomi devices like #200. I can't debug this because i don't have an Xiaomi device and can't reproduce this behavior.

**Comment by David-Mou** [comment]
I think this is the same as #200. I have a Xiaomi POCO in Android 11 but not with MIUI 12.5. This library is working as expected.

I think that MIUI 12.5 is the one generating this issue.

**Comment by David-Mou** [comment]
Deleting app data is enough for bypass this error (at least in my case). A workaround could be reset the KeyStore by code, providing a method to make that clean-up. Could this be done in the plugin @juliansteenbakker ?

**Comment by juliansteenbakker** [comment]
Deleting the data will regenerate all files and keys so that would indeed fix the problem. It could be a solution however since this will just delete all data we need to be careful with this. Maybe we can add a parameter like `resetOnError` which the dev can opt-in to.

**Comment by David-Mou** [comment]
I would like this parameter. In my case the issue is in the signIn/signUp step, so delete data is not an issue at all. I don't know where most devs have the problem, but It would not be weird that the one of the use case most used is about storing authentication stuff. 

With that paramenter, at least these issues will be solved!

**Comment by juliansteenbakker** [comment]
Please try again with version 5.0.0 and report if it still fails.
