### ISSUE TITLE
[BLOCKING] No implementation for containsKey on iOS, macOs, linux

### ISSUE THREAD

**Issue by jhancock4d** [mogol/flutter_secure_storage#266]
Not sure if this is that it just isn't implemented or if it's a bug in the platform interface for it although web calls the platform interface correctly. (doesn't look like it's implemented at all in the code for android or ios, linux,)

Web has a different bug and needs it's implementation changed to:

```
  @override
  Future<bool> containsKey({
    required String key,
    required Map<String, String> options,
  }) =>
      Future.value(html.window.localStorage
          .containsKey(options[_PUBLIC_KEY]! + "." + key));

```

Basically none but web implement contains key, which looks like it should be in one of the pull requests, and web's is wrong and needs to be fixed.

**EDIT: Right now we only need to develop a method for containsKey on iOS, macOs, linux. This is blocking a stable 5.0.0 release.**

**Comment by kennethnym** [comment]
i'll work on the windows implementation, then make a PR for it alongside readAll and deleteAll.

**Comment by jhancock4d** [comment]
Note for others: Web has been fixed and is in.  Looks like @kennethnym  has graciously committed to adding to windows. So just need this added to Android, iOS and macOS.

**Comment by kennethnym** [comment]
According to the docs, `read` returns null if the key doesn't exist in storage. Shouldn't `containsKey` be implemented entirely in Dart instead? It should just be a simple null check.

**Comment by jhancock4d** [comment]
@kennethnym That's not a valid test because null can be a valid entry in storage. Never use a read test on a value to test for existence of a key.

This should be implemented in code for each platform and actually check to see if the entry exists in whatever data store it's using and return a bool.  Anything else is asking for trouble.

**Comment by kennethnym** [comment]
That is a valid point. However, if a null value is given to `write`, the key is deleted instead, according to the documentation. At least on Windows, null values aren't possible in credential storage. How will null values get into the storage?

**Comment by kennethnym** [comment]
That is a valid point. However, if a null value is given to `write`, the key is deleted instead, according to the documentation. At least on Windows, null values aren't possible in credential storage. How will null values get into the storage?

**Comment by jhancock4d** [comment]
@kennethnym It shouldn't get into storage, BUT shouldn't and won't are 2 different things.  Every platform has the ability to check if a key exists or not, and should do so to implement the interface.

**Comment by kennethnym** [comment]
You are right 👍

**Comment by talhabalaj** [comment]
For Linux, it's implemented now. #295
