### ISSUE TITLE
5.0.0-beta.1 Android Errors on readAll with previous values from 4.x.x with default settings

### ISSUE THREAD

**Issue by jhancock4d** [mogol/flutter_secure_storage#267]
I believe this is because of the encrypted storage change.  Perhaps the defaults should be the same as the past? Otherwise something needs to be done so that it's backwards compatible and has a path to upgrade otherwise this will cause major issues with apps that depend on this library and I don't see any way to do a seamless migration that wouldn't cause end users issues.

Ideally it would use the new implementation, but when faced with the old values, would automatically migrate them to the new values and then store them and just work.

**Comment by juliansteenbakker** [comment]
Yes this is true, however encrypted shared preferences is a opt-in:
```dart
  AndroidOptions _getAndroidOptions() => const AndroidOptions(
        encryptedSharedPreferences: true,
      );
```

by default it will be false:

```java
    private boolean useEncryptedSharedPreferences(Map arguments) {
        return arguments.containsKey("encryptedSharedPreferences") && arguments.get("encryptedSharedPreferences").equals("true");
    }
```

A migration would be even better though

**Comment by jhancock4d** [comment]
Ok, well I'm thinking that the new encryptedSharedPreferences should store a bit flag that is set if the values are in the new encrypted stored preferences, and if not found or not set, but the flag is set, should read with the old verison, all of the values, and then write them all back with the new version and then set the bit.

That would make it transparent, and at the same time would allow defaulting this to true which seems like a good idea from what I understand.  Is that doable? I'm not a Java/Kotlin guy so I can't really help with this.

**Comment by juliansteenbakker** [comment]
That sound doable however i think this may be better for a later release. Right now the encryptedSharedPreference is not really tested by anyone, so i think it would be better for now to leave it as an opt in, and with a next release (v6.0.0) migrate it to an opt out with automatic migration. That way we can first test the implementation with v5.0.0 and improve it if necessary, and when everything is good start the migration proces.

**Comment by jhancock4d** [comment]
@juliansteenbakker Makes sense. It appears to be very reliable right now but I'll let you know if I find issues....

**Comment by juliansteenbakker** [comment]
I will add this request in a new ticket. Thanks!
