### ISSUE TITLE
Keychain items lost after app update installed from App Store

### ISSUE THREAD

**Issue by ToniTornado** [mogol/flutter_secure_storage#284]
Hi,

we are currently investigating an issue that caused data loss after the users installed our latest release. We already released a hotfix that made the app usable again but we would like to find the root cause of this issue to avoid it in the future. The loss of data, although painful, is bearable in our case, as we only had data in the encrypted database that we could retrieve again from the user by signing in and onboarding again.

Our app's version history:
1.0 Native iOS app
2.0 Flutter App with flutter_secure_storage 3.3.5
3.0 Flutter App with flutter_secure_storage 4.2.1 -> Crashed, not usable after update, fresh install works
3.1 Hotfix release with a fallback if decryption of data fails

The issue has happened ONLY on the latest store release, not in any of our testing stages before (dev/qa/prod). For the testing stages we sign the app with a different certificate, the store release is resigned with a company profile - so there is no easy way to reproduce or "try out".

Our app is pretty much following the implementation [from the Hive docs](https://docs.hivedb.dev/#/advanced/encrypted_box) to create an encrypted Hive box:

```dart
void main() async {
  final FlutterSecureStorage secureStorage = const FlutterSecureStorage();
  var containsEncryptionKey = await secureStorage.containsKey(key: 'key'); // <--- This returned probably false!
  if (!containsEncryptionKey) {
    var key = Hive.generateSecureKey();
    await secureStorage.write(key: 'key', value: base64UrlEncode(key));
  }
  
  var encryptionKey = base64Url.decode(await secureStorage.read(key: 'key'));
  print('Encryption key: $encryptionKey');

  // This line crashes when the key was recreated but the box already existed
  var encryptedBox = await Hive.openBox('vaultBox', encryptionCipher: HiveAesCipher(encryptionKey)); 
}
```

We were able to derive from the behavior of the released app that the `containsKey` call somehow returned false and thus the app created and stored a new encryption key. The app now crashed when trying to open the box with the wrong key. Our hotfix catches this error and creates a new empty box in this case so that the user is able to sign in again but the encryption key and all data in the existing box was lost.

**We see currently two possibilities:**

1. We lost all access to our keychain items
   This usually happens when BundleSeedID/TeamID or AppID changes but we verified this is not the case. Since it happened only with the resigned store release and not with any of the various test builds from TestFlight, this was our first thought but only the Associated Domains entitlement was added to the profile, everything else stayed the same.  Do you know any other reasons why our app might have lost access to its keychain items other than that?

2. The `containsKey` behavior changed from version 3.3.5 to 4.2.1
   We went with the default code from the example and did not specify `IOSOptions` at all, so no `accountName`/`serviceName`/access group was supplied by us. I recognized a commit that changed the `defaultAccountName` assume that our values ended up in the `flutter_secure_storage_service` default `accountName`. We think a change here is rather unlikely because we did not have any issue in any tested update scenario for dev/qa/prod. But we can't completely rule it out either, since we also had numerous intermediate versions installed for testing purposes, which may have affected the keychain.

Any input and other ideas on what might have happened are very welcome! 😊

**Comment by juliansteenbakker** [comment]
Unfortunately v4.2.1 had several issues regarding lost data. I hope with latest version 5.0.0 those issues won't happen.
