### ISSUE TITLE
Read a nonexists key cause an error "No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage"

### ISSUE THREAD

**Issue by khhily** [mogol/flutter_secure_storage#285]
I read a nonexist key, and got an error "No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage".
Because it returns a null value, flutter plugin in safety null it has a class named OptionalMethodChannel, this allow null value return. the MethodChannel class already don't allow null value return.

**Comment by juliansteenbakker** [comment]
Duplicate of #152
