### ISSUE TITLE
Windows `read` crashes if key doesn't exist yet

### ISSUE THREAD

**Issue by kennethnym** [mogol/flutter_secure_storage#287]
In the current implementation, the private `Read` method does return `nullopt` if the key doesn't exist, however, I didn't take this into account at call site, meaning I forgot to do a `has_value()` check before accessing `value()` and returning that value to the method channel. Should be an easy fix. Thanks for reporting.

_Originally posted by @kennethnym in https://github.com/mogol/flutter_secure_storage/issues/263#issuecomment-897881227_

**Comment by aquilarafa** [comment]
Same issue on  Android 10

**Comment by JsonLinesCode** [comment]
It's not resolved for me as I mentioned it in #290.

**Comment by kennethnym** [comment]
That is weird. I'll look into this when I'm free. @juliansteenbakker can you please reopen this issue? Thanks.

**Comment by Jon-Salmon** [comment]
I have tried and failed to reproduce this error so don't believe this is still an issue on the develop branch.
