### ISSUE TITLE
BIG ISSUE ( WINDOWS ) : It shares the data between two apps with the same key

### ISSUE THREAD

**Issue by topperspal** [mogol/flutter_secure_storage#294]
### STEPS TO RECREATE

1. Create two different apps with `flutter_secure_storage 5.0.0-beta.4.`
2. Open First app and save data using FlutterSecureStorage().write(key: "mykey", value: "my_highly_secured_key")
3. Open Second app and try to read the data using `FlutterSecureStorage().read(key: "mykey")`

You will be able to read the my_highly_secure_key from another app.

PLEASE FIX IT SOON

**Comment by juliansteenbakker** [comment]
This is fixed in #325 and will be released soon.

**Comment by topperspal** [comment]
If two apps are named same, they can read creds of each other :(. Please reopen this issue.

I have edited `STEPS TO RECREATE` above, please go through them :)
