### ISSUE TITLE
error: use of undeclared identifier 'flutter_secure_storage_linux_plugin_register_with_registrar' on Linux

### ISSUE THREAD

**Issue by fatimahossny** [mogol/flutter_secure_storage#298]
I got this err while building for linux platform , I use version ` flutter_secure_storage: ^5.0.0-beta.4`
 `error: use of undeclared identifier 'flutter_secure_storage_linux_plugin_register_with_registrar'; did you mean 'flutter_secure_storage_plugin_register_with_registrar'?`
 any help please , thanks in advance

**Comment by juliansteenbakker** [comment]
Merged and will be released later today
