### ISSUE TITLE
broken build in latest flutter

### ISSUE THREAD

**Issue by Rockvole** [mogol/flutter_secure_storage#30]
flutter_secure_storage: 3.1.2

Latest flutter build on ios gives :

	flutter build ios
	Building com.rockvole.kbmlViewer for device (ios-release)...
	Automatically signing iOS for device deployment using specified development team
	in Xcode project: SQ4ZRAJ4V2
	Running pod install...                                       3.1s
	Starting Xcode build...                                          
	Xcode build done.                                            5.8s
	Failed to build iOS app
	Error output from Xcode build:
	↳
		** BUILD FAILED **

	Xcode's output:
	↳
		/Users/david/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.2
		/ios/Classes/FlutterSecureStoragePlugin.m:87:49: warning: values of type
		'OSStatus' should not be used as format arguments; add an explicit cast to
		'int' instead [-Wformat]
					NSLog(@"SecItemUpdate status = %d", status);
												   ~~   ^~~~~~
												   %d   (int)
		/Users/david/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.1.2
		/ios/Classes/FlutterSecureStoragePlugin.m:95:46: warning: values of type
		'OSStatus' should not be used as format arguments; add an explicit cast to
		'int' instead [-Wformat]
					NSLog(@"SecItemAdd status = %d", status);
												~~   ^~~~~~
												%d   (int)
		3 warnings generated.
		<module-includes>:1:1: warning: umbrella header for module 'Flutter' does
		not include header 'FlutterNavigationController.h' [-Wincomplete-umbrella]
		#import "Headers/Flutter.h"
		^
		1 warning generated.
		1 warning generated.

	Encountered error while building for device.

**Comment by Rockvole** [comment]
Never mind - it resolved after updating another plugin.

**Comment by uscagr** [comment]
Hey, we are having the same issue on bitrise, what packages you updated for a succesful build?

**Comment by khalithartmann** [comment]
would like to know too ... did you resolve ?

**Comment by sotoyjuan** [comment]
Same here. What was the fix.
