### ISSUE TITLE
macOS - containsKey is always returning true

### ISSUE THREAD

**Issue by kineticac** [mogol/flutter_secure_storage#302]
No matter what key I'm passing for the `containsKey` function, this always returns true the first time on a macOS build.

Is anyone else getting this issue? Let me know what other information you might need to help resolve.

**Comment by pikawika** [comment]
I have the same issue on iOS Iphone 12 simulator -> containsKey returns true but read returns null, used to work on stable release. temporary bypass for me is a function to check contains by calling
`await _secureStorage.containsKey(key: _tokenKey) && await _secureStorage.read(key: _tokenKey) != null;`

**Comment by juliansteenbakker** [comment]
Please try again using the latest v5.0.0. If issue still exists feel free to comment.

**Comment by AgustinV08** [comment]
Problem still exists in package 5.0.2

**Comment by jscti** [comment]
+1

Pretty critical/hardcore bug when you use this function to check if a user is LoggedIn or not ...

Maybe this plugin is not so secure ^^

**Comment by juliansteenbakker** [comment]
> Pretty critical/hardcore bug when you use this function to check if a user is LoggedIn or not ...

You should not use this function to check if a user is logged in or not. You should read the actual data that it has and check if it is still valid or not expired like a token.

**Comment by jscti** [comment]
It's up to me and you don't know of any of the other technical details. If you think containsKey has no use, remove it from the lib

But yeah now that containsKey is totally broke up, I don't really have a choice

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
