### ISSUE TITLE
Linux appears to be broken on 5.0.0-beta.5 branch

### ISSUE THREAD

**Issue by hishboy** [mogol/flutter_secure_storage#305]
1. I installed the following
```
sudo apt reinstall libjsoncpp1 libsecret-1-0 libjsoncpp-dev libsecret-1-dev -y
```
2. Ran ` flutter run -d linux -v` with no luck. Here's the error 
![image](https://user-images.githubusercontent.com/340982/132138618-4362ff73-1581-4489-9785-c601f129d52b.png)

the branch seem to work fine on all other platforms

**Comment by juliansteenbakker** [comment]
Please try the following: https://github.com/mogol/flutter_secure_storage/issues/213#issuecomment-796829086
