### ISSUE TITLE
Flutter app gets stuck on white screen when opening SAMSUNG A205F (flutter_secure_storage: ^4.2.0)

### ISSUE THREAD

**Issue by 0xmudur** [mogol/flutter_secure_storage#308]
E/flutter (23808): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E/flutter (23808): 	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
E/flutter (23808): 	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:596)
E/flutter (23808): 	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:363)
E/flutter (23808): 	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
E/flutter (23808): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:91)
E/flutter (23808): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:162)
E/flutter (23808): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:143)
E/flutter (23808): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$400(FlutterSecureStoragePlugin.java:30)
E/flutter (23808): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:200)
E/flutter (23808): 	at android.os.Handler.handleCallback(Handler.java:873)
E/flutter (23808): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (23808): 	at android.os.Looper.loop(Looper.java:214)
E/flutter (23808): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/flutter (23808): , null)
E/flutter (23808): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (23808): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (23808): <asynchronous suspension>
E/flutter (23808): #2      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50)
E/flutter (23808): <asynchronous suspension>
E/flutter (23808): #3      FlutterSecureStorage.containsKey (package:flutter_secure_storage/flutter_secure_storage.dart:71)
E/flutter (23808): <asynchronous suspension>

**Comment by Likhachev17** [comment]
I got same error on my OnePlus 7 pro. Another devices feels good, I think it might be broken because I got security patch 2021-08-01

**Comment by lsaudon** [comment]
My tester has the same concern with Samsung S9.

**Comment by Likhachev17** [comment]
> My tester has the same concern with Samsung S9.

This error throws if we try to read key which don't exist at the moment. I just wrapped my method "read" into try/catch and waiting for fix. Can you tell which version of the security patch you have?

**Comment by lsaudon** [comment]
I don't know, but I solved my problem by adding `android:allowBackup="false" android:fullBackupContent="false"` in the android manifest.
```xml
<application android:icon="@mipmap/ic_launcher" android:label="MyApp" android:allowBackup="false" android:fullBackupContent="false">
```

**Comment by Likhachev17** [comment]
> I don't know, but I solved my problem by adding `android:allowBackup="false" android:fullBackupContent="false"` in the android manifest.
> 
> ```
> <application android:icon="@mipmap/ic_launcher" android:label="MyApp" android:allowBackup="false" android:fullBackupContent="false">
> ```

I tried this but it's not working for my case

**Comment by giabaonguyen** [comment]
I got the same error on Nokia 5.3 and Note 10

**Comment by FernandoSini** [comment]
Same error for me too

**Comment by FernandoSini** [comment]
I don't know if it's just for me but it keeps happening even in v5.0.0-beta.5.

**Comment by Ozak93** [comment]
Happens with me on Redmi Note 9 Pro( security update 2021-07-01), several of my users aswell, Huawei Nova 5, and Samsung note 6. it happens after reinstalling the app.
i currently handle it by catching the exception and deleting all the SecureStorage data and exiting the app. next launch the app works fine.

**Comment by tibfox** [comment]
same here exactly as palchukovsky is desscribing it. I will nest my reads in try-catch and check if that helps. I have searched for so long to actually find that this package is the reason and it only happens in the store releases
