### ISSUE TITLE
[Question] [iOS] How to reset secure storage on iOS from app settings ?

### ISSUE THREAD

**Issue by fvisticot** [mogol/flutter_secure_storage#310]
The secure storage is corrupted on my iOS App (value returned with bad value).
This "bad" value prevents the apps to start

Is it possible to reset the secure storage from iphone general settings ?

**Comment by KDCinfo** [comment]
At the very top of your app, can you apply a call to `await storage.deleteAll();` and clear them all out?

**Comment by fvisticot** [comment]
Tx for the quick reply.
The pb is that the app is already on the store :(
When the users are deinstalling / reinstalling the application, the secure storage is not deleted
