### ISSUE TITLE
Firebase Crashlytics Errors

### ISSUE THREAD

**Issue by basnetjiten** [mogol/flutter_secure_storage#311]
com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init> (StorageCipher18Implementation.java:31)
com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher (FlutterSecureStoragePlugin.java:72)
com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000 (FlutterSecureStoragePlugin.java:30)
com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run (FlutterSecureStoragePlugin.java:182)

Caused by java.lang.ClassNotFoundException
Didn't find class "com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation" on path: DexPathList[[zip file "/data/app/com.paynep.moru-AuJqplCz4k9nlz4a5kzQkA==/base.apk"],nativeLibraryDirectories=[/data/app/com.paynep.moru-AuJqplCz4k9nlz4a5kzQkA==/lib/arm64, /data/app/com.paynep.moru-AuJqplCz4k9nlz4a5kzQkA==/base.apk!/lib/arm64-v8a, /system/lib64]]

**Comment by juliansteenbakker** [comment]
Fixed in v5.0.0
