### ISSUE TITLE
build application failed with flutter installed via snap in linux

### ISSUE THREAD

**Issue by dum3ng** [mogol/flutter_secure_storage#314]
I have installed `libsecret-1-dev` `libjsoncpp-dev` `libsecret-1-0` and `libjsoncpp1`,
and when run `flutter run -v -d linux`, some error occur:

```
[ +159 ms] [4/5] Linking CXX executable intermediates_do_not_run/flutter_myapp
[        ] FAILED: intermediates_do_not_run/flutter_myapp 
[   +4 ms] : && /snap/flutter/current/usr/bin/clang++  -g  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl
-L/snap/flutter/current/usr/lib/ CMakeFiles/flutter_myapp.dir/main.cc.o CMakeFiles/flutter_myapp.dir/my_application.cc.o CMakeFiles/flutter_myapp.dir/flutter/generated_plugin_registrant.cc.o  -o
intermediates_do_not_run/flutter_myapp  -Wl,-rpath,/home/dumeng/projects/poem/flutter_myapp/build/linux/x64/debug/plugins/flutter_secure_storage:/home/dumeng/projects/poem/flutter_myapp/linux/flutter/ephemeral:
plugins/flutter_secure_storage/libflutter_secure_storage_plugin.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/home/dumeng/projects/poem/flutter_myapp/linux/flutter/ephemeral/libflutter_linux_gtk.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +1 ms] //lib/x86_64-linux-gnu/libjsoncpp.so.1: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()@GLIBCXX_3.4.26'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[   +2 ms] Building Linux application... (completed in 4.7s)

```

Other tool version may be related:
```
gcc: gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
clang: clang version 10.0.0-4ubuntu1 

```

And I also found this note about `jsoncpp`: [jsoncpp linker error](https://github.com/open-source-parsers/jsoncpp/blob/94cda30dbddc1859f111848fdd05dfb85d3287c7/example/README.md),
but I do not know how to do about this issue.

**Comment by talhabalaj** [comment]
Can you share the whole log file?

**Comment by dum3ng** [comment]
The whole log is below:

<pre>flutter run -v -d linux
[  +74 ms] executing: uname -m
[  +34 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/dumeng/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] executing: [/home/dumeng/snap/flutter/common/flutter/] git tag
--points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +14 ms] Exit code 0 from: git tag --points-at
4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[   +9 ms] executing: [/home/dumeng/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/dumeng/snap/flutter/common/flutter/] git ls-remote
--get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +88 ms] executing: [/home/dumeng/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +56 ms] Artifact Instance of &apos;AndroidGenSnapshotArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;AndroidInternalBuildArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;IOSEngineArtifacts&apos; is not required, skipping
update.
[        ] Artifact Instance of &apos;FlutterWebSdk&apos; is not required, skipping
update.
[   +2 ms] Artifact Instance of &apos;WindowsEngineArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;WindowsUwpEngineArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;MacOSEngineArtifacts&apos; is not required, skipping
update.
[        ] Artifact Instance of &apos;LinuxEngineArtifacts&apos; is not required, skipping
update.
[        ] Artifact Instance of &apos;LinuxFuchsiaSDKArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;MacOSFuchsiaSDKArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;FlutterRunnerSDKArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;FlutterRunnerDebugSymbols&apos; is not required,
skipping update.
[  +72 ms] Artifact Instance of &apos;AndroidGenSnapshotArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;AndroidInternalBuildArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;IOSEngineArtifacts&apos; is not required, skipping
update.
[        ] Artifact Instance of &apos;FlutterWebSdk&apos; is not required, skipping
update.
[   +1 ms] Artifact Instance of &apos;WindowsEngineArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;WindowsUwpEngineArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;MacOSEngineArtifacts&apos; is not required, skipping
update.
[   +1 ms] Artifact Instance of &apos;LinuxFuchsiaSDKArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;MacOSFuchsiaSDKArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;FlutterRunnerSDKArtifacts&apos; is not required,
skipping update.
[        ] Artifact Instance of &apos;FlutterRunnerDebugSymbols&apos; is not required,
skipping update.
[  +84 ms] Skipping pub get: version match.
[  +37 ms] Found plugin flutter_secure_storage at
/home/dumeng/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flut
ter_secure_storage-4.2.1/
[<b> +119 ms</b>] Found plugin flutter_secure_storage at
/home/dumeng/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flut
ter_secure_storage-4.2.1/
[  +34 ms] Generating
/home/dumeng/projects/poem/flutter_poem/android/app/src/main/java/io/flutter/plu
gins/GeneratedPluginRegistrant.java
[<b> +107 ms</b>] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +4 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +2 ms] complete
[   +6 ms] <b>Launching lib/main.dart on Linux in debug mode...</b>
[   +6 ms] /home/dumeng/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/dumeng/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/fr
ontend_server.dart.snapshot --sdk-root
/home/dumeng/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutt
er_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.BSSDZB/flutter_tool.WORVYE/app.dill --packages
/home/dumeng/projects/poem/flutter_poem/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +25 ms] <b>Building Linux application...</b>
[  +20 ms] &lt;- compile package:flutter_poem/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja
-DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/dumeng/projects/poem/flutter_poem/linux
[  +66 ms] -- Configuring done
[   +7 ms] -- Generating done
[        ] -- Build files have been written to:
/home/dumeng/projects/poem/flutter_poem/build/linux/x64/debug
[   +6 ms] executing: ninja -C build/linux/x64/debug install
[  +10 ms] ninja: Entering directory `build/linux/x64/debug&apos;
[<b>+3030 ms</b>] [1/7] Generating
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/libflutter_linux
_gtk.so,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_basic_message_channel.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_binary_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_binary_messenger.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_dart_project.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_engine.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_json_message_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_json_method_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_message_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_method_call.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_method_channel.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_method_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_method_response.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_plugin_registrar.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_plugin_registry.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_standard_message_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_standard_method_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_string_codec.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_value.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
_view.h,
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/flutter_linux/fl
utter_linux.h, _phony_
[   +2 ms] [  +72 ms] executing: uname -m
[        ] [  +35 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +5 ms] executing: [/home/dumeng/snap/flutter/common/flutter/] git
-c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] [        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [        ] executing: [/home/dumeng/snap/flutter/common/flutter/] git
tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [  +13 ms] Exit code 0 from: git tag --points-at
4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] [        ] 2.5.0
[        ] [   +9 ms] executing: [/home/dumeng/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/dumeng/snap/flutter/common/flutter/] git
ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +63 ms] executing: [/home/dumeng/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +53 ms] Artifact Instance of &apos;AndroidGenSnapshotArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;AndroidInternalBuildArtifacts&apos; is
not required, skipping update.
[        ] [        ] Artifact Instance of &apos;IOSEngineArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterWebSdk&apos; is not required,
skipping update.
[        ] [   +2 ms] Artifact Instance of &apos;WindowsEngineArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;WindowsUwpEngineArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;MacOSEngineArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;LinuxEngineArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;LinuxFuchsiaSDKArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;MacOSFuchsiaSDKArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterRunnerSDKArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterRunnerDebugSymbols&apos; is not
required, skipping update.
[        ] [ +101 ms] Artifact Instance of &apos;MaterialFonts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;GradleWrapper&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;AndroidGenSnapshotArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;AndroidInternalBuildArtifacts&apos; is
not required, skipping update.
[        ] [        ] Artifact Instance of &apos;IOSEngineArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterWebSdk&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterSdk&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;WindowsEngineArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;WindowsUwpEngineArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;MacOSEngineArtifacts&apos; is not
required, skipping update.
[        ] [   +1 ms] Artifact Instance of &apos;LinuxFuchsiaSDKArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;MacOSFuchsiaSDKArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterRunnerSDKArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;FlutterRunnerDebugSymbols&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;IosUsbArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;IosUsbArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;IosUsbArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;IosUsbArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;IosUsbArtifacts&apos; is not required,
skipping update.
[        ] [        ] Artifact Instance of &apos;FontSubsetArtifacts&apos; is not
required, skipping update.
[        ] [        ] Artifact Instance of &apos;PubDependencies&apos; is not required,
skipping update.
[        ] [  +41 ms] Initializing file store
[        ] [  +12 ms] Done initializing file store
[        ] [  +45 ms] Skipping target: gen_localizations
[        ] [  +14 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +644 ms] Skipping target: unpack_linux
[        ] [ +583 ms] Skipping target: kernel_snapshot
[        ] [ +433 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [  +13 ms] Done persisting file store
[        ] [   +9 ms] build succeeded.
[        ] [  +10 ms] &quot;flutter assemble&quot; took 1,934ms.
[        ] [ +260 ms] ensureAnalyticsSent: 255ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +5 ms] exiting with code 0
[<b>+2375 ms</b>] [2/5] Building CXX object
CMakeFiles/flutter_poem.dir/my_application.cc.o
[        ] [3/5] Building CXX object
CMakeFiles/flutter_poem.dir/flutter/generated_plugin_registrant.cc.o
[<b> +468 ms</b>] [4/5] Linking CXX executable intermediates_do_not_run/flutter_poem
[        ] FAILED: intermediates_do_not_run/flutter_poem 
[   +6 ms] : &amp;&amp; /snap/flutter/current/usr/bin/clang++  -g
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma
-lpthread -ldl -L/snap/flutter/current/usr/lib/
CMakeFiles/flutter_poem.dir/main.cc.o
CMakeFiles/flutter_poem.dir/my_application.cc.o
CMakeFiles/flutter_poem.dir/flutter/generated_plugin_registrant.cc.o  -o
intermediates_do_not_run/flutter_poem
-Wl,-rpath,/home/dumeng/projects/poem/flutter_poem/build/linux/x64/debug/plugins
/flutter_secure_storage:/home/dumeng/projects/poem/flutter_poem/linux/flutter/ep
hemeral: plugins/flutter_secure_storage/libflutter_secure_storage_plugin.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/home/dumeng/projects/poem/flutter_poem/linux/flutter/ephemeral/libflutter_linux
_gtk.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so &amp;&amp; :
[   +1 ms] //lib/x86_64-linux-gnu/libjsoncpp.so.1: undefined reference to
`std::__cxx11::basic_ostringstream&lt;char, std::char_traits&lt;char&gt;,
std::allocator&lt;char&gt; &gt;::basic_ostringstream()@GLIBCXX_3.4.26&apos;
<font color="#CC0000">[        ] </font><font color="#CC0000"><b>clang: error: linker command failed with exit code 1 (use -v to see</b></font>
<font color="#CC0000"><b>invocation)</b></font>
[   +1 ms] ninja: build stopped: subcommand failed.
[  +12 ms] Building Linux application... (completed in 6.0s)
<font color="#CC0000">[        ] </font><font color="#CC0000"><b>Exception: Build process failed</b></font>
[   +1 ms] &quot;flutter run&quot; took 6,579ms.
<font color="#CC0000">[   +5 ms] </font>
<font color="#CC0000"><b>           #0      throwToolExit</b></font>
<font color="#CC0000"><b>(package:flutter_tools/src/base/common.dart:10:3)</b></font>
<font color="#CC0000"><b>           #1      RunCommand.runCommand</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/commands/run.dart:669:9)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #2      FlutterCommand.run.&lt;anonymous closure&gt;</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #3      AppContext.run.&lt;anonymous closure&gt;</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/base/context.dart:150:19)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #4      CommandRunner.runCommand</b></font>
<font color="#CC0000"><b>(package:args/command_runner.dart:209:13)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #5      FlutterCommandRunner.runCommand.&lt;anonymous closure&gt;</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #6      AppContext.run.&lt;anonymous closure&gt;</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/base/context.dart:150:19)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #7      FlutterCommandRunner.runCommand</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #8      run.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/runner.dart:62:9)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #9      AppContext.run.&lt;anonymous closure&gt;</b></font>
<font color="#CC0000"><b>           (package:flutter_tools/src/base/context.dart:150:19)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           #10     main (package:flutter_tools/executable.dart:92:3)</b></font>
<font color="#CC0000"><b>           &lt;asynchronous suspension&gt;</b></font>
<font color="#CC0000"><b>           </b></font>
<font color="#CC0000"><b>           </b></font>
[<b> +255 ms</b>] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

</pre>

**Comment by juliansteenbakker** [comment]
The issue is indeed snap. Please use manual version of flutter only.

**Comment by oliversd** [comment]
Confirmed the issue was the snap installation. Follow this steps:

1. Remove flutter with snap:

`sudo snap remove flutter`

2. Follow the instruction from official documentation:

https://docs.flutter.dev/get-started/install/linux#install-flutter-manually

3. Make sure that you have all the dependencies

https://docs.flutter.dev/get-started/install/linux#linux-setup

4. Check that you updated the PATH and that `flutter doctor` works.

5. Be sure to run `flutter clean`  **important**

You should ready to go.
