### ISSUE TITLE
Release Timeline for 5.0.0

### ISSUE THREAD

**Issue by ABausG** [mogol/flutter_secure_storage#318]
I was very happy to see that v5.0.0 now supports all platforms. I was wondering if there is a release timeline for when 5.0.0 would move to a stable release.

Reason is that I need it for a package itself and pub is complaining that I'd need to move my own package to a pre release as well. So checking for a rough timeline.

**Comment by juliansteenbakker** [comment]
It seems like it is not yet stable on some devices. I am still waiting for someone to provide a fix because i can't reproduce the issues that are described here.

**Comment by juliansteenbakker** [comment]
5.0.0 has been released
