### ISSUE TITLE
Build error for linux 5.0 beta

### ISSUE THREAD

**Issue by tmtong** [mogol/flutter_secure_storage#319]
sudo apt reinstall libjsoncpp1 libsecret-1-0 libjsoncpp-dev libsecret-1-dev -y

~/Documents/flutter_secure_storage/flutter_secure_storage/example$ flutter drive --target=test_driver/app.dart
Running "flutter pub get" in example...                                ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ 2,138ms
Multiple devices found:
Linux (desktop) ï¿½ï¿½ï¿½ linux  ï¿½ï¿½ï¿½ linux-x64      ï¿½ï¿½ï¿½ Ubuntu 20.04.1 LTS 4.19.76-linuxkit
Chrome (web)    ï¿½ï¿½ï¿½ chrome ï¿½ï¿½ï¿½ web-javascript ï¿½ï¿½ï¿½ Google Chrome 90.0.4430.93
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  flutter/CMakeLists.txt:28 (pkg_check_modules)

Building Linux application...                                          ï¿½ï¿½ 
Unable to generate build files

**Comment by talhabalaj** [comment]
Are you using the Snap version of flutter?

**Comment by juliansteenbakker** [comment]
Please try the following: https://github.com/mogol/flutter_secure_storage/issues/213#issuecomment-796829086
