### ISSUE TITLE
Calling secure storage from getters and setters

### ISSUE THREAD

**Issue by victorblaess** [mogol/flutter_secure_storage#323]
Hi Guys,

I am implementing a discord authentication.
Currently there is a class UserSession (Implemented as singleton) which consists of the following properties:

```dart
  DiscordUser? discordUser;
  List<DiscordGuild?>? discordGuilds;
  String? accessToken;
  String? refreshToken;
  DateTime? sessionExpirationDate;
```

Now I would like to hold accessToken and refreshToken in flutter_secure_storage and write it to secure storage whenever one of these properties are being set and read from the storage whenever one of these values are being get.

Actually I havent found an example implementation how to do that conveniently.
After implementing a first test within a getter and setter it didnt really worked out.
Anybody got a code snippet?

## Full class

```dart
class UserSession {
  static UserSession? _sessionInstance;

  UserSession._(
    DiscordUser? discordUser,
    List<DiscordGuild?>? discordGuilds,
    String? accessToken,
    String? refreshToken,
    DateTime? sessionExpirationDate,
  );

  factory UserSession(
          {required DiscordUser? discordUser,
          required List<DiscordGuild?>? discordGuilds,
          required accessToken,
          required refreshToken,
          required sessionExpirationDate}) =>
      _sessionInstance ??= UserSession._(discordUser, discordGuilds,
          accessToken, refreshToken, sessionExpirationDate);

  @override
  String toString() {
    // TODO: implement toString
    return super.toString();
  }
}
```

**Comment by juliansteenbakker** [comment]
The best possibility is to do it via a setter like so:
```dart
  String? _accessToken;
  set accessToken(String? _accessToken) {
    _accessToken = accessToken;
    saveToken(_accessToken);
  }
  String? get accessToken => _accessToken

Future<void> saveToken(String key, String? token) async {
    // Write value
    await storage.write(key: key, value: token);
}
```

**Comment by victorblaess** [comment]
> The best possibility is to do it via a setter like so:
> 
> ```dart
>   String? _accessToken;
>   set accessToken(String? _accessToken) {
>     _accessToken = accessToken;
>     saveToken(_accessToken);
>   }
>   String? get accessToken => _accessToken
> 
> Future<void> saveToken(String key, String? token) async {
>     // Write value
>     await storage.write(key: key, value: token);
> }
> ```

Thanks for your suggestion but two more question @juliansteenbakker: 

- Dont I need to call saveToken with await and be forced to make the setter async ?
- Doesnt the getter need to read the accessToken from the secureStorage?

**Comment by victorblaess** [comment]
Probably like this?
```dart
  String? _accessToken;
  String? refreshToken;
  DateTime? sessionExpirationDate;

  set accessToken(String? accessToken) {
    _accessToken = accessToken;
    storeAccessTokenToSafe(_accessToken);
  }

  String? get accessToken {
    getAccessTokenFromSafe();
    return _accessToken;
  }

  void storeAccessTokenToSafe(String? accessToken) async {
    await secureStorage.write(key: "ACCESS_TOKEN", value: accessToken);
  }

  Future<String?> getAccessTokenFromSafe() async {
    _accessToken = await secureStorage.read(key: "ACCESS_TOKEN");
  }
```
