### ISSUE TITLE
Unable to read existing value in iOS keychain

### ISSUE THREAD

**Issue by danielnordh** [mogol/flutter_secure_storage#324]
We are migrating a native iOS app to Flutter and need to read an existing keychain value for existing users.
While we can write and read the keychain fine for new users, we are not able to use `flutter_secure_storage` to read values from the native app. 

With the following code, `value` returns `null`.
```
FlutterSecureStorage keychain = FlutterSecureStorage();
final options = IOSOptions(accountName: "our_service");
final value = await keychain.read(key: "our_key", iOptions: options);
```

When using the [flutter_keychainaccess](https://pub.dev/packages/flutter_keychainaccess/example) package and the following code, `value` returns the correct string.
`final value = await FlutterKeychainaccess.read(service: "our_service", key: "our_key");`

While we can get around our issue by using this other package, it feels like this should be possible without adding another dependency.

Related:
#142
#184
#211

**Comment by maks** [comment]
@danielnordh  Given how small the code for `flutter_keychainaccess` is, I would suggest just comparing its Swift and Dart to what is in this package to see what the difference is in it working and this package not.

**Comment by juliansteenbakker** [comment]
Which version of this package are you using? Can you please try again with version 5.0.0

**Comment by danielnordh** [comment]
I'm using version 5.0.1

**Comment by danielnordh** [comment]
I just tested with 5.0.2 and it still returns `null`

**Comment by danielnordh** [comment]
I haven't been able to identify what changed, but I am now able to read the value with the above code snippets.
Suffice to say it was likely down to user error on my part.
