### ISSUE TITLE
Cannot read from SharedPreferences after updating to version 5.0.0

### ISSUE THREAD

**Issue by masewo** [mogol/flutter_secure_storage#332]
After updating this plugin from version 4.2.1 to version 5.0.0 my app cannot read from the SharedPreferences anymore. After restarting or redeploying the app, calling the `containsKey` or `read` methods result in the following error:

```
I/flutter (17096): The following exception was thrown as error:
I/flutter (17096): PlatformException(Exception encountered, containsKey, java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.contains(java.lang.String)' on a null object reference
I/flutter (17096): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:318)
I/flutter (17096): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (17096): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (17096): 	at android.os.Looper.loop(Looper.java:223)
I/flutter (17096): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (17096): , null)
```

Tried it with `AndroidOptions(encryptedSharedPreferences: true)` and with `AndroidOptions(encryptedSharedPreferences: false)`.
Wiping the emulator (API 30) does also not help.

**Comment by JAICHANGPARK** [comment]
I had same error 

```
E/flutter ( 8372): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.contains(java.lang.String)' on a null object reference
E/flutter ( 8372): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:298)
E/flutter ( 8372): 	at android.os.Handler.handleCallback(Handler.java:790)
E/flutter ( 8372): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 8372): 	at android.os.Looper.loop(Looper.java:164)
E/flutter ( 8372): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/flutter ( 8372): , null)
```

**Comment by hacpert** [comment]
same problem 
`
I/flutter (19966): │ ⛔ PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.contains(java.lang.String)' on a null object reference
I/flutter (19966): │ ⛔ 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:298)
I/flutter (19966): │ ⛔ 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (19966): │ ⛔ 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (19966): │ ⛔ 	at android.os.Looper.loop(Looper.java:246)
I/flutter (19966): │ ⛔ 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (19966): │ ⛔ , null)
`

**Comment by hacpert** [comment]
same error

> 
I/flutter (19966): │ ⛔ PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.contains(java.lang.String)' on a null object reference
I/flutter (19966): │ ⛔ 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:298)
I/flutter (19966): │ ⛔ 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (19966): │ ⛔ 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (19966): │ ⛔ 	at android.os.Looper.loop(Looper.java:246)
I/flutter (19966): │ ⛔ 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (19966): │ ⛔ , null)
>

**Comment by mohammedX6** [comment]
Same error

**Comment by juliansteenbakker** [comment]
I have found the issue and I'm working on a solution. Thanks for reporting.

**Comment by juliansteenbakker** [comment]
I have released V5.0.2 with the fix implemented. Please comment if it works or not.

**Comment by NicolaVerbeeck** [comment]
Works for me, thanks

**Comment by jiangxiaoqiang** [comment]
I upgrade to 5.0.2 but did not fix this problem.
