### ISSUE TITLE
IOSAccessibility.passcode

### ISSUE THREAD

**Issue by TMSantos** [mogol/flutter_secure_storage#340]
Hey guys,

when writing with IOSAccessibility.passcode , it means it will use kSecClassGenericPassword right? It shouldn't be able to retrieve the item without device authentication being performed?

I am able to return the item, without doing any authentication, I'm getting it wrong?

**Comment by wangjiejacques** [comment]
@TMSantos No, it means it will use [kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly](https://developer.apple.com/documentation/security/ksecattraccessiblewhenpasscodesetthisdeviceonly), which means 
> The data in the keychain can only be accessed when the device is unlocked. Only available if a passcode is set on the device.

So I suppose this is an expected behavior.
