### ISSUE TITLE
Add api to read/writ bytes

### ISSUE THREAD

**Issue by wangjiejacques** [mogol/flutter_secure_storage#341]
For now, we can only read/write utf8 string which is not convenient sometimes (for example, we may want to save other types like [Date](https://developer.apple.com/documentation/foundation/date)). 

Can we add a new api to read/write bytes like [this](https://github.com/kishikawakatsumi/KeychainAccess/blob/6299daec1d74be12164fec090faf9ed14d0da9d6/Lib/KeychainAccess/Keychain.swift#L610)?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
