### ISSUE TITLE
Values not updating right away

### ISSUE THREAD

**Issue by jamesmwase** [mogol/flutter_secure_storage#343]
When you update a value it still holds previous value for quite a long time. Then it updates later. I've noticed this multiple times. Please fix this. Thanks.

**Comment by juliansteenbakker** [comment]
Do you encounter this on Android or iOS?

**Comment by elmasry** [comment]
@juliansteenbakker The value is not deleted or updated at all on some devices. Happens on iOS 14 and 15

**Comment by juliansteenbakker** [comment]
That is a different issue @elmasry. Do you have any example or stacktrace of this issue?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
