### ISSUE TITLE
UNKNOWN_ERROR on windows for large secrets (>2561 bytes)

### ISSUE THREAD

**Issue by volund** [mogol/flutter_secure_storage#345]
The following error occurs on windows whenever I try to save a secret that's larger than 2561 bytes:

```
    PlatformException(Exception encountered: UNKNOWN_ERROR, write, null, null)
    
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
```

This error does not appear with a secret that is 2560 bytes or less. This is happening with 5.0.2 on Windows 10 Enterprise. 

For reference here's the secret I reproduce the error with:

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

This happens when using:
```
flutterSecureStorage.write('key1', secret);
```

**Comment by esbozos** [comment]
Same here. 

`flutter: storage write exception: PlatformException(Exception encountered: UNKNOWN_ERROR, write, null, null)
`

**Comment by yfakariya** [comment]
I found that this is a limitation from [Windows API design](https://docs.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala), it says that:

> `CredentialBlobSize`
> The size, in bytes, of the `CredentialBlob` member. This member cannot be larger than `CRED_MAX_CREDENTIAL_BLOB_SIZE` (5*512) bytes.

**Comment by Jon-Salmon** [comment]
I've worked around this in my application by encrypting the long secret with AES encryption and using this plugin to store the crypto key. Here's my implementation for oauth2_client if anybody is interested: https://github.com/Jon-Salmon/oauth2_client_aes_storage

**Comment by volund** [comment]
@ggaj  I added a small abstraction that detects if the platform is windows, and if it is windows then it splits the secret into several chunks and stores it under separate keys. It seems to work well enough. Jon-Salmon's solution is also good, if you have AES encryption at hand.

**Comment by fncap** [comment]
If anyone facing this issue, following is a custom class that splits value in chunks of 512 bytes and stores them using FlutterSecureStorage! 
It apply only if Platform.isWindows and value exceed Windows maximum allowed size.
It is able, also, to read chunked value and returns it as single value.

Enjoy it!

```dart
import 'dart:io';

import 'package:flutter_secure_storage/flutter_secure_storage.dart';

const CRED_MAX_CREDENTIAL_BLOB_SIZE = 5 * 512;

class SecureStorage {
  final FlutterSecureStorage flutterSecureStorage;

  const SecureStorage(this.flutterSecureStorage);

  Future<void> write({
    required String key,
    required String? value,
  }) async {
    if (Platform.isWindows &&
        value != null &&
        value.length > CRED_MAX_CREDENTIAL_BLOB_SIZE) {
      final exp = RegExp(r".{1,512}");
      final matches = exp.allMatches(value).toList();
      final chunkedKey = '\$${key}_chunk_size';
      await Future.wait(List.generate(matches.length + 1, (i) {
        return i == 0
            ? flutterSecureStorage.write(
                key: chunkedKey, value: matches.length.toString())
            : flutterSecureStorage.write(
                key: '${key}_$i', value: matches[i - 1].group(0));
      }));
    } else {
      await flutterSecureStorage.write(key: key, value: value);
    }
  }

  Future<String?> read({required String key}) async {
    if (Platform.isWindows) {
      final chunkedKey = '\$${key}_chunk_size';

      final chunkSize =
          int.parse(await flutterSecureStorage.read(key: chunkedKey) ?? '0');

      if (chunkSize > 0) {
        final chunks = await Future.wait(List.generate(chunkSize,
            (i) async => await flutterSecureStorage.read(key: '${key}_$i')));
        return chunks.join();
      } else {
        return await flutterSecureStorage.read(key: key);
      }
    } else {
      return await flutterSecureStorage.read(key: key);
    }
  }
}
```

**Comment by AmauryBuguet** [comment]
> If anyone facing this issue, following is a custom class that splits value in chunks of 512 bytes and stores them using FlutterSecureStorage! It apply only if Platform.isWindows and value exceed Windows maximum allowed size. It is able, also, to read chunked value and returns it as single value.
> 
> Enjoy it!
> 
> ```dart
> import 'dart:io';
> 
> import 'package:flutter_secure_storage/flutter_secure_storage.dart';
> 
> const CRED_MAX_CREDENTIAL_BLOB_SIZE = 5 * 512;
> 
> class SecureStorage {
>   final FlutterSecureStorage flutterSecureStorage;
> 
>   const SecureStorage(this.flutterSecureStorage);
> 
>   Future<void> write({
>     required String key,
>     required String? value,
>   }) async {
>     if (Platform.isWindows &&
>         value != null &&
>         value.length > CRED_MAX_CREDENTIAL_BLOB_SIZE) {
>       final exp = RegExp(r".{1,512}");
>       final matches = exp.allMatches(value).toList();
>       final chunkedKey = '\$${key}_chunk_size';
>       await Future.wait(List.generate(matches.length + 1, (i) {
>         return i == 0
>             ? flutterSecureStorage.write(
>                 key: chunkedKey, value: matches.length.toString())
>             : flutterSecureStorage.write(
>                 key: '${key}_$i', value: matches[i - 1].group(0));
>       }));
>     } else {
>       await flutterSecureStorage.write(key: key, value: value);
>     }
>   }
> 
>   Future<String?> read({required String key}) async {
>     if (Platform.isWindows) {
>       final chunkedKey = '\$${key}_chunk_size';
> 
>       final chunkSize =
>           int.parse(await flutterSecureStorage.read(key: chunkedKey) ?? '0');
> 
>       if (chunkSize > 0) {
>         final chunks = await Future.wait(List.generate(chunkSize,
>             (i) async => await flutterSecureStorage.read(key: '${key}_$i')));
>         return chunks.join();
>       } else {
>         return await flutterSecureStorage.read(key: key);
>       }
>     } else {
>       return await flutterSecureStorage.read(key: key);
>     }
>   }
> }
> ```

Thanks it helped me alot !
I just had an error because there was a chunk missing at the end and a null chunk at the start so I changed
```(i) async => await flutterSecureStorage.read(key: '${key}_$i')));``` 
into
```(i) async => await flutterSecureStorage.read(key: '${key}_${i+1}')));```
and everything was good again.

**Comment by 0xNF** [comment]
@AmauryBuguet, @fncap

This utility over read/write are great thanks. Here's a `delete` function to round it out. Any observant programmer could construct it on their own from the above examples, but better to have them all collected here in one place:

```dart

  Future<String?> read({required String key}) async {
    if (Platform.isWindows) {
      final chunkedKey = '\$${key}_chunk_size';

      final chunkSize =
          int.parse(await flutterSecureStorage.delete(key: chunkedKey) ?? '0');

      if (chunkSize > 0) {
        await Future.wait(List.generate(chunkSize,
            (i) async => await flutterSecureStorage.delete(key: '${key}_${i + 1}')));
      } else {
        return await flutterSecureStorage.delete(key: key);
      }
    } else {
      return await flutterSecureStorage.delete(key: key);
    }
  }
}
```

**Comment by karmanux** [comment]
> If anyone facing this issue, following is a custom class that splits value in chunks of 512 bytes and stores them using FlutterSecureStorage! It apply only if Platform.isWindows and value exceed Windows maximum allowed size. It is able, also, to read chunked value and returns it as single value.
> 
> Enjoy it!
> 
> ```dart
> import 'dart:io';
> 
> import 'package:flutter_secure_storage/flutter_secure_storage.dart';
> 
> const CRED_MAX_CREDENTIAL_BLOB_SIZE = 5 * 512;
> 
> class SecureStorage {
>   final FlutterSecureStorage flutterSecureStorage;
> 
>   const SecureStorage(this.flutterSecureStorage);
> 
>   Future<void> write({
>     required String key,
>     required String? value,
>   }) async {
>     if (Platform.isWindows &&
>         value != null &&
>         value.length > CRED_MAX_CREDENTIAL_BLOB_SIZE) {
>       final exp = RegExp(r".{1,512}");
>       final matches = exp.allMatches(value).toList();
>       final chunkedKey = '\$${key}_chunk_size';
>       await Future.wait(List.generate(matches.length + 1, (i) {
>         return i == 0
>             ? flutterSecureStorage.write(
>                 key: chunkedKey, value: matches.length.toString())
>             : flutterSecureStorage.write(
>                 key: '${key}_$i', value: matches[i - 1].group(0));
>       }));
>     } else {
>       await flutterSecureStorage.write(key: key, value: value);
>     }
>   }
> 
>   Future<String?> read({required String key}) async {
>     if (Platform.isWindows) {
>       final chunkedKey = '\$${key}_chunk_size';
> 
>       final chunkSize =
>           int.parse(await flutterSecureStorage.read(key: chunkedKey) ?? '0');
> 
>       if (chunkSize > 0) {
>         final chunks = await Future.wait(List.generate(chunkSize,
>             (i) async => await flutterSecureStorage.read(key: '${key}_$i')));
>         return chunks.join();
>       } else {
>         return await flutterSecureStorage.read(key: key);
>       }
>     } else {
>       return await flutterSecureStorage.read(key: key);
>     }
>   }
> }
> ```

thank
