### ISSUE TITLE
read() working weird after upgrading to iOS 15.1

### ISSUE THREAD

**Issue by alexnavarrogarcia** [mogol/flutter_secure_storage#346]
After upgrading to iOS 15.1, getting information in the background started to work weird (sometimes is able to get the values and some other times it doesn't). My IOSOptions value is first_unlock. Anyone else with the same issue?

**Comment by danallen88** [comment]
Wondering if this is at all related to: https://sourcediving.com/solving-mysterious-logout-issues-on-ios-15-8b818c089466

**Comment by alexnavarrogarcia** [comment]
Today, iOS 15.2 was released, so I upgraded my phone and it seems that the issue is fixed... I will continue testing and will keep you posted.

Thanks.

**Comment by danallen88** [comment]
We're experiencing this as well.  Upgrading iOS doesn't seem to help.  We released our app initially with the default `unlocked` setting and released an update with `first_unlock`, yet the keychain is inaccessible any time the app appears to be running in the background (e.g. due to an app update event, or a push notification).

**Comment by alexnavarrogarcia** [comment]
Sorry, I meant to provide an update earlier. First of all, I need to say I incorrectly assumed this was an issue related with Flutter Secore Storage, but it is not; long story short, the problem is with Apple iOS 15.0 and Geofences:
https://discussions.apple.com/thread/253247480?r_s_legacy=true

Now, @danallen88 in regards to your question "_If items were stored in the keychain with the unlocked accessibility attribute, is it the case that it will maintain that policy until it is rewritten with the first_unlock policy? Or would I be able to read out a value written with unlocked with a first_unlock policy applied to the constructor default when initializing FlutterSecureStorage?_" 

I had this problem as well and what worked for me  was deleting all of my "unlocked" values and then write them again with first_unlock; then, I was able to read them even in background. Hope this is helpfull.

**Comment by danallen88** [comment]
Makes complete sense.  I would say it's probably safe to close this issue then, would you agree @alexnavarrogarcia?

**Comment by alexnavarrogarcia** [comment]
Yes, I'll proceed and close it.
