### ISSUE TITLE
Should I say that "my app uses encryption" if I use this library?

### ISSUE THREAD

**Issue by alexverbitsky** [mogol/flutter_secure_storage#349]
![image](https://user-images.githubusercontent.com/34838543/147499182-06417b3f-a927-44f4-856b-6f45c961e856.png)
I'm distributing the app outside the US and Canada. So I'm curious whether should I attach any export documentation if I use this library. Thanks in advance.

**Comment by vicenterusso** [comment]
Technically yes, even if you just make HTTPS calls you must check that option.
