### ISSUE TITLE
Read key value from a different class file does to work

### ISSUE THREAD

**Issue by newbieflutter** [mogol/flutter_secure_storage#35]
My problem is that I want to secure the user id and password. The reason is that each time the user will login I will check the stored token (I store in shared preferences). So if the token is expired I will then send the user ID and password which I want to store securely to get a new token. Thus then I dont want the user to keep keying in their user id and password. Below is what I do in the login page.

The error I keep getting is this one 

> Error: Unexpected token 'await'.
>     String value = await _storage.read(key: "test1");
> Error: A value of type 'dart.async::Future<dart.core::String>' can't be assigned to a variable of type 'dart.core::String'.
> Try changing the type of the left hand side, or casting the right hand side to 'dart.core::String'.
>     String value = await _storage.read(key: "test1");

```
 _authenticateUser() async {
		if(_valid()) {      
			var responseJson = await NetworkUtils.authenticateUser(
				emailController.text, passwordController.text
			);
			print(responseJson);
			if(responseJson == null) {
			NetworkUtils.showSnackBar(_scaffoldKey, 'Something went wrong!');
			} 
                        else {
				AuthUtils.insertDetails(_sharedPreferences, responseJson);
                       }
	}
```
Here is the function I try to run on my login page to read the secure store 

```
_fetchSessionAndNavigate() async {
      _sharedPreferences = await _prefs;
      String authToken = AuthUtils.getToken(_sharedPreferences);
      String secKey = AuthUtils.getKey();
      //print("Existing token"+authToken);
      if(authToken != null){
          print("Existing token"+authToken);
      }
      else{
          print("No token yet");

      }
     
    }
```
Here is my full AuthUtil class.
```

import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
class AuthUtils {
  static final _storage = new FlutterSecureStorage();
  static final String authTokenKey = 'auth_token';
	static String getToken(SharedPreferences prefs) {
		return prefs.getString(authTokenKey);
	}
  static String getKey async() {
    String value = await _storage.read(key: "test1");
		return value;
	}
	static insertDetails(SharedPreferences prefs, var response) {		
    print("Token is :"+response['token']);
    print("userID is :"+response['userID']);    
    prefs.setString(authTokenKey, response['token']);
		//var user = response['user'];
		prefs.setString(userIdKey, response['userID']);
		//prefs.setString(nameKey, user['name']);
    _storage.write(key: "test1", value: "test");
    //await _storage1.write
	}	
}
```

**Comment by mogol** [comment]
Hi @newbieflutter ,
It looks like signature of the function is incorrect, 
if it's async, then return type should be `Future<String>` 
so 
`static String getKey async() {`  => `static Future<String> getKey() async {`

**Comment by newbieflutter** [comment]
Hi @mogol  I still get the same error its says I cant put string into Future<String>. On another note is this function correct for me to store password and reuse it for auto relogin or am I doing things wrongly.
