### ISSUE TITLE
Mac OS write read doesn't work

### ISSUE THREAD

**Issue by jaumard** [mogol/flutter_secure_storage#350]
Not sure why but on mac OS nothing is saved (or read) from secure prefs :(

```dart
final securePrefs = const FlutterSecureStorage();
await securePrefs.write(key: 'keyToken', value: 'token');
final token = await securePrefs.read(key: 'keyToken');
```
token is always null, no errors or anything. No problems on iOS and Android

Using `flutter_secure_storage: ^5.0.2` and `flutter 2.5.3`

**Comment by JWambaugh** [comment]
I'm having the same issue :/. No errors given, just doesn't work on mac.

**Comment by Andrflor** [comment]
I have the exact same problem on latest ArchLinux, always null, no error :face_with_spiral_eyes:

**Comment by zebamba** [comment]
I am Using flutter_secure_storage: ^5.0.2 and flutter 2.9.0-1.0.pre.471

I have same issue on Mac OS.

Is there any required permission to set/change while the app is in development?

**Comment by mikexkllr** [comment]
I have the same issue. Is there any configuration which needs to be done in the MacOS runner? thx for help!

**Comment by zebamba** [comment]
I opened the project on XCode, then added Keychain Sharing. Added group value as * (asterisk symbol) 

I am Using flutter_secure_storage: ^5.0.2, flutter 2.10.4, Dart 2.16.2

The same error still happening returning null value from the storage. 

What I am missing here?

<img width="606" alt="Screen Shot 2022-04-08 at 12 41 00 PM" src="https://user-images.githubusercontent.com/10945353/162486834-05dce1eb-79fe-41ae-bb01-cbdd946aa712.png">

<img width="699" alt="Screen Shot 2022-04-08 at 12 42 19 PM" src="https://user-images.githubusercontent.com/10945353/162486898-ccb60d57-2d7d-4904-9a5e-46473ce69e07.png">



<img width="875" alt="Screen Shot 2022-04-08 at 12 42 43 PM" src="https://user-images.githubusercontent.com/10945353/162486175-159307f4-4d39-4f1c-b653-9238953d3268.png">

**Comment by fluttertests** [comment]
same thing here and brought me here.

**Comment by zebamba** [comment]
@fluttertests @mikexkllr @jaumard @Andrflor 

I got it working, but I have few other issues with the build for mac after changes on the project.

Try this.

Open the `macos` project folder on Xcode
Add Key Chain sharing capability

You have to signin Xcode with a developer account, a generated certificate, set the bundle name kind of unique.

Ps: I have done the steps in the images from my previous message on the ios project folder. lol

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by usmanovrustam** [comment]
> I am closing all older issues. If this issue still exists in the latest version, please let me know.

The same error with v9.2.2 version: 

 `Unhandled Exception: PlatformException(Unexpected security result code, Code: -34018, Message: A required entitlement isn't present., -34018, null)`

 Then, I've seen there is written: 
 
 ![Screenshot 2024-09-07 at 11 55 52](https://github.com/user-attachments/assets/35cda353-765f-43bb-a37f-d187413ccd11)
 
 but , another error is coming right here: 
 
 ```
 Warning: unable to build chain to self-signed root for signer "Apple Development: ************@gmail.com (*********)"
/Users/***********/projects/flutter/******/*******/build/macos/Build/Products/Debug/*******.app/Contents/Frameworks/libswiftAppKit.dylib: errSecInternalComponent

warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **
```

**Comment by nikolaihen** [comment]
Same issue here (Code: -34018, Message: A required entitlement isn't present.). Tried to add a specific group id as well without success

**Comment by federico-b-visia** [comment]
I have the same issue on MacOS, lib version: 9.2.4.
`Unhandled Exception: PlatformException(Unexpected security result code, Code: -34018, Message: A required entitlement isn't present., -34018, null)`
