### ISSUE TITLE
Secure storage not replicated across devices.

### ISSUE THREAD

**Issue by Andy-JB** [mogol/flutter_secure_storage#351]
I'm working on an app where the user signs in with google. I generate a secret key on sign up and store it with flutter_secure_storage. If the user gets a new device, and sign into the app with google on the new device, the secret key is not available in secure storage. Is this something this package should/could cater for?

**Comment by Andrflor** [comment]
You are missing key application architecture principles.
If you want to store an information across devices you should store it on a server and give access to user via authentication.
This package is storing data on the user device.
If you are not familiar with backend principle you can use a service like Firebase.

I hardly recommend that you learn the theory behind application building before developing any further.

This may help
https://www.youtube.com/watch?v=8UlLgOf20Ho&list=PL4JxLacgYgqTgS8qQPC17fM-NWMTr5GW6

**Comment by Andy-JB** [comment]
I am using firebase. I asked the question because I was looking to have a solution where the user's data is encrypted in firebase and only they have access to the key. Thanks anyway for replying.
