### ISSUE TITLE
include file: 'atlstr.h' is missing

### ISSUE THREAD

**Issue by eae1212** [mogol/flutter_secure_storage#356]
Error during Building Windows application:
fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [XXX\_TESTS\flutter_secure_storage_example\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]

Flutter 2.5.3
flutter_secure_storage: ^5.0.2

**Comment by eae1212** [comment]
Error occurs when building example on Windows 10.
Building on Windows 7 is Ok

**Comment by alexkmbk** [comment]
> @alexkmbk and @eae1212 can you guys attach the link for these resources to be downloaded

https://visualstudio.microsoft.com/downloads/?q=build+tools
