### ISSUE TITLE
Can't be able to delete data 

### ISSUE THREAD

**Issue by idamsel** [mogol/flutter_secure_storage#357]
Can't be able to delete my data at Logout button click event. I perform below code at button `onPress`. But it can't work. Please give me solution related this issue.

`_secureStorage.deleteSecureData("username");`

**Comment by Livinglist** [comment]
I'm having same issue just now. Can't same to delete data using delete function. On iOS 15.2 with Flutter 2.8.1

**Comment by vaidarbhiiboon** [comment]
Yes , I refer this link for store , retrieve and delete data. He use `_secureStorage.deleteSecureData("username")` , So his name is empty when he press sign out. I want to perform same functionality for my E-Commerce application. But in my case I can't be able to remove my name at profile section after clicking log out button :(

I use Windows 10 with Flutter 2.8.1

If you find out any solution regarding this , then please inform me. It means a lot to me :) (You also refer below link too)
 [Flutter Secure Storage](https://www.youtube.com/watch?v=yP1Hq3x3WSM&ab_channel=Abhishvek)

**Comment by vaidarbhicontractor** [comment]
Yes , I refer below link for store , retrieve and delete data. He use `_secureStorage.deleteSecureData("username")` , So his name is empty when he press sign out. I want to perform same functionality for my E-Commerce application. But in my case I can't be able to remove my name at profile section after clicking log out button :(

I use Windows 10 with Flutter 2.8.1

If you find out any solution regarding this , then please inform me. It means a lot to me :) (You also refer below link too)
 [Flutter Secure Storage](https://www.youtube.com/watch?v=yP1Hq3x3WSM&ab_channel=Abhishvek)

**Comment by Maher-Reven** [comment]
apparently me and my team after suffering for a few weeks trying to solve the issue, we end up either deleting those params or assigning them to null or empty values to fix the issue and that works, 
I highly recommend you do that!

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
