### ISSUE TITLE
Android - containsKey is always returning false

### ISSUE THREAD

**Issue by nforesperance** [mogol/flutter_secure_storage#359]
After installing the package and running the example provided on [pub.dev](https://pub.dev/packages/flutter_secure_storage/example)
I realized that after adding items to the storage and using **containsKey** function for all the keys that were added, the result is always **false**
I don't know if anyone else has had this issue?

**Comment by sems** [comment]
The same is happening to me with the latest version from pub, after upgrading. I haven't tested it on Android, but it is happening on iOS. I re-rolled to the version I was using previously and it works again.

**Comment by farkerhaiku** [comment]
@sems can you confirm what version of the library works consistently so I can downgrade?

**Comment by sems** [comment]
> @sems can you confirm what version of the library works consistently so I can downgrade?
@farkerhaiku I downgraded to version `^4.2.1`, maybe some minor versions higher are also possible. But I can confirm that `^4.2.1` works fine, as it's supposed to.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
