### ISSUE TITLE
Linux desktop issues

### ISSUE THREAD

**Issue by shroff** [mogol/flutter_secure_storage#382]
I'm having issues getting this to work correctly on Linux desktop.

It's taking an unreasonably long time (~50s) to call `read`/`containsKey`, and about 60s to call `write`. Also, I'm not sure anything is actually getting written because calling `read` on fresh app start always returns `null`.

It's very likely it's not a problem with the package, since it seems to be the blocking call to `secret_password_lookupv_sync` that is taking so long (and presumably also not working correctly). I do have `gnome-keyring-daemon` running as I use it as my ssh agent.

Any tips for where to look into?

Relevant parts of `lutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.10.3, on Arch Linux 5.16.16-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/shroff/sandbox/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.22.3
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 5.16.16-zen1-1-zen
```

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
