### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by jwinarske** [mogol/flutter_secure_storage#384]
The project is missing a license file.

**Comment by jwinarske** [comment]
Yes I looked it up based on the link.  It is not referenced anywhere else, such as someone coming across a folder of the source.  

In my case I'm using it in the context of Yocto/OpenEmbedded.  The expectation of this build framework is that it has an explicit license file in the actual repo.

It's a formality.

**Comment by juliansteenbakker** [comment]
It's in the repo, however it's under the folder flutter_secure_storage. I will copy it to the main directory as well.
