### ISSUE TITLE
Private Browsing in Firefox not working

### ISSUE THREAD

**Issue by Pe-te** [mogol/flutter_secure_storage#389]
We have a flutter app with flutter_secure_storage.

When running the web version in a private firefox window, it does not work. In a normal window it works fine.

Is this a limit of flutter_secure_storage? Are there any settings we can change to make it work? (in the app, in firefox, ..)

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
