### ISSUE TITLE
Update the gradle please

### ISSUE THREAD

**Issue by saeedtaha96** [mogol/flutter_secure_storage#393]
A problem occurred configuring project ':flutter_secure_storage'.
> Could not resolve all files for configuration ':flutter_secure_storage:classpath'.
   > Could not find gradle-7.0.3.jar (com.android.tools.build:gradle:7.0.3).

**Comment by wh120** [comment]
same

**Comment by juliansteenbakker** [comment]
Fixed on develop, will be released asap.

**Comment by chriskikoti** [comment]
What is the solution? I am having the same issue

**Comment by chriskikoti** [comment]
> What is the solution? I am having the same issue

Sorted after migrating flutter_secure_storage to 5.1.0 from 5.0.2
