### ISSUE TITLE
iOS debug builds are not persisting keychain data after background

### ISSUE THREAD

**Issue by derekpitts28** [mogol/flutter_secure_storage#394]
Setup: Simple app with two buttons. 1 button writes and another reads. I am on a physical device iPhone6s ios14.6. I write a simple key and value. Then I read it and it works. Background the app. Foreground the app. Read same key. It doesn't exist.

I cannot figure out what the issue is other than maybe debug builds keychains are cleared when apps are backgrounded?

Does iOS need some amount of time other than waiting for the async to ensure the key gets written to the keychain?

NOTE1: I am NOT making any keychain reads/writes during background.
NOTE2: I already looks into the accessibility in the options and that I don't think relates to this as the phone is already unlocked.

Thanks!

**Comment by Enigma-I-am** [comment]
I am having a similar issue with this plugin

**Comment by Zfinix** [comment]
> I am having a similar issue with this plugin

You don't say ...

**Comment by derekpitts28** [comment]
Sorry I found out that we had another plugin that was clearing the entire key chain on foreground RIP 😭

**Comment by Enigma-I-am** [comment]
@derekpitts28 what plugin is this??

Might be a similar issue for me

**Comment by derekpitts28** [comment]
Okta sdk for ios. We wrote a plugin for it and the example it gives has us doing a full clear. We changed it so it only clears what is necessary.
