### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')

### ISSUE THREAD

**Issue by theTrivia** [mogol/flutter_secure_storage#404]
Getting error `Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')` only when I run the flutter app over any server (apache2 in my case)

App is working fine w/ iOS,android.
It is working fine when I run the app with flutter run -d chrome.

Flutter code:
```
Column(
        children: [
          RaisedButton(
            onPressed: () async {
              await secureStorage.write(key: 'abc', value: '123');
            },
            child: Text('Save'),
          ),
          RaisedButton(
            onPressed: () async {
              var abc = await secureStorage.read(key: 'abc');
              print(abc);
            },
            child: Text('print'),
          ),
          RaisedButton(
            onPressed: () async {
              await secureStorage.deleteAll();
            },
            child: Text('del'),
          ),
        ],
      )),
```

Issue is seen with the `write()` method.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/36889758/172446963-f832e937-732a-42e5-8391-3bc2e460f983.png">

```
main.dart.js:3688 Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')
    at main.dart.js:44307:36
    at Wb.a (main.dart.js:4831:63)
    at Wb.$2 (main.dart.js:25495:14)
    at Object.a2 (main.dart.js:4817:11)
    at Jh.IY (main.dart.js:44319:10)
    at Jh.hc (main.dart.js:44287:21)
    at main.dart.js:44331:14
    at Wb.a (main.dart.js:4831:63)
    at Wb.$2 (main.dart.js:25495:14)
    at Object.a2 (main.dart.js:4817:11)
```

**Comment by GabrieleVolpato** [comment]
Hello,
I'm having the exact same issue using Flutter 3.0.2.
The very strange thing is that, in my case, I dockerized the web application and it works fine if I run the container on my machine: whenever I deploy the exact same docker image on the external server I run into this issue.

**Comment by theTrivia** [comment]
The package is working fine after enabling HTTPS.
