### ISSUE TITLE
Written data removed automatically immediately in MacOs

### ISSUE THREAD

**Issue by ShourovRoy** [mogol/flutter_secure_storage#406]
Written data removed automatically immediately in MacOs.

**Comment by jayjah** [comment]
Same here with `flutter_secure_storage: ^8.0.0`

**Comment by gnunicorn** [comment]
still experiencing this on `^9.0.0` on macos...

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
