### ISSUE TITLE
NOT WORKING ON WINDOWS !!!!

### ISSUE THREAD

**Issue by parsa10** [mogol/flutter_secure_storage#409]
it does not work on WINDOWS , it stops app from running with an error !

**Comment by 0xNF** [comment]
Works fine for me in most situations. What is your error?

**Comment by Glitched-Manual** [comment]
Same Issue?
https://github.com/mogol/flutter_secure_storage/issues/379#issuecomment-2041438817

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
