### ISSUE TITLE
Problem with Mock Unit Test - type 'Null' is not a subtype of type 'Future<void>'

### ISSUE THREAD

**Issue by kharisazhar** [mogol/flutter_secure_storage#416]
Hi, my flutter project now is support null safety, but when migrate unit test and create Mock for FlutterSecureStorage with [mocktail](https://pub.dev/packages/mocktail), then got error type 'Null' is not a subtype of type 'Future<void>'

expect mocktail is support for null safety too, 

Implementation :

```
import 'package:mocktail/mocktail.dart';

class MockFlutterSecureStorage extends Mock implements FlutterSecureStorage {}

void main(){
final mockFlutterSecureStorage = MockFlutterSecureStorage();

..
.. 

verify(() => mockFlutterSecureStorage.write(
            key: passwordKey, value: encrypted(data['password']))).called(1);

}
```

Error : 
type 'Null' is not a subtype of type 'Future<void>'

When i check flutter_secure_storage.dart :
the function **.write** is : `Future<void> write({  ...` 
then i try to add null safe operation :

`Future<void>? write({  ...` and yes it's works, Should the implementation like it ? 
if yes maybe i can create pull request, but not sure if code before is best pratice & no makes new issue/bug

Env : 
```
flutter_secure_storage: ^5.0.2

Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (3 weeks ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2
```

Thanks

**Comment by kharisazhar** [comment]
Update : for workaround you can use build_runner & mockito package for generate mocks and verify 



```
import 'package:mockito/mockito.dart' as mockito;

@GenerateMocks([FlutterSecureStorage])
void main(){
final mockFlutterSecureStorage = MockFlutterSecureStorage();

mockito.verify(mockFlutterSecureStorage.write(
            key: passwordKey, value: encrypted(data['password'])));
}

```

But i still expect flutter secure storage can be mocked by Mocktail

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
