### ISSUE TITLE
Example does not function on Custom embedder

### ISSUE THREAD

**Issue by jwinarske** [mogol/flutter_secure_storage#418]
As stated when running `flutter build bundle` AOT image on a custom Linux embedder [ivi-homescreen](https://github.com/toyota-connected/ivi-homescreen) platform type is not properly decoded.  Running runtime=debug image does work fine; see https://github.com/flutter/flutter/issues/103660.  I have native platform channel code implemented in ivi-homescreen, which interoperates with the example.

https://github.com/toyota-connected/ivi-homescreen

The usage of 1P plugin patterns only means that it supports the Flutter GTK embedder.  No other Linux embedder is supported.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
