### ISSUE TITLE
PEN test failed on iOS

### ISSUE THREAD

**Issue by prijupaul** [mogol/flutter_secure_storage#419]
Hi,
First of all thanks for the package. 

We use this package in our app and during PEN test, a high priority issue was raised. 
Please find the attached

![image](https://user-images.githubusercontent.com/3048087/181230077-6b173118-9d61-4e31-8720-4c73517c2a42.png)

Risk Mitigation:

![image](https://user-images.githubusercontent.com/3048087/181230192-0f23e90d-39de-422d-9487-b9a7368b265c.png)

It is possible to address this issue on priority, please?

Thanks

**Comment by hm122** [comment]
Support for biometric storage protection would be great for both iOS and Android.
