### ISSUE TITLE
3.2.0 'no implementation found'

### ISSUE THREAD

**Issue by blaneyneil** [mogol/flutter_secure_storage#42]
Caught error: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)

#1      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:16:24)

[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.8 at /Users/neil/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

**Comment by blaneyneil** [comment]
sorry, this is no longer an issue after i created a new virtual android device.

**Comment by mogol** [comment]
Is it fresh install? 
Hot reload doesn’t work first time, because it contains native code. Try to re launch the apl
