### ISSUE TITLE
Add a way to watch/listen changes

### ISSUE THREAD

**Issue by ValentinVignal** [mogol/flutter_secure_storage#420]
It would be very useful to be able to listen to changes of a set of keys/any key in the secure storage and be notify when it happens.

For example [`hive`](https://pub.dev/packages/hive) allows you to listen to a change on specific keys or all the keys of a box  (see the [doc](https://docs.hivedb.dev/#/basics/hive_in_flutter)).

**Comment by hmawla** [comment]
You can use other dependencies for now to watch for changes, or create a simple state tracker since I don't think that this will be implemented anytime soon...

**Comment by MohamadGreatWarrior** [comment]
I've created this pull request: https://github.com/mogol/flutter_secure_storage/pull/640

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
