### ISSUE TITLE
change documentation 5.1.0

### ISSUE THREAD

**Issue by rmasarovic** [mogol/flutter_secure_storage#425]
Hi guys i just build app with new 5.1.0 and little breaking change i found 
 change IOSAccessibility.first_unlock to  KeychainAccessibility.first_unlock,
maybe it will be good change example documention for begginers.

**Comment by juliansteenbakker** [comment]
Thank you for reporting this and my apologies. I have added it to the readme.md.

**Comment by henry2man** [comment]
> Thank you for reporting this and my apologies. I have added it to the readme.md.

@juliansteenbakker In current README.md and/or CHANGELOG.md there aren't any mention on this breaking change :/

**Comment by Heech** [comment]
Yes, looks like the [Getting Started](https://pub.dev/packages/flutter_secure_storage#getting-started) part in the README.md is still saying to use old IOSAccessibility.
