### ISSUE TITLE
Implement flutter_secure_storage for web (All the precautions)

### ISSUE THREAD

**Issue by paulFlow33** [mogol/flutter_secure_storage#427]
hey, I've seen your documents where you quote web pages for the HTTP Strict-Transport-Security issue. Not only that, I have read some issues and have not personally found clarity on the matter. I understood that it can be done, but I did not understand how? That is, how is Strict-Transport-Security activated? Excuse my ignorance.

Can anyone kindly list what I should do using this library for the web? A thousand thanks

**Comment by paulFlow33** [comment]
Can you kindly have some documentation? Nothing is explained, what should the map you pass to read () contain for the web implementation? Also I had to manually import the package for the web.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
