### ISSUE TITLE
FlutterSecureStorage.read broken on Android 9.0 Samsung only

### ISSUE THREAD

**Issue by KathLevi** [mogol/flutter_secure_storage#43]
I just got Android 9.0 pie on my phone (physical not virtual). Everything was working fine and then once I downloaded 9.0 this error occurred. My co-worker has an Android but not a Samsung and it works fine but my Samsung produces this error when trying to read from secure storage. (Writing to secure storage doesn't seem to be an issue). Possibly locked keychain? Not sure if this fix is local or if anyone else experiences this issue.

`E/flutter (31692): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (31692): PlatformException(error, Unsupported value: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, null)
E/flutter (31692): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (31692): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (31692): <asynchronous suspension>
E/flutter (31692): #2      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:16:24)
E/flutter (31692): <asynchronous suspension>
E/flutter (31692): #3      main (package:phone_app/main.dart:27:11)
E/flutter (31692): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (31692): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)`

**Comment by mogol** [comment]
Hi @KathLevi ,
is it fresh install/updates/restore? debug/release? from Play Store?
And what model?

**Comment by MilloshFey** [comment]
Same thing here on Samsung Galaxy J7 Prime.
It happened when updated to:
"Version: G610MUBS4CSB4/G610MZTO4CSB1/G610MUBS4CSB1"

**Comment by KathLevi** [comment]
@mogol It is a fresh install, debug, not from the play store but from my local machine. My phones are a Samsung Galaxy S8 and a Samsung Galaxy S9.

**Comment by alsocalledchris** [comment]
I'm getting this error too - not sure if it's a issue between using release and debug builds on the same phone? (side-loaded not via playstore). It won't go away when I try and un-install and then re-install the App.

**Comment by MilloshFey** [comment]
Well... I kind of got it working trying some weird things. 
In the screen you can see where's my problem, maybe its yours too.
To solve I just called ".deleteAll();" (or _sotrage.deleteAll(); following the example provided by the autor).
I just call it at app's first run 
![error](https://user-images.githubusercontent.com/46675702/54033233-84c45200-4192-11e9-9858-f6ae02100020.png)
using a "SharedPreferences _firstRun" variable.

**Comment by mogol** [comment]
> I think its something with the keys recovery...idk
It looks like Samsung devices restore SharedPreferences.

I am looking for a device to debug the issue.

**Comment by MilloshFey** [comment]
Yep, I think you're right. My sharedPrefs was weird as well. I solved this by adding 
``` xml        
        android:allowBackup="false"
        android:fullBackupContent="false"
```
on AndroidManifest.xml.
So it can stop restoring stuff.

**Comment by mogol** [comment]
If you need `fullBackupContent="yes"`, you can [disable backup](https://developer.android.com/guide/topics/data/autobackup#IncludingFiles) of prefs used by the plugin.

```
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <exclude domain="sharedpref" path="FlutterSecureStorage"/>
</full-backup-content>
```

**Comment by cirediew** [comment]
<application
        ...
            android:allowBackup="false"
            android:fullBackupContent="false">

This worked for me.
However, a fresh install was needed to make it work.

**Comment by szotp** [comment]
You can also catch the error and erase the failing value.

**Comment by VernonGrant** [comment]
I can confirm the same issue is being reported by a few of our clients.

**Comment by ncuillery** [comment]
Sorry it's unclear to me. Why would I need to set both `android:allowBackup="false"` *and* `android:fullBackupContent="false"` ?

According to the [Android doc](https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup), the latter is used to configure which data should be include/exclude when `allowBackup` is enabled, right?

So, if I understand correctly, there are 2 viable solutions:

#### Option 1: Disable backup completely:

```xml
<application
    ...
        android:allowBackup="false">
```

#### Option 2: Keep backup enable but exclude the shared pref used by this plugin:

```xml
<application
    ...
        android:allowBackup="true" 
        android:fullBackupContent="@xml/backup_rules">
```

and this file `res/xml/backup_rules.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <exclude domain="sharedpref" path="FlutterSecureStorage"/>
</full-backup-content>
```

Am I correct?

**Comment by eimermusic** [comment]
For my app, it seems like once a user runs into this issue, they will not get out of it simply by the addition of the manifest changes. Trying to communicate with this random app user is also not easy to try to get them to uninstall and reinstall.

My question is: Can I catch this exception in Flutter-space and handle it more gracefully?

I saw a comment somewhere among the discussions here on Github that suggested catching the exception and then running deleteAll(). Would this work? I ask because I cannot reproduce this locally. I can only debug this by releasing a new version and then watching the error reporting service for a day or two waiting for results from the handful of users that have run into this error.

Something like:

```dart
    try {
      String accessToken = await storage.read(key: accessTokenKey);
      // obviously there is more code here
    } on PlatformException catch (exception) {
      storage.deleteAll();
      // report the error as a "handled" error for confirmation
    }

**Comment by bartonhammond** [comment]
I had two users w/ this problem and I did both recommendations from above:
```
Future<String> getEmail() async {
    String rtn;
    try {
      rtn = await flutterSecureStorage.read(key: storageUserEmailAddressKey);
    } catch (e) {
      //https://github.com/mogol/flutter_secure_storage/issues/43
      flutterSecureStorage.deleteAll();
    }
    return rtn;
  }
```
and this:
```
<application
    ...
        android:allowBackup="true" 
        android:fullBackupContent="@xml/backup_rules">
```
and this file res/xml/backup_rules.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <exclude domain="sharedpref" path="FlutterSecureStorage"/>
</full-backup-content>
```
And the issue was resolved

**Comment by aarjan** [comment]
i get this error when i include the backup_rules.xml, 
```
backup_rules.xml: Error: Can't determine type for tag '<exclude domain="sharedpref" path="FlutterSecureStorage"/>'
```
@ncuillery any help appreciated!!

**Comment by slaci** [comment]
When choosing to exclude the shared preferences file from backup (`Option 2` of https://github.com/mogol/flutter_secure_storage/issues/43#issuecomment-674412687), now there is an additional XML file which must? be defined, if the app targets Android 12 or higher: https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12

As the doc says for the [Android 11 and lower way](https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-11):

> Important: These XML backup rules are also used for devices running Android 12 or higher unless your app targets Android 12 (API level 31) or higher. In that case, you must [specify an additional set of XML backup rules](https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-12) to support the [changes to backup restore](https://developer.android.com/about/versions/12/backup-restore) that were introduced for devices running Android 12 or higher.

This means **one more** attribute for the `<application>` tag in the manifest and **one more** XML file.

In AndroidManifest.xml:
```xml
<application
    ...
        android:dataExtractionRules="@xml/data_extraction_rules">
```

Create `res/xml/data_extraction_rules.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
 <cloud-backup>
   <include domain="sharedpref" path="."/>
   <exclude domain="sharedpref" path="FlutterSecureStorage"/>
 </cloud-backup>
</data-extraction-rules>
```

Not sure if the `<include>` tag is needed, maybe the `<exclude>` is enough. I grabbed it from the linked Android docs.

Currently Flutter `3.3.9` defines `targetSdkVersion` as `31`, so the above may be required for new apps: https://github.com/flutter/flutter/blob/3.3.9/packages/flutter_tools/gradle/flutter.gradle#L39

Of course disabling backup by setting `android:allowBackup="false"` is still a valid option. In that case the above shouldn't be done.

**Comment by cpuell** [comment]
For anyone ending up here:

https://stackoverflow.com/a/67026552/7735112

**Comment by jacekwitkowski** [comment]
√] Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.22621.2861], locale pl-PL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.19)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] VS Code (version 1.85.1)
[√] Connected device (4 available)
[√] Network resources

sitll got the same issue. read from FlutterSecureStorage returns true not a value.

**Comment by RudrThakur** [comment]
Year 2024, if you still face this issue, the solution still works - https://github.com/mogol/flutter_secure_storage/issues/43#issuecomment-471642126

**Comment by keith-lytc** [comment]
Hello a quick question. Should this file also be excluded from `fullBackupContent` and `dataExtractionRules`?

```
<exclude domain="sharedpref" path="FlutterSecureKeyStorage.xml"/>
```

This seems to be an additional file generated by the plugin. I haven't look into what it does exactly, but when a backup is restored without excluding this file, this error is printed in LogCat.

```
E/StorageCipher18Impl( 3311): unwrap key failed
E/StorageCipher18Impl( 3311): java.security.InvalidKeyException: Failed to unwrap key
E/StorageCipher18Impl( 3311):   at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:820)
E/StorageCipher18Impl( 3311):   at javax.crypto.Cipher.unwrap(Cipher.java:2459)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.unwrap(RSACipher18Implementation.java:58)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:39)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.ciphers.StorageCipherAlgorithm$$ExternalSyntheticLambda0.apply(D8$$SyntheticClass:0)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.ciphers.StorageCipherFactory.getSavedStorageCipher(StorageCipherFactory.java:78)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.initStorageCipher(FlutterSecureStorage.java:185)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.ensureInitialized(FlutterSecureStorage.java:162)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.containsKey(FlutterSecureStorage.java:64)
E/StorageCipher18Impl( 3311):   at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:147)
E/StorageCipher18Impl( 3311):   at android.os.Handler.handleCallback(Handler.java:995)
E/StorageCipher18Impl( 3311):   at android.os.Handler.dispatchMessage(Handler.java:103)
E/StorageCipher18Impl( 3311):   at android.os.Looper.loopOnce(Looper.java:273)
E/StorageCipher18Impl( 3311):   at android.os.Looper.loop(Looper.java:363)
E/StorageCipher18Impl( 3311):   at android.os.HandlerThread.run(HandlerThread.java:85)
E/StorageCipher18Impl( 3311): Caused by: javax.crypto.IllegalBlockSizeException
E/StorageCipher18Impl( 3311):   at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:640)
E/StorageCipher18Impl( 3311):   at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:818)
E/StorageCipher18Impl( 3311):   ... 14 more
E/StorageCipher18Impl( 3311): Caused by: android.security.KeyStoreException: Unknown error (internal Keystore code: -1000 message: system/security/keystore2/src/operation.rs:852:
KeystoreOperation::finish
E/StorageCipher18Impl( 3311): 
E/StorageCipher18Impl( 3311): Caused by:
E/StorageCipher18Impl( 3311):     0: system/security/keystore2/src/operation.rs:433: Finish failed for uid 10499
E/StorageCipher18Impl( 3311):     1: Error::Km(r#UNKNOWN_ERROR)) (public error code: 10 internal Keystore code: -1000)
E/StorageCipher18Impl( 3311):   at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:465)
E/StorageCipher18Impl( 3311):   at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:79)
E/StorageCipher18Impl( 3311):   at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:132)
E/StorageCipher18Impl( 3311):   at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
E/StorageCipher18Impl( 3311):   at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
E/StorageCipher18Impl( 3311):   at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:630)
E/StorageCipher18Impl( 3311):   ... 15 more
```

The null values are correctly returned by the library for all, but excluding this file helps silence the error.
