### ISSUE TITLE
Static linking of libjsoncpp

### ISSUE THREAD

**Issue by rekire** [mogol/flutter_secure_storage#433]
When I start my flutter application on a fresh Ubuntu install (ubuntu-22.04.1-desktop-amd64) I get the error:
> error while loading shared libraries: libjsoncpp.so.1: cannot open shared object file: No such file or directory

I found out that this comes from this dependency. Is there a way to static link this dependency so that I can escape the dependency hell?

Background is when I run this command:

>myApp/lib$ ldd libflutter_secure_storage_linux_plugin.so | grep json
>	libjsoncpp.so.1 => not found

The dependency is not found, if this would would be static linked into I would be able to run my app on linux with this flutter library.

**Comment by talhabalaj** [comment]
I was thinking of statically linking it as well. I don't remember what issues I ran into, but I decided to dynamically link it. If you have time, you should invest into opening a PR.

**Comment by rekire** [comment]
To be honest, I was already checking if I could manage this, but I don't understand right now how static linking works in cmake files.
