### ISSUE TITLE
I Got Error On Iphone When Put String, After App Run 1 Weeks

### ISSUE THREAD

**Issue by deyong84** [mogol/flutter_secure_storage#434]
flutter_secure_storage: ^3.3.1+1

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 12.5 21G72 darwin-x64, locale en-ID)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.69.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
iwansupratman@Iwans-MacBook-Pro ios % fvm flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on macOS 12.5 21G72 darwin-x64, locale en-ID)
    • Flutter version 1.22.6 at /Users/iwansupratman/fvm/versions/1.22.6
    • Framework revision 9b2d32b605 (1 year, 7 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/iwansupratman/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/iwansupratman/Library/Java/JavaVirtualMachines/corretto-1.8.0_342/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.342.07.3 (build 1.8.0_342-b07)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 14.0, Build version 14A5284g
    • CocoaPods version 1.10.0

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (1 available)
    • iPhone 6 (mobile) • 513f5bca36b9c1c3ee70b2a93aaafec0a2c82e27 • ios • iOS 12.5.5

This log happend when app intalled after 1 week.

flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: HiveError: This should not happen. Please open an issue on GitHub.
flutter: 
#0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249:7)
#1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
#2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
<asynchronous suspension>
#3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:30)
<asynchronous suspension>
#4      BoxBaseImpl.initialize (package:hive/src/box/box_base_impl.dart:90:20)
#5      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:22)
<asynchronous suspension>
#6      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:18)
#7      Storage.putString (package:dooet_flutter/shared/storage.dart:46:26)
<asynchronous suspension>
#8      User.setSessionKey (package:dooet_flutter/shared/user.dart:127:19)
#9      _LoginPageState.authSuccess (package:dooet_flutter/pages/login/login_page.dart:809:16)
#10     _LoginPageState.build.<anonymous closure> (package:dooet_flutter/pages/login/login_page.dart:970:15)
#11     _BlocListenerBaseState._subscribe.<anonymous closure> (package:flutter_bloc/src/bloc_listener.dart:193:26)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#18     _SkipStream._handleData (dart:async/stream_pipe.dart:393:10)
#19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#20     _rootRunUnary (dart:async/zone.dart:1198:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#25     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#26     _StreamController._add (dart:async/stream_controller.dart:682:7)
#27     _StreamController.add (dart:async/stream_controller.dart:624:5)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#33     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#34     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#35     _rootRun (dart:async/zone.dart:1182:47)
#36     _CustomZone.run (dart:async/zone.dart:1093:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#39     _rootRun (dart:async/zone.dart:1190:13)
#40     _CustomZone.run (dart:async/zone.dart:1093:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
flutter: ----------------------------------------------------
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: HiveError: This should not happen. Please open an issue on GitHub.
flutter: 
#0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249:7)
#1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
#2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
<asynchronous suspension>
#3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:30)
<asynchronous suspension>
#4      BoxBaseImpl.initialize (package:hive/src/box/box_base_impl.dart:90:20)
#5      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:22)
<asynchronous suspension>
#6      HiveImpl.openBox (package:hive/src/hive_impl.dart:135:18)
#7      Storage.putString (package:dooet_flutter/shared/storage.dart:46:26)
<asynchronous suspension>
#8      User.setSessionKey (package:dooet_flutter/shared/user.dart:127:19)
#9      _LoginPageState.authSuccess (package:dooet_flutter/pages/login/login_page.dart:809:16)
#10     _LoginPageState.build.<anonymous closure> (package:dooet_flutter/pages/login/login_page.dart:970:15)
#11     _BlocListenerBaseState._subscribe.<anonymous closure> (package:flutter_bloc/src/bloc_listener.dart:193:26)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#18     _SkipStream._handleData (dart:async/stream_pipe.dart:393:10)
#19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#20     _rootRunUnary (dart:async/zone.dart:1198:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#25     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#26     _StreamController._add (dart:async/stream_controller.dart:682:7)
#27     _StreamController.add (dart:async/stream_controller.dart:624:5)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#33     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#34     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#35     _rootRun (dart:async/zone.dart:1182:47)
#36     _CustomZone.run (dart:async/zone.dart:1093:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#39     _rootRun (dart:async/zone.dart:1190:13)
#40     _CustomZone.run (dart:async/zone.dart:1093:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
flutter: ----------------------------------------------------
Lost connection to device.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
