### ISSUE TITLE
false format of saving the key on linux

### ISSUE THREAD

**Issue by j0chn1** [mogol/flutter_secure_storage#438]
Hey there,
I am using your plugin to store a securing key like this:
` const FlutterSecureStorage secureStorage = FlutterSecureStorage();
    if (!await secureStorage.containsKey(key: 'key') &&
        await secureStorage.read(key: 'key') == null) {
      await secureStorage.write(
          key: 'key', value: base64UrlEncode(Hive.generateSecureKey()));
    }
    var encryptionKey =
        base64Url.decode(await secureStorage.read(key: 'key') as String);`
Now I got a ticket which mentiones, that the key is stored in a wrong format (on linux) which leads in an unreadable keyring and a new one has to be created.

Please be so kind and have a look at:
https://gitlab.com/j0chn/nextcloud_password_client/-/issues/29
The ticket is described pretty well.

Thank you very much !!!

**Comment by j0chn1** [comment]
Nearly one year is over now. 
Did you have a chance to check this topic?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
