### ISSUE TITLE
fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by joeythomaschaske** [mogol/flutter_secure_storage#44]
after installing the package and running flutter run I get an error

```
Macbook-pro:app joseph$ flutter run
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...                                              1.0s
Running Xcode build...                                                  
Xcode build done.                                            0.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET flutter_secure_storage OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from
    /Users/joseph/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.2.0/ios/Classes/FlutterSecureStoragePlug
    in.m:1:
    /Users/joseph/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.2.0/ios/Classes/FlutterSecureStoragePlug
    in.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.
```

I think it is the package because I ran flutter run before adding the package and everything ran perfectly. This has happened to me twice now after adding the package

**Comment by joeythomaschaske** [comment]
After removing the flutter sdk and reinstalling it everything works normally. I'm not sure what corrupts the flutter sdk with a package install though..

**Comment by mogol** [comment]
hi @joeythomaschaske 
can you provide output of `flutter run -v` and `flutter doctor`

**Comment by joeythomaschaske** [comment]
Hey @mogol 

I found a work around and it seems more like a flutter issue than a package issue. I've opened an issue with the flutter team.

 I can still run `flutter run -v` and `flutter doctor` if you're still interested in it

https://github.com/flutter/flutter/issues/29028

**Comment by mogol** [comment]
I got the issue. Thanks for the update!
