### ISSUE TITLE
Warning: The plugin flutter_secure_storage requires Android SDK version 32.

### ISSUE THREAD

**Issue by declan-m** [mogol/flutter_secure_storage#440]
Why does the documentation say Min 18 but the console says 32? Is it just a compiling requirement?

**Comment by AhmetMelihSerter** [comment]
Your compileSdkVersion is less than 32. But the package compileSdkVersion is 32.

**Comment by declan-m** [comment]
> Your compileSdkVersion is less than 32. But the package compileSdkVersion is 32.

yes but the documentation of this plugin says sdkVersion 18

**Comment by techouse** [comment]
> > Your compileSdkVersion is less than 32. But the package compileSdkVersion is 32.
> 
> yes but the documentation of this plugin says sdkVersion 18

It says `minSdkVersion` must be 18 or above. [The `compileSdkVersion` or Flutter is currently 31](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L33).

**Comment by AhmetMelihSerter** [comment]
Package compileSdkVersion 33

https://github.com/mogol/flutter_secure_storage/blob/0e1be9a326ba55786bd36d4d2b1093754b426a66/flutter_secure_storage/android/build.gradle#L24-L41

**Comment by juliansteenbakker** [comment]
Your compile sdk should always be the latest possible. The minsdkversion refers to the lowest android version it can run on.

**Comment by emrbli** [comment]
tammadır. p0rn0
