### ISSUE TITLE
Possible issue where values are deleted from storage on newer versions? 

### ISSUE THREAD

**Issue by alliha** [mogol/flutter_secure_storage#441]
I am using flutter secure storage 5.1.2, after upgrading my dependencies (used to be on 3.2.0) and have been running into situations where the stored value has been removed. 

We use this package as a way of storing database-responses, so that they are available. To test our functionality we make the device disconnect and reconnect at various stages. While doing this we discovered that sometimes the stored/saved key-value pairs would simply disappear. 

When rolling back the dependency upgrade, we do not encounter the same issue which makes me wonder if there is a situation where the storage would be cleared out?

**Comment by juliansteenbakker** [comment]
It can happen that the data gets reset after an update or other event. For example, version 5.0.0 introduced EncryptedSharedPreference for android and not all versions had a proper upgrade system for the data. Also, we relay on other libraries for android to save encrypted data. If any of those libraries encounter any issue with encryption keys, they automatically reset everything and start fresh.
