### ISSUE TITLE
Android Implementation - Make read and write methods public

### ISSUE THREAD

**Issue by teranpeterson** [mogol/flutter_secure_storage#442]
In `FlutterSecureStorage.java`, is there a reason that all of the following methods are not public? Making these methods public would make it a lot easier for developers to access stored values from native Java/Kotlin. 

```java
boolean containsKey(String key);
String read(String key) throws Exception;
public Map<String, String> readAll() throws Exception;
void write(String key, String value) throws Exception;
public void delete(String key);
void deleteAll();
```

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
