### ISSUE TITLE
RSACipher18Implementation.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by Arcttyx** [mogol/flutter_secure_storage#446]
When I do "flutter build apk --release" the following message is showed in the console:

_Note: /Users/myuser/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-6.0.0/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java uses or overrides a deprecated API._

flutter_secure_storage: ^6.0.0
sdk: ">=2.17.0 <3.0.0"
Flutter 3.0.5
Dart 2.17.6
compileSdkVersion 33
minSdkVersion 21
targetSdkVersion 30

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale es-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.70.2)
[!] Connected device
    ! No devices available
[✓] HTTP Host Availability

**Comment by CartmanGD** [comment]
Facing the same issue

**Comment by prajwalcognerium** [comment]
Facing same issue

**Comment by eugenioadapta** [comment]
Facing same issue with Flutter 3.3.2

**Comment by saliouseck2009** [comment]
have same issues 3.3.3

**Comment by antoniodourado** [comment]
Same issue here as well.

**Comment by sungyan** [comment]
Same issue

**Comment by AliHG** [comment]
same here

**Comment by wryczko** [comment]
same issue

**Comment by luis8elias** [comment]
Same issue with flutter 3.3.7

**Comment by JoelOvien** [comment]
Same issue with Flutter 3.3.1

**Comment by juliansteenbakker** [comment]
This is fixed with version 6.1.0
