### ISSUE TITLE
web dont work - ver. 5.2.1/6.0.0

### ISSUE THREAD

**Issue by rmasarovic** [mogol/flutter_secure_storage#447]
Hi when i run web on debug mode  everything work. But when i build prod web and i go write/store value get this error. 

 ‼️ [ERROR]: global TypeError: Cannot read properties of undefined (reading 'generateKey')
    at /main.dart.js:107391:36
    at bfg.a (/main.dart.js:4367:62)
 ‼️ [ERROR]: global TypeError: Cannot read properties of undefined (reading 'generateKey')

**Comment by rmasarovic** [comment]
okey i was tried it on webserver without https.  it was problem

**Comment by leocape** [comment]
@rmasarovic how did you get around this locally?
