### ISSUE TITLE
Streaming a value

### ISSUE THREAD

**Issue by Faiyyaz** [mogol/flutter_secure_storage#455]
Hey,

Thanks for such a great library.

I just have one question, if I want to stream a value from the storage, can you let me know how can I do it?

Usecase for the above requirement, suppose auth token has been deleted on logout, then it should automatically then that will trigger the stream which in turn will handle the navigation.

**Comment by danijorda1** [comment]
return StreamBuilder(
      stream: storage.read(key: "token").asStream(),
           builder: (context, snapshot) {
}
);

**Comment by alarkirikal** [comment]
> return StreamBuilder( stream: storage.read(key: "token").asStream(), builder: (context, snapshot) { } );

`.asStream()` just creates a one time event stream from this future and completes. It will not stay listening.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
