### ISSUE TITLE
[iOS 16]FlutterSecureStorage.containsKey returns true when FlutterSecureStorage. is empty 

### ISSUE THREAD

**Issue by dayveedaniel** [mogol/flutter_secure_storage#456]
on iOS 16 emulator secure storage.containskey returns true when secure storage is empty

```  void main() async {
const FlutterSecureStorage  _secStore =   FlutterSecureStorage();

  print ("content ${await _secStore.readAll()}");
  print ("contains key ${await _secStore.containsKey(key: 'randomKey')}");
}
runApp(...) 
```
<img width="727" alt="Screen Shot 2022-09-26 at 9 38 34 AM" src="https://user-images.githubusercontent.com/47108741/192183131-a12abe85-c2b8-43ac-9da7-a489576641a1.png">

**Comment by juliansteenbakker** [comment]
Can you please try with version 6.1.0-beta.1?

**Comment by marcellocamara** [comment]
It worked for me. Lets see it seems fine for @dayveedaniel too.

iPhone 14 Pro **Simulator** with iOS 16.0
```
environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '3.3.3'
```

**Comment by dayveedaniel** [comment]
works okay 👍

**Comment by juliansteenbakker** [comment]
Great to hear!

**Comment by marcellocamara** [comment]
@juliansteenbakker any plans to rollout the beta version into release/prod version ?

Just asking to skip this warning:
![Captura de Tela 2022-11-05 às 13 43 39](https://user-images.githubusercontent.com/18273071/200131518-88caae7a-5166-4749-b5ce-1d088fdc1382.png)
