### ISSUE TITLE
[Android] At app start, value is returned only after second read

### ISSUE THREAD

**Issue by ps-filipefreitas** [mogol/flutter_secure_storage#457]
In Android (api 33), I noticed a weird issue when using the storage at app start (ie, withing main).
It seems that reading a key will incorrectly return null, and immediately reading again will then return the value.
![Screen Shot 2022-09-30 at 16 01 29 PM](https://user-images.githubusercontent.com/109595986/193311686-af05d446-b6cd-4b8f-b5fe-cc45bf42f929.png)
I tested with encryptedSharedPreferences true and false, and it happens in both cases.
I haven't tested in iOS.

**Comment by JPdesconectado** [comment]
Same problem with the same configs.

**Comment by alvindrakes** [comment]
Is this problem happening on on Android?

Trying to gage whether we can use this package in production.

**Comment by ps-filipefreitas** [comment]
in android, didn't check on ios

**Comment by tattivitorino** [comment]
i am having this in production:

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.contains(java.lang.String)' on a null object reference at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:301) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:223) at android.os.Looper.loop(Looper.java:317) at android.os.HandlerThread.run(HandlerThread.java:67) , null). 

any ideas?

**Comment by Kerrely** [comment]
Same problem. Found out that deleting cache and app's data from App Info screen helps but you cannot tell this to clients.

**Comment by DavidIjsud** [comment]
@tattivitorino how did you solve it ?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
