### ISSUE TITLE
[Windows] error building the app with plugin

### ISSUE THREAD

**Issue by afandos-bbm** [mogol/flutter_secure_storage#458]
Error:
C:\...\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp(1,10): fatal error C1083: No se puede abrir el archivo incluir: 'include/flutter_secure_storage_windows/flutter_secure_storage_windows_plugin.h': No such file or directory [C:\...\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj] Exception: Build process failed.

Flutter doctor:
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Versi¢n 10.0.19044.2075], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.19)
[√] Android Studio (version 2021.3)
[√] VS Code, 64-bit edition (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

Plugin version: 6.0.0

Content in windows folder:
![Imgur](https://imgur.com/iBvfHW9.png)

**Comment by alejandrofan2** [comment]
Update: I've updated flutter, dart, recreated the project... It still doesn't work

**Comment by kamilkarp** [comment]
@alejandrofan2 Have you solved the problem? Just encountered it.

**Comment by alejandrofan2** [comment]
no @kamilkarp, not finding files for build in windows. I`m still waiting to teply from repo owners @mogol

**Comment by kamilkarp** [comment]
@alejandrofan2 For me this solved my problem: https://github.com/mogol/flutter_secure_storage/issues/379#issuecomment-1350496484

I had to install Visual Studio 2022 Community and select these in build tools options:
![image](https://user-images.githubusercontent.com/22731536/213712572-b97d3652-0427-4326-b322-6d2407c03162.png)

**Comment by alejandrofan2** [comment]
I tried but still not working.


my procedure has been:
1- Changed from VS 2019 to VS 2020
2- Installed ATL and MFC for (x86 and x64)
3- Also installed ATL and MFC for (x86 and x64) for Spectre Migrations
4- Run flutter clean
5- Removed windows directory and recreated with flutter create .
6- Run flutter pub get
7- Run flutter run -v 

Got same error:
 (ClCompile destino) ->
C:\Users\x\Documents\workspace\erp_crm_web\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp(1,10): fatal  error C1083: No se puede abrir el archivo incluir:
'include/flutter_secure_storage_windows/flutter_secure_storage_windows_plugin.h': No such file or directory [C:\Users\x\Documents\workspace\erp_crm_web\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]

Screenshot from VS Installer:
![screenshot](https://i.ibb.co/nb3xgH2/image.png)

**Comment by alejandrofan2** [comment]
Solved updating to 6.1.0 from 6.0.0 (Not working in previous versions)
