### ISSUE TITLE
Verify on pub.dev

### ISSUE THREAD

**Issue by h-unterp** [mogol/flutter_secure_storage#459]
Given this package is related to security, the publisher should be verified https://dart.dev/tools/pub/verified-publishers

**Comment by juliansteenbakker** [comment]
I am a verified publisher, however the package does not belong to me but to @mogol. I don't know what his views are if i verified the package with my account.

**Comment by mogol** [comment]
Hey @juliansteenbakker 
It works given you take of the package. Also we could move it to community project if it helps

**Comment by juliansteenbakker** [comment]
Ok! I'll verify it for now and if needed we can always move it to a community project.
