### ISSUE TITLE
Keystore exception -- 

### ISSUE THREAD

**Issue by sjmcdowall** [mogol/flutter_secure_storage#46]
The older issue is closed -- but I am still seeing this anytime I run/reload my Android app .. even on a branch new emulator device I created.. 

Any ideas? 

Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        39.9s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         4.3s
W/KeyStore(  605): KeyStore exception                                   
W/KeyStore(  605): android.os.ServiceSpecificException:  (code 7)       
W/KeyStore(  605):      at android.os.Parcel.createException(Parcel.java:1956)
W/KeyStore(  605):      at android.os.Parcel.readException(Parcel.java:1910)
W/KeyStore(  605):      at android.os.Parcel.readException(Parcel.java:1860)
W/KeyStore(  605):      at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
W/KeyStore(  605):      at android.security.KeyStore.get(KeyStore.java:195)
W/KeyStore(  605):      at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
W/KeyStore(  605):      at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
W/KeyStore(  605):      at java.security.KeyStore.getEntry(KeyStore.java:1560)
W/KeyStore(  605):      at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:113)
W/KeyStore(  605):      at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:33)
W/KeyStore(  605):      at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
W/KeyStore(  605):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
W/KeyStore(  605):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
W/KeyStore(  605):      at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:26)
W/KeyStore(  605):      at com.missionmode.mobile.MainActivity.onCreate(MainActivity.java:11)
W/KeyStore(  605):      at android.app.Activity.performCreate(Activity.java:7136)
W/KeyStore(  605):      at android.app.Activity.performCreate(Activity.java:7127)
W/KeyStore(  605):      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
W/KeyStore(  605):      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
W/KeyStore(  605):      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
W/KeyStore(  605):      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/KeyStore(  605):      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/KeyStore(  605):      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/KeyStore(  605):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
W/KeyStore(  605):      at android.os.Handler.dispatchMessage(Handler.java:106)
W/KeyStore(  605):      at android.os.Looper.loop(Looper.java:193)      
W/KeyStore(  605):      at android.app.ActivityThread.main(ActivityThread.java:6669)
W/KeyStore(  605):      at java.lang.reflect.Method.invoke(Native Method)
W/KeyStore(  605):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/KeyStore(  605):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mogol** [comment]
Hi @sjmcdowall 
what simulator version do you use?

**Comment by sjmcdowall** [comment]
I use the Nexus 6P API 28 launched out of the Android Studio AVD tool thing.  And yes, Android Studio is all up to date and all patches / updates applied.  In case you were going to ask :)

**Comment by mogol** [comment]
Yes, found similar [issue](https://stackoverflow.com/questions/52024752/android-9-keystore-exception-android-os-servicespecificexception/52295484#52295484).
I will add fix on the weekends.

**Comment by sjmcdowall** [comment]
Ah ha!  Looks perfect!  Great news, thanks!!

**Comment by mogol** [comment]
I have published 3.2.1. 
@sjmcdowall pls check it solves your problem and reopen the issue if not.
