### ISSUE TITLE
Wrong type for groupId parameter on iOS native implementation

### ISSUE THREAD

**Issue by aloys-c** [mogol/flutter_secure_storage#462]
Hi !

Planned to use the plugin with iOS App Groups to access the data from an extension. Yet, I just noticed the implementation for the groupId parameter on the native side is of type Int? when it should be a String passed to "ksecattraccessgroup", is it indeed a mistake or am I missing something ?

Best wishes

**Comment by juliansteenbakker** [comment]
This is fixed with version 6.1.0
