### ISSUE TITLE
Make the library test friendly

### ISSUE THREAD

**Issue by timnew** [mogol/flutter_secure_storage#471]
I ran into multiple issues while writing unit tests for some code depends on `FluttreSecureStorage`.

I tried using `mocktail` to create a fake instance, but run into issues, which is also mentioned by an existing ticket (https://github.com/mogol/flutter_secure_storage/issues/416)

And rather than having a mock, I might prefers a fake implementation that uses in memory storage, just like official `SharedPreferences` does.

So I created my own in memory fake implementation of `FlutterSecureStoragePlatform`, which works fine initially, but soon run into some very strange bugs that store returns stale data when multiple tests are involved.

After some debugging, I found the issue is caused because `FluttreSecureStorage` is making a copy of `FlutterSecureStoragePlatform.instance` into a private static final field `_platform`, which makes the test super tricky to setup.

So I created a PR(https://github.com/mogol/flutter_secure_storage/pull/470) to suggest some changes on the API, which make the lib more friendly to UT environment.

So developer can have following code:
```dart
const storage = FlutterSecureStorage();

setUp() {
  FlutterSecureStorage.setMockInitialValues({
     "key1": "value1",
     "key2": "value2",
  });
}
```

**Comment by bvoq** [comment]
This can be closed as it's implemented now.

**Comment by timnew** [comment]
Close this due to https://github.com/mogol/flutter_secure_storage/pull/470 is merged
