### ISSUE TITLE
Add possibility to invalidate storage after biometric changes

### ISSUE THREAD

**Issue by vscmaster** [mogol/flutter_secure_storage#474]
Hi folks,

Is it any chance to handle biometric changes in the package?

There are methods on platforms:
IOS: `evaluatedPolicyDomainState`
Android: `setInvalidatedByBiometricEnrollment`

Also investigated that package `biometric_storage` and unfortunately it doesn't manage those changes.

thank you,
hope the things are possible

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
