### ISSUE TITLE
Attention point related to "Padding Oracle", reported by MobSF, when using encryption mode, "AES/CBC/PKCS7Padding", in class "StorageCipher18Implementation.java".

### ISSUE THREAD

**Issue by ricardonostrum** [mogol/flutter_secure_storage#475]
Padding is a common practice in cryptography that consists of adding data at the beginning,
middle or end of a message before it is encrypted, being necessary for reasons of compatibility of the cryptographic algorithm that requires, for example, a specific number of characters or bytes for the correct functioning of the cryptographic function.
Oracle Padding is an attack in which a function decrypts messages and leaks the padding validity state, allowing the attacker to read sensitive data or escalate their privileges, without the need to know the key used in cryptographic operations. . The attack is commonly associated with the CBC (Cipher-Block Chaining) encryption mode, which encrypts data only in blocks of specific sizes, so it is necessary to use padding for the correct functioning of its algorithm. The padding schemes commonly used in these operations are PKCS5 and PKCS7.
It was identified, in the source code contained in the tested application, that CBC mode encryption is used with PKCS7 padding, creating a possible Oracle Padding attack vector in the application.

References

• CWE
– CWE-649: Reliance on Obfuscation or Encryption of Security-Relevant Inputs without
Integrity Checking23

Recommendation

It is recommended to change the CBC encryption mode to one of the considered authenticated modes, such as GCM (Galois/Counter Mode). As an alternative, the CBC mode could be maintained, but a MAC (Message Authentication Code) - also known as a tag -, such as the HMAC, must be implemented to verify the legitimacy of the transmitted data.

I await a response on the possibility of adaptations in the plugin.

Ricardo Magno da Silva
Nostrum Consultotia e Projetos.

**Comment by juliansteenbakker** [comment]
This is already possible using the following options:
```dart
const AndroidOptions(
        encryptedSharedPreferences: true,
      storageCipherAlgorithm: StorageCipherAlgorithm.AES_GCM_NoPadding
      );
```

**Comment by zjoart** [comment]
I tried this i still got the error reported by MobSF

The App uses the encryption mode CBC with PKCSS/PKCS7 padding. This configuration is vulnerable to padding oracle attacks

**Comment by mnnlthmpsn** [comment]
> I tried this i still got the error reported by MobSF
> 
> The App uses the encryption mode CBC with PKCSS/PKCS7 padding. This configuration is vulnerable to padding oracle attacks

Same here

**Comment by kaganzdmr58** [comment]
i tried it too and i get this error from MobSf "The App uses the encryption mode CBC with PKCS5/PKCS7 padding. This configuration is vulnerable to padding oracle attacks."
