### ISSUE TITLE
iOS persistent local storage data after reinstall

### ISSUE THREAD

**Issue by marcellocamara** [mogol/flutter_secure_storage#482]
Hello,

I've figured out that if you install your app, save data - in this case using the flutter_secure_storage `write()` method, close the app and complete delete it (removing it and deleting the data), when you reinstall the same app, if you read the same key that you saved data before, there it is - the method `read()` brings the data that you cleaned when you deleted the app. 

This is right ? 
I'm asking because, for me, it is a problem. I'm using this local storage to know if it's user first install.

```
Environment:
simulator iPhone 14 Pro Max - iOS 16.1
Flutter 3.3.9 - Dart 2.18.5
flutter_secure_storage: 6.1.0
```

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
