### ISSUE TITLE
[iOS] [6.0.1] crash in combination with hydrated_bloc and activated flightmode

### ISSUE THREAD

**Issue by sabifa** [mogol/flutter_secure_storage#484]
Hello,

I am experiencing a crash of my app when using `flutter_secure_storage` and `hydrated_bloc`.
I have created a [repository ](https://github.com/sabifa/secure_storage_hydrated_bloc) as a reproduction for the error.

## Steps to reproduce:
1. check out master
2. run app on iOS device
3. activate flight mode and close the app completely
4. launch app
5. crash (App does not start anymore)

With version `6.0.0` it does not crash:
1. check out 6.0.0
2. run app on iOS device
3. activate flight mode and close the app completely
4. launch app
6. App starts fine

In the changenotes it says that you have `Migrated from objective C to Swift` - could this be related?

Unfortunately, I can't gain any further insight into the crash as I have to close the app completely to force the crash and so I don't have any logs available. My hope is that you have a better way to debug the native code of the package to see if something is failing.

Thank you very much for taking a look!

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
