### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage))

### ISSUE THREAD

**Issue by Kyle-Mendes** [mogol/flutter_secure_storage#49]
`MissingPluginException (MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage))`

Not sure what happened, but I've been getting the title error every time I try to run my app. I removed the plugin files from my `.pub_cache` but the problem persists.  I don't think I'm doing anything out of the ordinary.  I've tried on multiple emulators and a physical device, but I just cannot get this to build.  

```dart
final storage = new FlutterSecureStorage();
String accessToken = await storage.read(key: 'access_token'); // <-- error
```

This wasn't a problem until today.  I think the only thing that might've borked my app would be doing a `git checkout` but I'm not sure.

**Comment by mogol** [comment]
Hi @Kyle-Mendes 
is it iOS or Android?

Flutter has such issue from time to time. You need to force dependency update, e.g. add new plugin , get packages and remove the plugin.

**Comment by Kyle-Mendes** [comment]
That doesn't seem to have worked, unfortunately

```[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.12.6 16G29, locale en-US)
    • Flutter version 1.3.8 at /Users/user/Projects/flutter
    • Framework revision e5b1ed7a7f (5 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone X                  • AFE355F9-BD65-4E01-AD21-956C7163274B • ios         • iOS 11.2 (simulator)

! Doctor found issues in 1 category.
```

**Comment by mogol** [comment]
I found this comment. Can you check 
https://github.com/flutter/flutter/issues/14137#issuecomment-447336721 ?

**Comment by Kyle-Mendes** [comment]
Just tried removing all of `ios` and `android`.  Ran `flutter create .` and then updated the gradle file to have the `minSdk` for this package.  I'm still encountering the title error however :(

**Comment by mogol** [comment]
Did you experience the same issue with another package with native plugins? Can you try any new package , eg Firebase or image pickers ?

**Comment by Kyle-Mendes** [comment]
I just tested a very simple app using the `image_picker` that you shared before, and was able to get it to run.


```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyHomePage());

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _image;

  Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);

    setState(() {
      _image = image;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    ));
  }
}

```

**Comment by Kyle-Mendes** [comment]
I actually think I might have fixed it!

I manually removed the app from my emulator (went to the app drawer, long pressed, app info, uninstall) and it seems to be building again. 

Thanks for the help in debugging this!

**Comment by mogol** [comment]
that’s great, 
you are welcome.

**Comment by craiglabenz** [comment]
@Kyle-Mendes That also worked for me when nothing else was

**Comment by vathlala** [comment]
Please also check your .kt file in android src which look likes:
`import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}`

**Comment by wilyanto** [comment]
After few hours of surfing. Finally **SOLVED** for me. Here is what I found out.

If you are calling `flutter_secure_storage` (or any packages) method in background service (as example, when you are using notification `onBackgroundMessage`). This exception occurred because usually our plugin registered at `main.dart` in foreground, but if we are calling our plugin's method in background we need to manually registered our plugin in our `app/src/main/[kotlin/java]/.../Application.[java or kt]`.

Inside the Application.java or Application.kt

<img width="992" alt="image" src="https://user-images.githubusercontent.com/53255602/106501831-2cb93600-64f6-11eb-8169-3468272a6fec.png">

After done that, do `flutter run` again. Hope it helps!
