### ISSUE TITLE
[iOS] Set access control flags through IOSOptions

### ISSUE THREAD

**Issue by Coyote79** [mogol/flutter_secure_storage#494]
I would like to [constraint the access to Keychain items](https://github.com/sensepost/objection/wiki/Understanding-the-iOS-Biometrics-Bypass). 

Is it possible to update IOSOptions to set access control flags like [kSecAccessControlBiometryAny](https://developer.apple.com/documentation/security/secaccesscontrolcreateflags/ksecaccesscontrolbiometryany) ?

Thanks

**Comment by 0xYao** [comment]
I wanted to use this feature too but I don't think it's available in the package yet

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
