### ISSUE TITLE
Rewrite (write on existing value) value not working

### ISSUE THREAD

**Issue by Shahriyar13** [mogol/flutter_secure_storage#496]
```
  @override
  Future<void> put(String key, String data) async {
    debugPrint('----------\nvalue before write: ${await get(key)}');
    debugPrint('trying to write: $data');
    await secureStorage.write(key: key, value: data);
    debugPrint('value after wrote: ${await get(key)}\n----------');
  }
```

flutter: ----------
flutter: value before write: null
flutter: trying to write: Test0
flutter: value after wrote: Test0
flutter: ----------

after trying to write again with same key:

flutter: ----------
flutter: value before write: Test0
flutter: trying to write: Test1
flutter: value after wrote: Test0
flutter: ----------

but after deleting and writing new it's working:

```
  @override
  Future<void> put(String key, String data) async {
    debugPrint('----------\nvalue before write: ${await get(key)}');
    debugPrint('trying to write: $data');
    await secureStorage.delete(key: key);
    await secureStorage.write(key: key, value: data);
    debugPrint('value after wrote: ${await get(key)}\n----------');
  }
```
  
flutter: ----------
flutter: value before write: Test0
flutter: trying to write: Test2
flutter: value after wrote: Test2
flutter: ----------

using latest version:

  flutter_secure_storage 7.0.1
  flutter_secure_storage_linux 1.1.2
  flutter_secure_storage_macos 2.0.1
  flutter_secure_storage_platform_interface 1.0.1
  flutter_secure_storage_web 1.1.1
  flutter_secure_storage_windows 1.1.3

Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-US)
Dart version 2.18.6

**Comment by kmoreau** [comment]
Hello,

I have the same error if i don't use delete if we have value. 

But if i put synchronizable = true in MacOsOptions, it's work.

what does synchronizable attribute ?

 flutter_secure_storage: 7.0.1
 Flutter 3.6.0-0.1.pre
 Dart 2.19.0

**Comment by heynext** [comment]
same issue

**Comment by robert-muriithi** [comment]
Facing the same issue

**Comment by idlehart** [comment]
> But if i put synchronizable = true in MacOsOptions, it's work.

This does not works for us. 
We have to delete the key first and then write the new.

**Comment by DarkHeros09** [comment]
Having the same issue.

**Comment by jaelee1993** [comment]
Hey guys, any update on this?

**Comment by colinbes** [comment]
Any news on this issue - I am seeing same behavior where I need to delete key before updating value.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
