### ISSUE TITLE
Flutter build fails on macos

### ISSUE THREAD

**Issue by CodeDoctorDE** [mogol/flutter_secure_storage#499]
If I upgrade the project to flutter_secure_storage 7 and flutter_secure_storage_macos 2.0.1, I get this error if I run `flutter run macos`:

```
   [!] CocoaPods could not find compatible versions for pod "flutter_secure_storage_macos":
                 In Podfile:
                   flutter_secure_storage_macos (from `Flutter/ephemeral/.symlinks/plugins/flutter_secure_storage_macos/macos`)

               Specs satisfying the `flutter_secure_storage_macos (from `Flutter/ephemeral/.symlinks/plugins/flutter_secure_storage_macos/macos`)` dependency were found, but they required a higher minimum deployment target.
```

I'm currently running on macOS 11.7.2

**Comment by gausoft** [comment]
Same issue

**Comment by heynext** [comment]
any updates here?

**Comment by gausoft** [comment]
I found a solution. First, I've switched the minimum Mac version from 10.11 to 10.13 in Podfile, after that, I remove the plugin and install It again

**Comment by gausoft** [comment]
Seriously? Let try in a new project. I'll get back to you

**Comment by gausoft** [comment]
@junhoolee check this issue [#7312](https://github.com/flutter/flutter/issues/73122)

**Comment by junhoolee** [comment]
@gausoft I solved it and the issue was really helpful, I appreciate it. Thanks!

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
