### ISSUE TITLE
iOS: Allow customizing kSecAttrAccessible

### ISSUE THREAD

**Issue by hpoul** [mogol/flutter_secure_storage#50]
I store tokens in the keychain which I need to access from a background process (background_fetch, and `content-available` push notifications) - to do this items have to be stored with `kSecAttrAccessible` = `kSecAttrAccessibleAlways`.

I think, the current implementation is a bit inconsistent, because on Android the default is that items can always be accessed, while on iOS the secure_storage can only be accessed while the user has unlocked the device.

**Comment by andersunloc** [comment]
This is really required for a lot of apps on the iOS side, and also the bug is pretty hard to test, so probably a lot of people will have issues when their data suddenly is not readable

**Comment by fvisticot** [comment]
I have the same issue. I need to get information from the keychain when the app is in background.
Is there any solution / workarround ?
