### ISSUE TITLE
keyset not found, will generate a new one. can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist

### ISSUE THREAD

**Issue by bugrevealingbme** [mogol/flutter_secure_storage#502]
There was no such problem before. I'm not sure if the error is related to this package.

/AndroidKeysetManager( 1749): keyset not found, will generate a new one. can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist

Flutter: 3.3.10
API 32

**Comment by pdax-king** [comment]
I'm having this same problem. 

We're planning to use the new feature `EncryptedSharedPreferences` to resolve the oracle padding attack issue but we're getting block by this issue. 

Flutter 3.3.10
API 21

Related Issues About Oracle Padding Attack
- https://github.com/mogol/flutter_secure_storage/issues/249
- https://github.com/mogol/flutter_secure_storage/issues/475

**Comment by arualana** [comment]
Same issue on Flutter 3.7.7 stable

**Comment by edilson14** [comment]
this [answer](https://stackoverflow.com/a/75785721) solved my problem

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
