### ISSUE TITLE
[Question] Do I need to make the key unique among different APPs?

### ISSUE THREAD

**Issue by theideasaler** [mogol/flutter_secure_storage#504]
Hi,

thanks for the great work of this package.

I am wondering when I write’ a key into secure storage in iOS and Android, do I need to make the key unique among different APPs?

e.g. if I have two Apps: App1 and App2 and both uses secure storage, do I need to add app prefix if the key to write is the same like ‘app1: key-to-write’ and ‘app2: key-to-write’?

Thanks in advance

**Comment by dJani97** [comment]
I'm pretty sure I'm just copy-pasting my storage layer in between apps, so some of my keys are the same. Apps don't seem to interfere with each other.

**Comment by theideasaler** [comment]
> 

Hi @dJani97 thanks for your reply and the case provided. 

Does it mean, the value of same key won't be override from different apps? I did't find very clear explanation from this package.

**Comment by pisolofin** [comment]
I've the same issue. 
In my company I have two application with two different application id ( it.company.applicationA and  it.company.applicationB ).
I use that code into the application A

    FlutterSecureStorage secureStorage = const FlutterSecureStorage(
        aOptions: AndroidOptions(
            encryptedSharedPreferences: true
        )
    );
    await secureStorage.write(key: "KeyValue", value: "Application A");

Into application B I use

    String? valueOfStorage = await secureStorage.read(key: "KeyValue");

The result is `valueOfStorage` is not null or value written of ApplicationB, but it's `Application A`.

It's a bug or it's right and I have to specify `accountName` into `iOptions`?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
