### ISSUE TITLE
[Question] Web private key storage

### ISSUE THREAD

**Issue by donaic** [mogol/flutter_secure_storage#509]
For the Web version, where is the private key stored to be used to decrypt?

**Comment by Lohann** [comment]
At `publicKey` localstorage:

https://github.com/mogol/flutter_secure_storage/blob/develop/flutter_secure_storage_web/lib/flutter_secure_storage_web.dart#L14

**Comment by Ahmadre** [comment]
> For the Web version, where is the private key stored to be used to decrypt?

The reason for web behind this is, that you can pass your own key:

https://github.com/mogol/flutter_secure_storage/blob/3bb93366161a787b07c45d8ce98c7405b40fbf1f/flutter_secure_storage/lib/options/web_options.dart#L7

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
