### ISSUE TITLE
iCloud backup

### ISSUE THREAD

**Issue by bee-warrior** [mogol/flutter_secure_storage#51]
Hello guys. I highly appreciate this library and I want to use it for my project. We would like to store crypto wallet private keys in secure storage and looks like it works fine. But as I know, if you delete an app your Keychain storage will be gone and after reinstalling the app you will lose your data. iOS applications can backup the Keychain to iCloud and the secure data can be restored from iCloud after user reinstalling the app. Is it possible to achieve with flutter?

**Comment by mogol** [comment]
Hi @bee-warrior 
Flutter runs on top of iOS, so it's possible. Likely it requires some work to add new API to the plugin to support https://developer.apple.com/documentation/security/ksecattrsynchronizable (the similar to #50 )
I will add this when I have time.

**Comment by x23b5** [comment]
How is it going here? =)

**Comment by jabonge** [comment]
is it solved? i faced it

**Comment by maxp89** [comment]
+1

**Comment by shredding** [comment]
+ 1

**Comment by juliansteenbakker** [comment]
This functionality has been merged and will be included in the next release.
