### ISSUE TITLE
Android: IllegalAcessError on flutter_secure_storage v7.0.* 

### ISSUE THREAD

**Issue by dmytrohurskyi** [mogol/flutter_secure_storage#511]
Hi! 
I use flutter_secure_storage in my flutter project like this: 

```
late FlutterSecureStorage _storage;

 _storage = const FlutterSecureStorage(
      aOptions: AndroidOptions(
        encryptedSharedPreferences: true,
      ),
    );
```

 and when I update package version to 7.0.0 or 7.0.1, Android app keeps crashing on startup with exception (release build): 

`Fatal Exception: java.lang.IllegalAccessError
Illegal class access: 'd.h.c.a.F.e' attempting to access 'com.google.crypto.tink.internal.n' (declaration of 'd.h.c.a.F.e' appears in /data/app/***app package name + some key***/base.apk)`

This happens only on release builds, on debug build app does not crash with v. 7.0.*

If I use flutter_secure_storage version 6.0.0, then app runs fine.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by ericomine** [comment]
I'm also having this issue, but my app is using v6.0.0 of flutter_secure_storage

**Comment by dmytrohurskyi** [comment]
@mogol can you help here?

**Comment by AbdulazizAlshami** [comment]
I also have the same issue in 9.0.0

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
