### ISSUE TITLE
Read on iOS fails silently and returns null instead of throwing platform exception.

### ISSUE THREAD

**Issue by janniklind** [mogol/flutter_secure_storage#519]
Hi.

I am investigating this plugin a bit, since I want to store an encryption key for the local database in my app.
It is crucial that this key is not lost, otherwise the data in the database will be lost.

I am performing a standard check like (pseudo code):
```
key = flutterSecureStorage.read('key');
if (key == null) {
  // On first app start.
  flutterSecureStorage.write('key', cipher.generateKey());
}
database.open(key)
```

However it seems from the following line in your code, that you ignore the status on the response and always just returns the value:
https://github.com/mogol/flutter_secure_storage/blob/develop/flutter_secure_storage/ios/Classes/SwiftFlutterSecureStoragePlugin.swift#L47

Do I understand correctly that is fails silently and instead returns null? That would be bad for the most usage of this plugin since you cannot count on what you get from the read method.

**Comment by gevork** [comment]
I having the same problem.
Wait any  solution

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
