### ISSUE TITLE
App Crashes on Startup (Android 4.4)

### ISSUE THREAD

**Issue by RuckyZucky** [mogol/flutter_secure_storage#52]
App Crashes on Samsung Galaxy S3 Neo (Android 4.4).
Exception in Logcat:
```04-20 16:30:42.742 3794-3794/com.it_nomads.fluttersecurestorageexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.it_nomads.fluttersecurestorageexample, PID: 3794
    java.lang.VerifyError: com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation
        at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
        at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
        at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
        at com.it_nomads.fluttersecurestorageexample.MainActivity.onCreate(MainActivity.java:12)
        at android.app.Activity.performCreate(Activity.java:5451)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
        at android.app.ActivityThread.access$900(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5476)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
```

I think the problem is the StrongBoxUnavailableException in the createKeys method (RSACipher18Implementation). I tried to comment it out and it works, but I have no idea how to replace it properly.

**Comment by DangLin012** [comment]
@RuckyZucky , @bbedward @hnvn @bcko , I found it is the same crash issue on HUAWEI Honor  (Android 4.4.2). I don't know how solve it.

**Comment by danielwii** [comment]
@DangLin012 I have make a change like [this](https://github.com/danielwii/flutter_secure_storage/commit/97bcdc729bfe27c892d2d7c705f021b2b6f5736e). It's working now, but not sure if am I doing right.

**Comment by Sdlion** [comment]
Same error, it happened after I upgraded flutter, dart, gradle and libraries preparing to the 32/64bit app bundle migration

**Comment by mitchar** [comment]
I'm having the same issue.

**Comment by Sdlion** [comment]
Still happens on 3.2.1+1
Works with @danielwii changes (gradle version changes are note needed)

> [✓] Flutter (Channel master, v1.7.12-pre.48, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.12-pre.48 at /media/Archivos/SDKs/flutter
    • Framework revision 1a374d820d (25 hours ago), 2019-07-01 16:17:11 -0700
    • Engine revision 45b66b722e
    • Dart version 2.4.0

 

> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /media/Archivos/SDKs/android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /media/Archivos/SDKs/android_sdk
    • Java binary at: /home/ppc/Programas/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.


> [✓] Chrome - develop for the web
    • Chrome at google-chrome


> [✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1


> [✓] Android Studio (version 3.4)
    • Android Studio at /home/ppc/Programas/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)


> [✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 4.3.1 (API 18) (emulator)
    • Linux                     • Linux         • linux-x64      • Linux
    • Chrome                    • chrome        • web-javascript • 


> • No issues found!

**Comment by jjchiw** [comment]
This is the problem


```
E/dalvikvm(15780): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createKeys
W/dalvikvm(15780): VFY: unable to resolve new-instance 423 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;
D/dalvikvm(15780): VFY: replacing opcode 0x22 at 0x0064
W/dalvikvm(15780): VFY: unable to resolve exception class 425 (Landroid/security/keystore/StrongBoxUnavailableException;)
W/dalvikvm(15780): VFY: unable to find exception handler at addr 0xd1
W/dalvikvm(15780): VFY:  rejected Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;.createKeys (Landroid/content/Context;)V
W/dalvikvm(15780): VFY:  rejecting opcode 0x0d at 0x00d1
W/dalvikvm(15780): VFY:  rejected Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;.createKeys (Landroid/content/Context;)V
W/dalvikvm(15780): Verifier rejected class Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;
D/AndroidRuntime(15780): Shutting down VM
```

`android.security.keystore.KeyGenParameterSpec` started from in API 23 and we are targeting `minsdk 18`

**Comment by rwrz** [comment]
Isn't @danielwii  a good solution? since strongbox has issues with the device version... so, just use an older algorithm in that case...

**Comment by yaymalaga** [comment]
@mogol is this library still supported? I think this is a necessary issue to fix, as the plugin is advertised as working with minsdk 18. Isn't @danielwii change good enough or is there any other motive to not close the issue?

**Comment by mogol** [comment]
@yaymalaga yes, it’s supported. No worries 
I will check when I have time.

**Comment by yaymalaga** [comment]
Thanks for your effort!

**Comment by manuelgomes2** [comment]
The problem persists, the really odd thing is, if i run the app using a release build (flutter run --release) the problem disappears(!). Same thing if i build the aab, publish to the play store as beta - runs ok. Only fails if i run in debug mode, from the command line or from inside android studio. Why?

**Comment by jonataslaw** [comment]
The problem still persists

**Comment by wesleyguirra** [comment]
same error here using android emulator with android 4.4.2 API 19

**Comment by dreampowder** [comment]
i have the same error on Samsung SM-T800 Tablet with 4.4.2 too.

**Comment by sydneyagcaoili** [comment]
Same error here using Jellybean emulator

**Comment by rdev-software** [comment]
Any update ?

**Comment by NeroSong** [comment]
> @DangLin012 I have make a change like [this](https://github.com/danielwii/flutter_secure_storage/commit/97bcdc729bfe27c892d2d7c705f021b2b6f5736e). It's working now, but not sure if am I doing right.

It works on Android 4.4.2, thx @danielwii  😁

**Comment by walidbagh** [comment]
Can this be fixed and released soon ? Thank you for your efforts.

**Comment by brunovsiqueira** [comment]
Any updates on this?

**Comment by RicardoRB** [comment]
Same problem here with Android 4.4.2

**Comment by juliansteenbakker** [comment]
Right now there already is a check on the SDK version like so:
```dart
           if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
                spec = makeAlgorithmParameterSpecLegacy(context, start, end);
            } else {
                KeyGenParameterSpec.Builder builder = new KeyGenParameterSpec.Builder(KEY_ALIAS, KeyProperties.PURPOSE_DECRYPT | KeyProperties.PURPOSE_ENCRYPT)

```

I do still get a warning in the console, however this doesn't seem to cause any issues running the application.
```dart
W/dalvikvm: VFY: unable to resolve new-instance 259 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;
D/dalvikvm: VFY: replacing opcode 0x22 at 0x002a
    DexOpt: unable to opt direct call 0x0449 at 0x2f in Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;.createKeys
```

Please report if you are still having issues. I'm closing this for now.
