### ISSUE TITLE
read not working when Migrate a Windows project to set version information

### ISSUE THREAD

**Issue by cwangfr** [mogol/flutter_secure_storage#521]
when i follow this doc migrate windows project, delete CMakeLists.txt and Runner.rc, and create use 'flutter create', i can't read anything from file, and nothing exception throw. i change it back, everything is back.
i use this doc:
https://docs.flutter.dev/development/platform-integration/windows/version-migration

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
