### ISSUE TITLE
Custom AES encryption key

### ISSUE THREAD

**Issue by subzero911** [mogol/flutter_secure_storage#522]
Is it possible to encrypt values with the custom AES key?
I was wondering why it is encrypted "by itself" and does not require the user to enter some secret key. So I examined the source https://github.com/mogol/flutter_secure_storage/blob/develop/flutter_secure_storage/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/StorageCipher18Implementation.java

...and found this 😱
<img width="588" alt="image" src="https://user-images.githubusercontent.com/12999702/218679647-8edf1955-488a-4a30-a7b5-7076c424d53f.png">
Then it's used to encrypt values:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/12999702/218680820-50036589-89f9-4a40-b3aa-6f85af86797a.png">

Looks like it is always encrypted with the same hardcoded key, moreover, which is publicly accessible! Seems not secure at all.

**Comment by marcotrumpet** [comment]
@subzero911 do you receive an answer to this? @mogol can you give some clarification?

**Comment by subzero911** [comment]
No, I didn't but it looks like a legacy code.
I hadn't found that it is used anywhere.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by Maf-Dy** [comment]
Isn't storing the encryption key in the sharedpreference named "FlutterSecureKeyStorage" to be accessible using this PreferencesKey is not secure at all and can be considered a strong security issue for this package ? what could be implemented / changed to resolve this if i am correct ? using keystore or something else entirely ?

**Comment by Maf-Dy** [comment]
As per my understanding
an AES key is being generated then encrypted using RSA from the keystore ( Public/Private key )
then stored inside the FlutterSecureKeyStorage shared pref

the AES preference key you are describing is base64 and can be decoded to
"This is the key for a secure storage AES Key\n"

Not sure though if EncryptedSharedPref is enabled then will this be used or not

**Comment by arbyazra123** [comment]
Is that hardcoded getAESPreferencesKey() may be harmful?

**Comment by Den-creator** [comment]
Was **preferencesKeyPrefix** implemented for solving above described issue ???

**Comment by juliansteenbakker** [comment]
The fix for this issue will be discussed in #769
