### ISSUE TITLE
Path to secure storage for Windows Desktop 

### ISSUE THREAD

**Issue by DKAC** [mogol/flutter_secure_storage#523]
Hi everyone,

I am wondering, where to find the secure storage file location for a Windows Desktop app. I would have expected omething like %appdata%/<applicationId>, but I can't find it anywhere. Any information on that would greatly appreciated. (The storage does work. I can read and write from and to the storage.)

Regards

**Comment by cwangfr** [comment]
On my windows the file store in :
C:\Users\username\AppData\Roaming\companyname\appname\

**Comment by DKAC** [comment]
Thanks for the quick answer. That is strange... in that folder, I can only see the share_preferences.json, but no other file. May I ask what the name of your secure storage file does look like?

**Comment by DKAC** [comment]
> On my windows the file store in : C:\Users\username\AppData\Roaming\companyname\appname\

Thanks for the quick answer. That is strange... in that folder, I can only see the share_preferences.json, but no other file. May I ask what the name of your secure storage file does look like?

**Comment by cwangfr** [comment]
it looks like appname_VGhpcyBpcyB0aGUgcHJlZml4IGZv_xxxxxxxx.secure

**Comment by Mino5531** [comment]
Hi, just gonna add some info that might or might not help :)
>On my windows the file store in :
C:\Users\username\AppData\Roaming\companyname\appname\

That is correct by default all encrypted files are written to that folder. Note that you can (and probably should) change the values for `companyname` and `appname` in your Runner.rc file. 
It is important however to note that this does not apply for packaged desktop apps (e.g. msix installed, UWP). In that case files written by the applicatation to that folder are rerouted to another folder and combined at runtime with the files that are actually present in that directory. You can read more about that [here](https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes).

>it looks like appname_VGhpcyBpcyB0aGUgcHJlZml4IGZv_xxxxxxxx.secure

Note that this `appname` is not defined by the Runner.rc file but by the name of your flutter project. The xxx are the key that you define/use in flutter/dart
So
```dart
_storage.write(key:"test",value:"myval");
```
will result in the filename: `appname_VGhpcyBpcyB0aGUgcHJlZml4IGZv_test.secure`

Hope that helps.

**Comment by Mino5531** [comment]
Hi,
file support for windows has been added in the latest version of flutter_secure_storage (8.0.0). 
Any earlier versions do **not** use encrypted files to store data but rather the windows credential system.

**Comment by DKAC** [comment]
Hi, with your help, I found it in the windows credentials. Thank you so much! Never would have found it myself...
