### ISSUE TITLE
Questions about IOSOptions accessibility - How to access enum

### ISSUE THREAD

**Issue by arualana** [mogol/flutter_secure_storage#525]
I read the following in the docs:

> final options = IOSOptions(accessibility: IOSAccessibility.first_unlock);
> await storage.write(key: key, value: value, iOptions: options);

I am importing  `'package:flutter_secure_storage/flutter_secure_storage.dart';` but IOSAccessibility is not found in this import. How do I access this enum?

**Comment by arualana** [comment]
@loonix @mogol ?

**Comment by loonix** [comment]
KeychainAccessibility.first_unlock

**Comment by arualana** [comment]
Yeah, thanks

**Comment by loonix** [comment]
Just out of curiosity how did you know my username? Was it from another post?

**Comment by neiljaywarner** [comment]
@loonix @arualana Did you end up with some samples or any concern about the deprecated ones? first_unlock still excludes an important scenario, but always is deprecated.
