### ISSUE TITLE
Flutter secure storage in Linux

### ISSUE THREAD

**Issue by soumyaDghosh** [mogol/flutter_secure_storage#528]
What should I use as a runtime dependency, `libsecret-1-dev` or `libsecret-1-0`, as the readme practically contradicts itself.

**Comment by spinus** [comment]
libsecret-1-dev as build dependency, libsecret-1-0 as runtime

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
