### ISSUE TITLE
[web] getting null data after refresh app

### ISSUE THREAD

**Issue by rajeshbdabhi** [mogol/flutter_secure_storage#531]
I have hosted web app using nginx. and when I try to refresh app I am getting all stored data as null. but in debug mode it is working fine and with localhost also it is working fine. I have build web app using "flutter build web --web-renderer html --release" this command.

NoSuchMethodError: method not found: 'generatedKey' on null.

this exception showing when I add try catch block.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by worldwidee** [comment]
Same here, it's not working on web when i deploy my build folder :(

**Comment by rackberg** [comment]
I' am expecting exactly the same issue :-(

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
