### ISSUE TITLE
How to store different different data types

### ISSUE THREAD

**Issue by mahammad-webelight** [mogol/flutter_secure_storage#535]
**How to store different types of data in flutter secure storage**

How can I store different data types like int, double, bool, etc.?

**Comment by HankG** [comment]
I do it by serializing everything to a JSON string and then deserializing it to read it back.

**Comment by mahammadalidodiya121** [comment]
@HankG Can you please share an example here? or do we have any other way except serialising?

**Comment by HankG** [comment]
These are really just writing to string key/value stores on the OS's. So everything has to be a string. So I just treat it like writing/reading JSON data from an API service where one implements fromJson/toJson methods. Then you get something like in this code snippet for storing and later retrieving a list of Profile objects that implement standard toJson and fromJson methods would be:

```dart
const key = 'profiles_key'
final secureStorage = const FlutterSecureStorage();

// writing
final json = profiles
    .map((p) => p.toJson())
    .toList();
final jsonString = jsonEncode(json);
await secureStorage.write(key: key, value: jsonString);



// reading
final jsonString = await secureStorage.read(key: key);
if (jsonString == null || jsonString.isEmpty) {
    return;
}
final profiles = (jsonDecode(jsonString) as List<dynamic>)
    .map((json) => Profile.fromJson(json))
    .toList();
```

This is about as complicated as it can get. If you are trying to just write simple values you can do the same thing but with just serializing the values to strings and parsing them from strings like:

```dart
// writing
final x = 10;
await secureStorage.write(key: key, value: '$x');

// reading
final valueString = await secureStorage.read(key: key);
final value = int.parse(valueString);
```

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
