### ISSUE TITLE
Linux libsecret error

### ISSUE THREAD

**Issue by atreidessoft** [mogol/flutter_secure_storage#545]
My libsecret linux package version  -> libsecret-1-0 vers 0.20.4-2 

flutter_secure_storage versions greater than 4.2.1 give errors like these when try to run:

libsecret_error: !\xc3\xc1\xf4\u0007
libsecret_error: \xa7h\xf9\xf7\u0007
libsecret_error: \u0010\xc0\x89\xf6\u0007

Is there any version of the linux library that is compatible with the latest flutter_secure_storage  versions?

**Comment by walsha2** [comment]
Are you running from a Windows Linux (WSL) environment?

**Comment by walsha2** [comment]
@atreidessoft can you try to install `gnome-keyring`. Does that resolve your issue?

```
sudo apt-get install -y gnome-keyring
```

**Comment by spinus** [comment]
I have this issue as well.
I use keepassxc 2.7.1 as secret store provider and libsecret-1 0.20.5

**Comment by spinus** [comment]
@atreidessoft is the 4.2.1 version where you identified the change? seems like worth running a diff and see what has changed in C extension module

**Comment by spinus** [comment]
checked and seem to be no work on the C files so sounds like that implementation worked with older version of libsecret-1 and at some point interface has changed.
Seems like from some version (probably 0.18?) interface has changed from supporting gnome keyring to generic secret service API. So potentially some suggestions in other tickets to use gnome-keyring here and not generic secret service are more accurate but that would need testing if that works with newer versions of gnome keyring as well (to see if gnome keyring still supports older protocol). 

I wonder if changes to the code should support both cases or we should migrate to new (potentially breaking old versions). I'm happy to help if somebody has an idea (I didn't work with this lib before so don't have strong preference).

**Comment by abroekhuis** [comment]
Hello, I am running into a similar issue, and wondering if something has been doen wrt this issue.

I am running a flutter app under Linux, and the libsecret version is 0.20.5-3. At start I see similar warnings as above.
On a rare occasion I do not see the warnings and the actual gnome-keyring login is shown, but I found no way to reproduce this whatsoever.

Having said that, I would not mind a more simpler solution, which does not need gnome-keyring at all. However, using https://github.com/yousefvand/secret-service does give the same problems.

Is there a fix/workaround that I could try?

Thanks!

**Comment by KRTirtho** [comment]
Facing the similar issue. But unfortunately, it happened on production in my case (my fault. I didn't test well)

> I wonder if changes to the code should support both cases or we should migrate to new (potentially breaking old versions).

Maybe for now, support both. In future, when the old interface becomes obsolete, it can be removed

**Comment by pintarj** [comment]
I had a similar problem. I have `flutter` installed via _snap_. I solved running:
```
sudo apt reinstall snapd
```
IDK what's happening 🤷

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
