### ISSUE TITLE
How do you write a unit test for a Flutter/Dart class that uses FlutterSecureStorage?

### ISSUE THREAD

**Issue by ToddManUtah** [mogol/flutter_secure_storage#546]
I've tried a couple of things but it crashes every time. I had a similar problem with SharedPreferences and had to run this command to get my tests to run: 

    SharedPreferences.setMockInitialValues({});

Is there a similar option for FlutterSecureStorage?

**Comment by morrowyn** [comment]
You might want to look into [Mocktail](https://pub.dev/packages/mocktail). You can write stuff like:
`class MockSecureStorage extends Mock implements FlutterSecureStorage {}` and use it like so for instance: 
`when(() => mockSecureStorage.containsKey(key: 'myKey').thenAnswer((_) async => myReturnValue);`

**Comment by codelovercc** [comment]
Use `FlutterSecureStorage.setMockInitialValues` instead mock it.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
