### ISSUE TITLE
Windows Secure Storage Details

### ISSUE THREAD

**Issue by dlewis2017** [mogol/flutter_secure_storage#550]
Where exactly is data stored in windows? Looking through the code I couldn't seem to find the resource that makes calls to the OS to store/retrieve data. Thanks

**Comment by Mino5531** [comment]
Hi,
depending on the version that you are using the data is either stored in `/Users/<Username>/AppData/Roaming/<CompanyName>/<ProductName>/` or in the [windows credential system](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0).
You can find the values for <CompanyName> and <ProductName> in your Runner.rc file

Hope that helps.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
