### ISSUE TITLE
Android native plugin doesn't support AGP 8.0

### ISSUE THREAD

**Issue by ahmedhnewa** [mogol/flutter_secure_storage#559]
The native Android plugin of this package doesn't support Android gradle Plugin 8.0, in 8.0 the package name of a library or application should be defined in build.gradle in the app module in the android block as a namespace instead of specifying it in the package attribute in AndroidManifest.xml, however, that might break compatibility with gradle versions older than 7.0, but gradle 8.0 will be required sooner or later, I think all the packages that have native plugin should update android gradle plugin to 8.0 so people start to migrate their build system to 8.0 to significantly improve the build system of android and how the app is packaged, All applications and libraries that use plugin have gradle version less than 8.0 can't migrate unless they update it manually but that is not a good solution since after any upgrade or clean the changes will reverted back

Also see [https://github.com/mogol/flutter_secure_storage/issues/557](https://github.com/mogol/flutter_secure_storage/issues/557)

[Fore more information](https://developer.android.com/build/publish-library/prep-lib-release#choose-namespace)

**Comment by chenenyu** [comment]
@juliansteenbakker The issue has been fixed, why not release a new version to pub ?

**Comment by sbatezat** [comment]
@juliansteenbakker All my plugins are compatible with AGP 8.0 except yours, is there a reason to not release this fix?
