### ISSUE TITLE
Hardcoded encryption keys can jeopardize secure data storage and transmission within the mobile application by allowing an attacker to decrypt any potentially sensitive information.

### ISSUE THREAD

**Issue by ChanakaWeerasinghe** [mogol/flutter_secure_storage#561]
We have done some VAPT scans and below issue we have identified. Could you please help us to resolve this issue.

Hardcoded encryption keys can jeopardize secure data storage and transmission within the mobile application by allowing an attacker to decrypt any potentially sensitive information.

<img width="941" alt="Screenshot 2023-05-02 at 4 54 15 PM" src="https://user-images.githubusercontent.com/20734864/235624634-179701cf-e3d9-421d-ba4b-10fbec0a1033.png">

**Comment by juliansteenbakker** [comment]
The fix of this issue will be discussed in #769
