### ISSUE TITLE
High attention point related to "Padding Oracle", reported by MobSF, when using encryption mode, "AES/CBC/PKCS7Padding", in class "StorageCipher18Implementation.java". 

### ISSUE THREAD

**Issue by kaganzdmr58** [mogol/flutter_secure_storage#562]
When I analyzed the project with mobsf, it said that it found a high priority error. When I followed the error, I discovered that an old method was used in the library, can you help me to fix the error?

const AndroidOptions(
        encryptedSharedPreferences: true,
      storageCipherAlgorithm: StorageCipherAlgorithm.AES_GCM_NoPadding
      );

I tried this but my problem still persists, i get this error from MobSf "The App uses the encryption mode CBC with PKCS5/PKCS7 padding. This configuration is vulnerable to padding oracle attacks."

**Comment by nhan7777** [comment]
I have the same issue when scan app via Qualys

**Comment by abirajabi** [comment]
I'm also having this issue. Is there any workaround for this problem?

**Comment by ernestomar** [comment]
Possible duplicate of #526?

**Comment by juliansteenbakker** [comment]
The fix of this issue will be discussed in #769
