### ISSUE TITLE
Delete fails on Flutter web

### ISSUE THREAD

**Issue by eirikskogoy** [mogol/flutter_secure_storage#563]
I do delete, close the app, open the app, and the value is back again when I read it

I do the following

main() {

  await secureStorage.delete(key: 'aKey');
  value = await secureStorage.read(key: 'aKey');
  print(value); // Here I get 'something', despite the read returned nothing after doing delete before closing the app

  String value = '';
  final secureStorage = FlutterSecureStorage();
  
  await secureStorage.write(key: 'aKey', value: 'something');
  value = await secureStorage.read(key: 'aKey');
  print(value); // Here I get 'something' as expected
  
  await secureStorage.delete(key: 'aKey');
  value = await secureStorage.read(key: 'aKey');
  print(value); // Here I get '' as expected

}

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
