### ISSUE TITLE
[Android] Bad Padding

### ISSUE THREAD

**Issue by Mino5531** [mogol/flutter_secure_storage#569]
I'm getting the following error on some (very rare) android devices: 
```
PlatformException (Exception encountered, read, 
javax.crypto.BadPaddingException:error:le000065:Cipher functions:OPEN
SSL internal:BAD DECRYPT at com.android.org.conscrypt.Native
Crypto.EVP_CipherFinal_ex(Native
Method)
at com.android.org.conscrypt.Opens SLEvpCipher.doFinalinternal(OpenSSL
EvpCipher.java:152)
at com.android.org.conscrypt.Opens SLCipher.engineDoFinal(OpenSSLCiph er.java:374)
at javax.crypto.Cipher.doFinal(Cipher java:2056)
at z5.h.b(Unknown Source:35)
at 5.a.c(Unknown Source:11)
at v5.a.k(Unknown Source:17)
at y5.e$b.run(Unknown Source:233) at android.os.Handler.handleCallbac
k(Handler.java:942)
at android.os.Handler.dispatchMessa ge (Handler.java:99)
at android.os.Looper.loopOnce (Loop er.java:226)
at android.os.Looper.loop (Looper.jav a:313)
at android.os.HandlerThread.run(Han dierThreadiava:67)
‚null)
```

has someone encountered this error before?

**Comment by gjsomerville** [comment]
I also get the same issue, as you say it only seems to happen on some android devices. Very tricky to debug.

**Comment by mlph-jandag** [comment]
Also encountering this issue, does anyone have a fix for this?

**Comment by fruts** [comment]
have the same issue, samsung a52

**Comment by Mino5531** [comment]
So, what I've tried is using the encrypted shared storage flag, however since I don't actually have a device that is affected by this bug, so the only thing I was able to do was push it onto our beta testing branch. So far I have not heard back from any of our users... maybe one of you guys can test my hypothesis?

**Comment by mozochek** [comment]
@Mino5531 
We encountered this issue on some devices with Android 13+ versions with enabled `android:allowBackup=true` and `encryptedSharedPreferences: true`. This problem occurs after app full reinstallation, when backup already stored in Google Drive(or device, idk) and is used when app started. 

Possible steps to reproduce:
1. Install the app and write some data to storage with `android:allowBackup=true`(which is by default) and `encryptedSharedPreferences: true`
2. Delete the app
3. Install the app and try to read written data

It may be significant that this problem occurs(in our case) only in release builds.

**Comment by fruts** [comment]
> @Mino5531 We encountered this issue on some devices with Android 13+ versions with enabled `android:allowBackup=true` and `encryptedSharedPreferences: true`. This problem occurs after app full reinstallation, when backup already stored in Google Drive(or device, idk) and is used when app started.
> 
> Possible steps to reproduce:
> 
> 1. Install the app and write some data to storage with `android:allowBackup=true`(which is by default) and `encryptedSharedPreferences: true`
> 2. Delete the app
> 3. Install the app and try to read written data
> 
> It may be significant that this problem occurs(in our case) only in release builds.

encryptedSharedPreferences worked for me, thx

**Comment by Mino5531** [comment]
Looks like this issue is actually resolved!
Thanks for all the help guys
