### ISSUE TITLE
when using a IP address without domain name, the following error occurs on WEB

### ISSUE THREAD

**Issue by ckdgus08** [mogol/flutter_secure_storage#577]
When accessing http://localhost:3000, https://my.custom.domain the operation works fine. 

However, when accessing http://192.168.0.5:3000, http://my.public.ip the following error occurs. I see. The IP address 192.168.0.5 is a private IP address.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'generateKey')
    at _getEncryptionKey (flutter_secure_storage_web.dart:110:16)
    at _getEncryptionKey.next (<anonymous>)
    
  It is suspected that there is an issue with fetching the dependency for crypto.
  
<img width="1472" alt="image" src="https://github.com/mogol/flutter_secure_storage/assets/122216336/1775c3da-0e98-4634-aa19-3242e26f22f3">

```
static FlutterSecureStorage secureStorage = const FlutterSecureStorage(
    aOptions: AndroidOptions(
      encryptedSharedPreferences: true,
    ),
  );
  
secureStorage.write(key: cachedRefreshTokenKey, value: refreshToken);
```

**Comment by ckdgus08** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.1 22C65 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by linchen2chris** [comment]
hi, @ckdgus08  I met the same issue, may I know have you solve it and how you bypass it?
