### ISSUE TITLE
PKCS5 and PKCS7 are known to be vulnerable to oracle padding attacks

### ISSUE THREAD

**Issue by eikebartels** [mogol/flutter_secure_storage#584]
This package seems to use AES-CBC-PKCS7 encryption for secure storage.

PKCS5 and PKCS7 are known to be vulnerable to oracle padding attacks in combination with CBC mode of operation. The issue occurs if an app reports failed encryption.  By that, the plaintext can be restored piece by piece, as only byte-sized blocks are brute-forced.

Flutter seems to expose the EncrypredSharedPreferences of Android. They are the go-to solution. See https://pub.dev/packages/flutter_secure_storage and https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences

**Comment by mkhtradm01** [comment]
> This package seems to use AES-CBC-PKCS7 encryption for secure storage.
> 
> PKCS5 and PKCS7 are known to be vulnerable to oracle padding attacks in combination with CBC mode of operation. The issue occurs if an app reports failed encryption. By that, the plaintext can be restored piece by piece, as only byte-sized blocks are brute-forced.
> 
> Flutter seems to expose the EncrypredSharedPreferences of Android. They are the go-to solution. See https://pub.dev/packages/flutter_secure_storage and https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences

So this happens on Android as android is using `EncrypredSharedPreferences`

**Comment by ernestomar** [comment]
Possible duplicate of #526?

**Comment by juliansteenbakker** [comment]
Please read #769 for an upcoming fix for this issue.
