### ISSUE TITLE
iOS app crash while read

### ISSUE THREAD

**Issue by jiangzhiguo1992** [mogol/flutter_secure_storage#585]
When restarting the app, ios crashed.
Discovery is triggered when read() is executed.
Positioning is a problem in SecItemCopyMatching().

`let status = SecItemCopyMatching(keychainQuery as CFDictionary, &ref)`

so how do i fix it？

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
