### ISSUE TITLE
[bug] [macOS]: Asks for confidential information stored in keychain multiple times even after pressing "Always Allow"

### ISSUE THREAD

**Issue by KristijanMitrik** [mogol/flutter_secure_storage#586]

**Comment by bvoq** [comment]
This is pretty annoying, to the point where we have to combine all secure information into one key and read/write it only once.

**Comment by KristijanMitrik** [comment]
@bvoq Do you know what might be the problem?

**Comment by bvoq** [comment]
Yes, you need to use only one key.

**Comment by bvoq** [comment]
And use the following options when initialising your keychain:
```
const MacOsOptions kFlutterSecureStorageMacOSOptions = MacOsOptions(
  accessibility: KeychainAccessibility.unlocked_this_device,
  groupId: null,
  // Note: This needs to be true in order for macOS to only write to the Local Items (or Cloud Items) keychain.
  synchronizable: true,
);
```

**Comment by bvoq** [comment]
You can debug your application by opening keychain and looking for flutter_secure_storage:
<img width="989" alt="image" src="https://github.com/mogol/flutter_secure_storage/assets/3169217/ee5b8e99-6e80-458c-aac6-c6b1200ccb61">
