### ISSUE TITLE
What are the  key and value

### ISSUE THREAD

**Issue by tpatikirikorala** [mogol/flutter_secure_storage#59]
This is a question, not a bug report. 

1. What are key and value you refer to in the documentation? is key the alias in the case of Android or is it just an id for a value I need to be stored in the storage.

2. say I need a small JSON string to be stored securely. Is this the correct method for it.

await storage.write(key: 'my_json_key', value: jsonString);
String jsonString = await storage.read(key: my_json_key',);

Does this mean, real encryption/decryption key management is done behind the scenes for both platforms? In the case of Android where do you store value data?

**Comment by mogol** [comment]
Hi @tpatikirikorala 
1. Key - id for a value
2. Yes, it can be done this way.
3. Yes, the data is stored in [SharedPreferences](https://github.com/mogol/flutter_secure_storage/blob/develop/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java#L126)
