### ISSUE TITLE
can't disable data restore from icloud / keychain on iOS

### ISSUE THREAD

**Issue by Maf-Dy** [mogol/flutter_secure_storage#591]
i want to disable getting flutter_secure_storage data from any type of backup when the app is removed
also disable saving data to keychain and make it syncronizable with icloud backup

please help, i set the kSecAttrSynchronizable to false but still there's data to be backed up
and on app run the data is restored even icloud data is removed and backup is disabled 

i know it's not directly related to the package usage but setting synchronizable in iosoptions didn't help in my case

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
