### ISSUE TITLE
[iOS] Map correctly the Keychain Attributes for Passwords

### ISSUE THREAD

**Issue by feinstein** [mogol/flutter_secure_storage#593]
Hi, I am not an iOS developer, but I was reading the Keychain docs [here](https://developer.apple.com/documentation/security/keychain_services/keychain_items/item_attribute_keys_and_values) and looking at the source code of the lib, and I think there's a bug in it.

Keychain defines these attributes for passwords:

> [Password Attribute Keys](https://developer.apple.com/documentation/security/keychain_services/keychain_items/item_attribute_keys_and_values#2882540)
[let kSecAttrAccount: CFString](https://developer.apple.com/documentation/security/ksecattraccount)
A key whose value is a string indicating the item's account name.
[let kSecAttrService: CFString](https://developer.apple.com/documentation/security/ksecattrservice)
A key whose value is a string indicating the item's service.
[let kSecAttrGeneric: CFString](https://developer.apple.com/documentation/security/ksecattrgeneric)
A key whose value indicates the item's user-defined attributes.
[let kSecAttrSecurityDomain: CFString](https://developer.apple.com/documentation/security/ksecattrsecuritydomain)
A key whose value is a string indicating the item's security domain.
[let kSecAttrServer: CFString](https://developer.apple.com/documentation/security/ksecattrserver)
A key whose value is a string indicating the item's server.
[let kSecAttrProtocol: CFString](https://developer.apple.com/documentation/security/ksecattrprotocol)
A key whose value indicates the item's protocol.
[let kSecAttrAuthenticationType: CFString](https://developer.apple.com/documentation/security/ksecattrauthenticationtype)
A key whose value indicates the item's authentication scheme.
[let kSecAttrPort: CFString](https://developer.apple.com/documentation/security/ksecattrport)
A key whose value indicates the item's port.
[let kSecAttrPath: CFString](https://developer.apple.com/documentation/security/ksecattrpath)
A key whose value is a string indicating the item's path attribute.

For iOS apps I think only the `kSecAttrService` and `kSecAttrAccount` are used.

Currently the lib has a [variable](https://github.com/mogol/flutter_secure_storage/blob/abb0b8d243b026b96fd7b5c3c1f29b452a8188a7/flutter_secure_storage/ios/Classes/FlutterSecureStorage.swift#L24) called `accountName` that maps to `kSecAttrService`. I would like to have the opinion of an iOS developer experienced with Keychain, but IMHO I think it's wrong, as there's an attribute just for account names. The lib should change it's variable mappings:

 - `kSecAttrService` should map to a new parameter named `service`, and `accountName` should be deprecated, and later removed.
 - `kSecAttrAccount` shoud map to `account`. This ensures compatibility is not broken between versions.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by absar** [comment]
It still exists in the latest version, the issue should be reopened.
However nothing should be done for the second point, since `key` is mapped to `kSecAttrAccount` which is correct, and it is platform agnostic:
>`kSecAttrAccount` shoud map to account. This ensures compatibility is not broken between versions
