### ISSUE TITLE
Keychain data on iOS gets deleted after some time

### ISSUE THREAD

**Issue by ilyosbekkk** [mogol/flutter_secure_storage#595]
Hi, thank you for that amazing package! I am having a strange issue in my app, I store all tokens in secure storage in my Flutter app and it's working perfectly for most  of the users but one of my users didn't use the app actively for weeks (or even a month) and app was either in background or terminated state. Today he opened the app and noticed that all requests to the server didn't work.  We found out that when we try to get the token from secure storage it returns `null`.  What might be the reason for this? Does the iOS delete the data from Keychain if it's not active for some time? Thank you for that answer in advance:)

**Comment by Fellerson** [comment]
Hello
Any update about this issue ? We have the same problem by us. Does somebody fixed it ? ty

**Comment by OneOFFER** [comment]
Hi 
We have the same problem. Does soomebody fixed it ?
Thank you

**Comment by Fellerson** [comment]
Hi,
It looks that nobody fixed it. We tried to reach them by mail unsuccessfully.

**Comment by KanybekMomukeyev** [comment]
Same here

**Comment by roncakjakub** [comment]
same here :)

**Comment by neiljaywarner** [comment]
see the code in develop re: cupertinoProtected data availability from above mr

**Comment by g-apparence** [comment]
Is there any fix? 
This makes the all plugin unusable in production

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by juliansteenbakker** [comment]
Some extra information for this issue, there is a known issue in version 9.1.0 which causes data to be inaccessible due to wrong read parameters. This will be fixed in the upcoming release.
