### ISSUE TITLE
Doesnt work on windows 

### ISSUE THREAD

**Issue by cyberpwnn** [mogol/flutter_secure_storage#596]
C:\Users\cyberpwn\Documents\development\workspace\Crucible\crucible\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp(6,10): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [C:\Users\cyberpwn\Documents\development\workspace\Crucible\crucible\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]

**Comment by rekire** [comment]
Did you note [this part](https://github.com/mogol/flutter_secure_storage/tree/develop#configure-windows-version) of the readme?
>**Configure Windows Version**  
>You need the C++ ATL libraries installed along with the rest of Visual Studio Build Tools. Download them from [here](https://visualstudio.microsoft.com/downloads/?q=build+tools) and make sure the C++ ATL under optional is installed as well.

**Comment by FZY456** [comment]
flutter_secure_storage: 9.0.0

Running on the desktop, an error occurred.


```
Flutter (Channel stable, 3.19.2, on Microsoft Windows [版本 10.0.19042.630], locale zh-CN)
    • Flutter version 3.19.2 on channel stable at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter/
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter/
    • Framework revision 7482962148 (6 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Connected device (3 available)
 Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19042.630]

```


```
D:\Program Files\VisualStudio\Microsoft Visual Studio\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(382,5): error MSB3491: δ�����ļ���flutter_secure_storage_windows_plugin.dir\Debug\flutter_.2DBB85DB.tlog\flutter_secure_storage_windows_plugin.lastbuildstate��д�������С�·��: flutter_secure_storage_windows_plugin.dir\Debug\flutter_.2DBB85DB.tlog\flutter_secure_storage_windows_plugin.lastbuildstate ���� OS ���·�����ơ���ȫ�޶����ļ����������� 260 ���ַ��� [D:\test\build\windows\x64\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]
Error: Build process failed.
```

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
