### ISSUE TITLE
Latest update on flutter_secure_storage_windows 2.1.0 Broke app build

### ISSUE THREAD

**Issue by RomanKapshuk** [mogol/flutter_secure_storage#599]
After the pushing of flutter_secure_storage_windows v2.1.0, the app build process has been broken.

![image](https://github.com/mogol/flutter_secure_storage/assets/16819254/03e0a01f-8acf-4e79-b646-71a055db96de)

**Comment by VB10** [comment]
Me too +1

**Comment by juliansteenbakker** [comment]
Thanks for notifying, i am looking into this.

**Comment by juliansteenbakker** [comment]
This is probably a win32 dependency issue, since the syntax changed with newer versions of win32, and this package still using v3.x of win32. I'm currently looking into upgrading the package.

**Comment by juliansteenbakker** [comment]
I have reverted the breaking changes made in the flutter_secure_storage_windows package with v2.1.1.

I will release a new major version, with the requirements for win32 ^5.0.0, which is required for the latest code changes.

**Comment by juliansteenbakker** [comment]
I've released v9.0.0 with latest code.
