### ISSUE TITLE
Reading same entries from different apps in Windows

### ISSUE THREAD

**Issue by peronohaynada** [mogol/flutter_secure_storage#605]
I'm working on my flutter app that writes and reads into the secure storage some sensitive information. Then, for the sake of testing, I've created a second app and tried successfully to read from the secret storage.

Steps to reproduce:
App A: writes sensitive information in the secure storage
App B: create an app with the same package name and Runner.rc's CompanyName, etc, as the App A, then readAll and print in console.

App B is able to read entries generated by the App A. 

Am I missing a key step in setting the windows options to help protect the Credential Manager key? Is there a guide available that I don't know of on how to use this library correctly?

**Comment by DavidIjsud** [comment]
something similar is happening to me but on apps ios , i am using flavors stag , dev and prod and every enviroments are using different bundle ids and when i build it dev, stag and prod are like sharing the same data storaged. any iidea?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
