### ISSUE TITLE
About encryption on iOS

### ISSUE THREAD

**Issue by taiseiiiii** [mogol/flutter_secure_storage#613]
Thanks for offering this convenient package.

I believe this package uses KeyChain to hold the information in iOS, but is the encryption of the information itself left to KeyChain?

What I'm asking is, does this package itself contain the logic to encrypt the information?

**Comment by kev-techi** [comment]
The iOS Keychain is a secure storage which handles this for you: https://developer.apple.com/documentation/security/keychain_services/ 

You don't need additional encryption on top of this.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
