### ISSUE TITLE
Read from keychain in iOS project

### ISSUE THREAD

**Issue by hx28939** [mogol/flutter_secure_storage#63]
Hello! I made a package with flutter and imported it into swift project.
In my swift project, I can read data stored by flutter_secure_storage in flutter part. However, in flutter package, I can't read data from swift keychain. I tried other keychain package such as flutter_keychain. I got the same result.
What's more, in flutter project, I can't use flutter_secure_storage to read data stored by flutter_keychain.
Is there any way I can do to read data stored in swift project? Thanks a lot.

**Comment by mogol** [comment]
Hi @hx28939 

I see 2 options how to read data from native swift:

*Option 1*
Hack
```swift
    import flutter_secure_storage

    let call = FlutterMethodCall(methodName: "readAll", arguments: nil)
    FlutterSecureStoragePlugin().handle(call) { (result) in
    }
```
List of method names you can find in [FlutterSecureStoragePlugin.m](https://github.com/mogol/flutter_secure_storage/blob/develop/ios/Classes/FlutterSecureStoragePlugin.m)

*Option 2*
Use keychain with the same parameters as plugin itself. Keychain config you can find in [FlutterSecureStoragePlugin.m](https://github.com/mogol/flutter_secure_storage/blob/develop/ios/Classes/FlutterSecureStoragePlugin.m)
