### ISSUE TITLE
[Web] Cannot read value of JWT token

### ISSUE THREAD

**Issue by TykanN** [mogol/flutter_secure_storage#630]
flutter_secure_storage throws Uncaught Error, reading jwt value from storage at WEB

Maybe the decyrption fails for certain characters.
But I also think "it doesn't make sense", because JWT has url-safe-BASE64 characters with .(dot) character.
it means JWT is a very common form of encoding. 

so If this pacakage has an issue with decyrpt encrypted JWT, there is a big problem with the encryption method of this package.

Does this problem only happen to me?

I keep the following conditions well.
1. https
2. call a function "read" with await keyword.

*iOS/Android works fine.
**Not all JWT tokens are having trouble reading. Some tokens are read without error.

**Comment by Artem-S1** [comment]
@TykanN The same issue. Did you fix it?

**Comment by zamirszn** [comment]
> @TykanN The same issue. Did you fix it?

I have the same question too

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
