### ISSUE TITLE
StorageCipher initialization failed

### ISSUE THREAD

**Issue by imsujan276** [mogol/flutter_secure_storage#632]
I am getting "StorageCipher initialization failed" issue when I run the app. 

Snippet:
``` dart
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

AndroidOptions _getAndroidOptions() =>
    const AndroidOptions(encryptedSharedPreferences: true);

IOSOptions _getIOSOptions() =>
    const IOSOptions(accessibility: KeychainAccessibility.first_unlock);

class SecureStorage {
  SecureStorage._();

  static final SecureStorage instance = SecureStorage._();

  final _secureStorage = FlutterSecureStorage(
    aOptions: _getAndroidOptions(),
    iOptions: _getIOSOptions(),
  );
}

```

pubspec Info:
``` dart
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter_secure_storage: ^9.0.0
```

Console Error message:

> E/SecureStorageAndroid( 6164): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.ensureInitialized(FlutterSecureStorage.java:154)
> E/SecureStorageAndroid( 6164): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.containsKey(FlutterSecureStorage.java:63)
> E/SecureStorageAndroid( 6164): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:149)
> E/SecureStorageAndroid( 6164): 	at android.os.Handler.handleCallback(Handler.java:790)
> E/SecureStorageAndroid( 6164): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/SecureStorageAndroid( 6164): 	at android.os.Looper.loop(Looper.java:164)
> E/SecureStorageAndroid( 6164): 	at android.os.HandlerThread.run(HandlerThread.java:65)
> E/SecureStorageAndroid( 6164): Caused by: android.security.KeyStoreException: Unknown error
> E/SecureStorageAndroid( 6164): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
> E/SecureStorageAndroid( 6164): 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:505)
> E/SecureStorageAndroid( 6164): 	... 15 more

Flutter Info:
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (12 days ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

**Comment by ddicko** [comment]
**Same issue (Only on Android 13)**  but work on Android 12:
StorageCipher initialization failed
![Screenshot from 2024-02-22 09-44-18](https://github.com/mogol/flutter_secure_storage/assets/27320352/77b9b790-e402-4bd9-9595-d3ae51b41af7)

Environnement:
Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (8 days ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

**Comment by remylavergne** [comment]
Same error. Someone has a solution / fix?

**Comment by ddicko** [comment]
> Same error. Someone has a solution / fix?

After testing on a new Android emulator, I no longer saw this error.
Clean your env and retry.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
