### ISSUE TITLE
[Web] TypeError: undefined is not an object (evaluating 'dart.global.crypto.subtle.generateKey')

### ISSUE THREAD

**Issue by agordeev** [mogol/flutter_secure_storage#633]
I'm trying to write a value into the storage:

```dart
await secureStorage.write(key: 'authDetails', value: jsonEncode(authDetails.toJson()));
```

and getting this error:

```dart
TypeError: undefined is not an object (evaluating 'dart.global.crypto.subtle.generateKey') 0m (dart_sdk.js, line 29145)
#0   packages/flutter_secure_storage_web/flutter_secure_storage_web.dart.js 136:59   write [0m (dart_sdk.js, line 29145)
```

flutter_secure_storage 8.1.0

Seems to happen only on mobile browsers: Safari, Chrome. iOS 17.0.3.

**Comment by msutharworkspace** [comment]
facing same issue on iOS browser.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by Aadv1k** [comment]
Am facing a very similar, issue. In this case unable to setup notifications. 
![image](https://github.com/user-attachments/assets/7604bd34-9e3c-478b-96f7-0fb91ba37e59)

**Comment by luis-cruzt** [comment]
I'm having the same issue with iOS and Safari browser, any ideas on how to fix it?

<img width="538" height="35" alt="Image" src="https://github.com/user-attachments/assets/be2c5ff4-f586-45d4-94d5-383dda51c6b3" />
