### ISSUE TITLE
Change storage path of secure storage

### ISSUE THREAD

**Issue by stan-at-work** [mogol/flutter_secure_storage#635]
It would be nice if we could choose the path where the secure storage is saved.

c:\users\USER\appdata\roaming\**com.example**\APPNAME\flutter_secure_storage.dat

I would also like to change the **com.example** to a domain.

Thx 👍

**Comment by longtimedeveloper** [comment]
I changed the name by searching for "com.example" in my Windows desktop app.  Then changed the name to what I need.

Work perfect.  Hope this helps.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
