### ISSUE TITLE
Feature request: Example to use with SQFLITE file

### ISSUE THREAD

**Issue by bremington** [mogol/flutter_secure_storage#64]
Hi, I preload an SQL database file from the root bundle and load into my app. Could you provide directions on how I would redirect this path into secure_storage? 

Here is example code of how it loads today:
var databasesPath = await getDatabasesPath();
var path = join(databasesPath, "newfile.db");
print(path);
ByteData data = await rootBundle.load(join("assets", "preload.db"));
List<int> bytes =
data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
await new File(path).writeAsBytes(bytes);

Thank you!

**Comment by mogol** [comment]
Hi @bremington 
I do not get the question, can you please elaborate?

**Comment by bremington** [comment]
Hi German,

My app is using a database file using SQFLITE. I create a db file to store 6 SQL tables, and import a pre existing db file to load from the root bundle.

I was hoping to encrypt this file with your solution. In looking at the few examples it appears this is more to secure key value pairs as opposed to a single file (i.e finance.db which is my file)?

If I can encrypt this file how would I do so:


This is my current code to create the finance.db file:

assert(version > 0, "Version number must be greater than one!");
var databasesPath = await getDatabasesPath();
var path = join(databasesPath, "finance.db");
print(path);
ByteData data = await rootBundle.load(join("assets", "seed.db"));
List<int> bytes =
data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

await new File(path).writeAsBytes(bytes);

So would I replace the databasePath above with final storage = new FlutterSecureStorage();??

I am trying to understand how to use this secure area to place my db file. Then I assume I can use my normal SQL commands to query and update the db file, which would be located in this encrypted location?

Thank you,

Brian Remington

**Comment by mogol** [comment]
The plugin supports only key-value string pairs. It doesn't support your use case. 
Please check https://pub.dev/packages/flutter_sqlcipher for encrypted SQLite

**Comment by bremington** [comment]
German, thank you.

Yes I have looked at flutter_sqlcipher, but it is only for Android, and I need a solution that also supports iOS.
