### ISSUE TITLE
[Linux] `read` returns null when keyring is unlocked for the first time after boot

### ISSUE THREAD

**Issue by KRTirtho** [mogol/flutter_secure_storage#643]
`FlutterSecureStorage.read` returns null for the first time unlocking the secret-service after system boots. 

- If the keyring is already unlocked beforehand, it works fine.
- If I manually lock the keyring and then try to read, it works fine also.

This issue is only occuring in Ubuntu-22.04 or above and Debian-12 or above based Linux distributions

Mine is Ubuntu 23.04

Source code:
https://github.com/KRTirtho/spotube/tree/cf7b849cddca3260d9c3a6a064418b0ba2d63270/lib/utils/persisted_state_notifier.dart#L60-L97

**Comment by KRTirtho** [comment]
Also, in a KDE based environment where KWallet is installed it still uses gnome-keyring instead of kwallet

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
