### ISSUE TITLE
FlutterSecureStorage values in Integration Tests

### ISSUE THREAD

**Issue by ishtiaque06** [mogol/flutter_secure_storage#65]
Hi, 

Thank you for making such a handy library! 

I was trying to check `FlutterSecureStorage` values in an integration test. However, when I imported `flutter_secure_storage` in my test file and ran the test driver, my app threw a weird error and exited immediately on startup. This was the trace output by flutter: 

```dart
file:///directory/to/flutter/packages/flutter/lib/src/services/binary_messenger.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/font_loader.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/platform_messages.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/platform_views.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/system_channels.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/system_chrome.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/system_chrome.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Brightness;
^
file:///directory/to/flutter/packages/flutter/lib/src/services/text_editing.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues, TextAffinity, TextPosition;
       ^
file:///directory/to/flutter/packages/flutter/lib/src/services/text_editing.dart:9:1: Error: Not found: 'dart:ui'
export 'dart:ui' show TextAffinity, TextPosition;
^
file:///directory/to/flutter/packages/flutter/lib/src/services/text_input.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show TextAffinity, hashValues, Offset;
       ^
Stopping application instance.
Driver tests failed: 254
```
My integration test runs otherwise. Simply adding the import statement 

```dart
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
```

causes this issue. This means that I can't get access to the store when my app is running during my integration test. I import `FlutterSecureStorage` in my app's `main` method and load the values present before returning my Home widget. 

I was wondering if anyone could shed some light on this. The stacktrace really leaves me in no man's land here.

Thanks in advance! 

Best,
Ahmed

**Comment by mogol** [comment]
Hi Ahmed,
how do you use the plugin in your tests? 

Integration tests are run in simulators/emulators/devices, so it works as normal application. 
However from test code can not use the plugin, because it's run separately from the application.

**Comment by NerditLtd** [comment]
I need to use sharedprefrences from driver test file and used MethodChannel to connect to native code like this:
```
setUpAll(() async {
      driver = await FlutterDriver.connect();
      const MethodChannel('plugins.flutter.io/shared_preferences')
          .setMockMethodCallHandler((MethodCall methodCall) async {
        if (methodCall.method == 'getAll') {
          return <String, dynamic>{}; // set initial values here if desired
        }
        return null;
      });
    });
```
but still there is same error

**Comment by mogol** [comment]
I am not quite sure, what you are trying to achieve. But 
* the plugin doesn’t use shared preference plugin and method channel. So mock should not work. 
*  should not setMockMethodCallHandler be called inside running app?
