### ISSUE TITLE
[Android] Storage does not survive device restart

### ISSUE THREAD

**Issue by Wegi** [mogol/flutter_secure_storage#653]
On some Android devices the storage is completely wiped after a restart (other data is retained).

You can test it with one of the Android Studio Emulator Images. Create a Pixel 7 with API 33 (Play Store).

After restarting the device the storage will be wiped. Other Android devices work just fine.

**Comment by kecson** [comment]
Same problem, Android device can't read the previously saved data after restarting the APP

**Comment by Yonkokilasi** [comment]
This happens also on Pixel 5 API 36 . Is there any fix for this?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
