### ISSUE TITLE
values are being shared between apps on ios.

### ISSUE THREAD

**Issue by DavidIjsud** [mogol/flutter_secure_storage#659]
On ios that are with flavors and enviroments are using differents appbundles ids , but when i create the same app using differents appbundle id's different flavors and enviroments , they are like sharing the same data, for example if i introduce a value "a" with a key "email" in my app A and then i read it from the app B then the app B can read it without any problem.

What can cause this ? all of these using the same iphone.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
