### ISSUE TITLE
Cmake Error: a required package was not found

### ISSUE THREAD

**Issue by lola-emil** [mogol/flutter_secure_storage#663]
### Error
```
CMake Error at /snap/flutter/141/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /snap/flutter/141/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/CMakeLists.txt:13 (pkg_check_modules)
```

OS: Kubuntu 22.04.3 LTS x86_64
Flutter version: Flutter 3.16.2

How to reproduce error

1. `flutter pub add flutter_secure_storage`
2.  Run the app in debug mode `flutter run -d linux`

**Comment by InesGarcia84** [comment]
It's the same problem here (found a solution) : 
https://stackoverflow.com/questions/68891798/flutter-a-required-package-was-not-found-flutter-secure-storage-linux-cmakelists
