### ISSUE TITLE
Upgrade dependency js

### ISSUE THREAD

**Issue by maxlapides** [mogol/flutter_secure_storage#670]
There's a new version of the `js` package: https://github.com/dart-lang/sdk/blob/HEAD/pkg/js/CHANGELOG.md#070

Note that there is a breaking change:
> Breaking Change: Moved annotations to single location in dart:_js_annotations. This makes it easier to avoid collisions with dart:js_interop's @\JS, as you will now see a static error instead of it resolving in favor of the package definition. However, since this may result in breakages in previously working code, this is treated as a breaking change.

**Comment by JgomesAT** [comment]
we need update js from 0.6.7 to 0.7.0,  we have incompatible problems with other libraries

**Comment by juliansteenbakker** [comment]
This is fixed in v4.0.0

**Comment by juliansteenbakker** [comment]
``

**Comment by JgomesAT** [comment]
is not deployed the version with the JS 0.0.7??
