### ISSUE TITLE
How can you delete flutter secure storage data from an iphone?

### ISSUE THREAD

**Issue by joshpetit** [mogol/flutter_secure_storage#671]
I see in #660 that the shared preferences persists after app installs and have found solutions to delete the data from within the app. Is there a way that an iphone user can delete all the secure storage data from their iphone? Without using the app, as in from their iphone settings.

**Comment by NicolasEymael** [comment]
any news on this?

**Comment by Jason-Gregoire** [comment]
Same question

**Comment by s15-coder** [comment]
I had this problem before and the workaround that I found was to use the shared_preferences library to store one single variable that tells me if it is the first time the application is opened or not. Unlike flutter_secure_storage the shared_preferences variables are removed when the app is uninstalled.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by imgurbot12** [comment]
@juliansteenbakker this is still an issue on the modern version.

As I understand it, `flutter_secure_storage` uses the ios keychain for saving data on IOS. However, according to several [open issues](https://apple.stackexchange.com/questions/332574/deleting-an-app-s-data-from-the-ios-keychain-or-resetting-the-keychain-entirely), the data is never deleted on uninstall and it's impossible for users to manually delete this data unless they factory reset their entire device.

This just bit us hard for the IOS version of our app as users are unable to manually reset the storage if the app enters an irrecoverable state. 

The workaround recommended that I've seen is to use a secondary insecure storage mechanism that is saved on-disk to check if the program is booting for the first time after install/reinstall and to delete any data in secure-storage if it is. Though this then requires a secondary storage mechanism to make use of secure-storage properly which is less than ideal.
