### ISSUE TITLE
[WEB] Alternative to the experimental implementation using WebCrypto

### ISSUE THREAD

**Issue by hbatalhaStch** [mogol/flutter_secure_storage#675]
I want to use this package in my app which is aimed at both mobile and web so the warning about the web version being experimental bothers me a little.

So since the WebCrypto implementation in this package is experimental I am wondering about this [webcrypto package](https://github.com/google/webcrypto.dart) from google.
Can it be used instead of the experimental implementation used at the moment?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
