### ISSUE TITLE
On uninstall delete keys and values from keychain, possible?

### ISSUE THREAD

**Issue by FrankSantoso** [mogol/flutter_secure_storage#68]
What the title said, is there any way to remove the saved key / value from keychain (iOS) on uninstall?

**Comment by mogol** [comment]
Hi @FrankSantoso 
The plugin doesn't provide such functionality, 
Please check [this thread ](https://forums.developer.apple.com/thread/36442) to see how it can be implemented.

**Comment by enricobenedos** [comment]
Sorry for the issue reopen. 
Can anyone please better explain the workaround for this issue? I'm not very practical with iOS.  The only things that I have understood is that after iOS 10.3 the keychain will be automatically deleted (but it seems it is not true). In my case the data persist after deleting and reinstall.
