### ISSUE TITLE
Update flutter_secure_storage_web depends on js ^0.6.3

### ISSUE THREAD

**Issue by MarceloRab** [mogol/flutter_secure_storage#683]
Firstly, thank you for your work.

I'm having difficulty importing packages due to the broken js version.

I thank the attention.

`Because socket_io_client >=3.0.0-beta.0 depends on js ^0.7.1 and every version of flutter_secure_storage_web depends on js ^0.6.3, socket_io_client >=3.0.0-beta.0 is incompatible with flutter_secure_storage_web.`

**Comment by ThexXTURBOXx** [comment]
The `js` version is not broken, it's just outdated. #680 fixes this.
Also, this issue is a duplicate of #670

**Comment by noskova** [comment]
+1

**Comment by andremobiis** [comment]
+1

**Comment by ThexXTURBOXx** [comment]
Commenting "+1" does not add anything here. If you want to stay up to date regarding this issue, subscribe to this issue instead

**Comment by vongrad** [comment]
+1

**Comment by mark8044** [comment]
@juliansteenbakker Although closed, this seems to still be an issue.  It looks like its because flutter_secure_storage 9.2.1 depends on flutter_secure_storage_web ^1.2.1 which still contains the js dependency.  Perhaps that should be updated as well

**Comment by ThexXTURBOXx** [comment]
@mark8044 This is desired behaviour. See this comment for reference: https://github.com/mogol/flutter_secure_storage/pull/698#issuecomment-2111967218
