### ISSUE TITLE
During archive process for ios the following exception occurs 

### ISSUE THREAD

**Issue by sadaqatdev** [mogol/flutter_secure_storage#684]
Unhandled exception:
Null check operator used on a null value
#0      Context.embedFlutterFrameworks (file:///Users/macbookpro/flutter/packages/flutter_tools/bin/xcode_backend.dart:235:68)
#1      Context.run (file:///Users/macbookpro/flutter/packages/flutter_tools/bin/xcode_backend.dart:59:9)
#2      main (file:///Users/macbookpro/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Command PhaseScriptExecution failed with a nonzero exit code

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1.2 23B92 darwin-x64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
