### ISSUE TITLE
 Android cryptography audit: 6 findings

### ISSUE THREAD

**Issue by skerkour** [mogol/flutter_secure_storage#69]
Hi,

I've audited this package and here is my observations about cryptography usage in Android:
* you should use 4096 bits RSA secret size
* you should use a 256 bits AES secret size
* `RSA/ECB` DOES NOT provides integrity. `RSA/OAEP` should be used instead.
* `AES/CBC/PKCS7Padding` DOES NOT provides authentication/integrity (it means an attacker could swap Keys/values, or even completely replace a value). Instead you need to encrypt the value in `AES/GCM/NoPadding` mode with the key as  Additional Authentication Data (as I do here https://gitlab.com/bloom42/libs/flutter_secure_store/blob/dev/android/src/main/kotlin/com/bloom42/flutter_secure_store/crypto/KeyStoreHelper.kt#L58)
* Keys are not encrypted. They can be encrypted using deterministic encryption to allow lookup (a same (Plaintext, Secret) will always result to the same ciphertext). See (https://github.com/google/tink/blob/master/docs/PRIMITIVES.md#deterministic-authenticated-encryption-with-associated-data). I recommend using `AES_SIV` in google Tink.
* The trick to use `RSA` to encrypt an `AES` secret is only valid for Android < 23.
For Android >= 23, `AES/GCM/NoPadding` is already available in KeyStore and thus should be used directly, without RSA.

Another option to obfuscate keys if you do not want to include Google Tink is to use a salt and Sha2-512(key + salt) and use it as shared preference's key. the salt is stored encrypted with Android Keystore.

**Comment by AfzalivE** [comment]
Should be using tink in the first place instead of manually managing keys and whatnot, because tink already has mitigation for a lot of security bugs.

**Comment by juliansteenbakker** [comment]
With #270 you can now use the following code to enable EncryptedSharedPreferences:

  AndroidOptions _getAndroidOptions() => const AndroidOptions(
        encryptedSharedPreferences: true,
      );
This method doesn't use the custom StorageCipher but rather a Jetpack Compose library that automatically encrypts the data. Please note that on API < 23 it will fall back to the 'regular' secure storage. 

I think this would fix most of the problems mentioned here.
