### ISSUE TITLE
Flutter Secure Storage is Not working on Release Mode in Android 14

### ISSUE THREAD

**Issue by Pursoth1815** [mogol/flutter_secure_storage#690]
[ActivityRecord{a1891bf u0 com.nic.InspectionAppNew/.MainActivity t2886}#209122](this:0xb4000070e6e19ba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'ActivityRecord{a1891bf u0 com.nic.InspectionAppNew/.MainActivity t2886}#209122'
2024-03-12 15:56:49.704   858-1179  BufferQueueDebug        surfaceflinger E  [9f428b6 Splash Screen com.nic.InspectionAppNew#209123](this:0xb4000070e460dba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from '9f428b6 Splash Screen com.nic.InspectionAppNew#209123'
2024-03-12 15:56:49.712   858-1179  BufferQueueDebug        surfaceflinger E  [Splash Screen com.nic.InspectionAppNew$_1786#209124](this:0xb4000070e462eba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Splash Screen com.nic.InspectionAppNew$_1786#209124'
2024-03-12 15:56:49.751   858-2038  BufferQueueDebug        surfaceflinger E  [86d4f19 ActivityRecordInputSink com.nic.InspectionAppNew/.MainActivity#209129](this:0xb4000070e3206ba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from '86d4f19 ActivityRecordInputSink com.nic.InspectionAppNew/.MainActivity#209129'
2024-03-12 15:56:49.887   858-2038  BufferQueueDebug        surfaceflinger E  [c21616d com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity#209130](this:0xb4000070e3209ba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'c21616d com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity#209130'
2024-03-12 15:56:49.907   858-2038  BufferQueueDebug        surfaceflinger E  [com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity$_6062#209131](this:0xb4000070e321bba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity$_6062#209131'
2024-03-12 15:56:49.932   858-1179  BufferQueueDebug        surfaceflinger E  [Bounds for - com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity@0#209134](this:0xb4000070e4634ba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Bounds for - com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity@0#209134'
2024-03-12 15:56:49.933   858-2858  BufferQueueDebug        surfaceflinger E  [SurfaceView[com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity]@0#209135](this:0xb4000070e6cbcba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'SurfaceView[com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity]@0#209135'
2024-03-12 15:56:49.933   858-1179  BufferQueueDebug        surfaceflinger E  [SurfaceView[com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity]@0(BLAST)#209136](this:0xb4000070e46a9ba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'SurfaceView[com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity]@0(BLAST)#209136'
2024-03-12 15:56:49.934   858-1179  BufferQueueDebug        surfaceflinger E  [Background for SurfaceView[com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity]@0#209137](this:0xb4000070e46cfba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Background for SurfaceView[com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity]@0#209137'
2024-03-12 15:56:50.030   858-2858  BufferQueueDebug        surfaceflinger E  [Surface(name=c21616d com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity)/@0xf625125 - animation-leash of starting_reveal#209138](this:0xb4000070e6cd9ba0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=c21616d com.nic.InspectionAppNew/com.nic.InspectionAppNew.MainActivity)/@0xf625125 - animation-leash of starting_reveal#209138'
2024-03-12 15:56:55.150  6062-6192  ProfileInstaller        com.nic.InspectionAppNew             D  Installing profile for

**while I try to Read the Values I am end up with this Big thing and my Apllication crashed with this error**

**Comment by fakhriyuda** [comment]
gw butuh besok

**Comment by muhammad67uzair** [comment]
any update on this? i get no exception or anything, if i try to read the values i have stored in secure storage after restarting the app, nothing shows up.

have you solved this?

**Comment by petri-lipponen-movesense** [comment]
I'm experiencing the same on Oneplus 12, Android 14 and some other phone models. If I read after write, the values show up, but fail to appear after restart of the app. Logcat does not have anything related.

**Comment by petri-lipponen-movesense** [comment]
I added a generous amount of Log.d's to the Android's "FlutterSecureStorage.java" and got the following printouts. The code calls for read("welcome") and then readAll() to enumerate storage content. The  _raw.entrySet()_ in readAll() seems to contain a lot of entries, but _keyWithPrefix_ is somehow mangled: it has wrong prefix and no "=" followed by the value. 

A functional entry looks like this: `raw.entrySet(): entry: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg_birthYear=ZP6OL5ZSrFipHMtzEoW0VuIS5DTl7rPK9x6B45d3jEM=`. 

`
D/SecureStorageAndroid(21551):  ensureOptions()
D/SecureStorageAndroid(21551): ensureInitialized()
D/SecureStorageAndroid(21551):  ensureOptions()
D/SecureStorageAndroid(21551): preferences = nonEncryptedPreferences
I/flutter (21551): FlutterSecureStorage [APP_SETTING_WELCOME]: null
D/SecureStorageAndroid(21551):  ensureOptions()
D/SecureStorageAndroid(21551): ensureInitialized()
D/SecureStorageAndroid(21551):  ensureOptions()
D/SecureStorageAndroid(21551): preferences = nonEncryptedPreferences
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBTFgRAkYi0RFQ6E+vv8X6W2W9RUXVejgwMb1fKOQbZPvn8s67Loe3eDLTyrekJisvTEO2+JIIh0zScv+H+ebDms80rLFpVVOfTM/LkRFZ2F/XRB+U5M++mHah65iQ===AX0lTB4djYdABRuXC56RC0ChQ0Z4VtVUaD8/T8prqNwr9+GOfgFXPfeb3DwZWA==
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBTFgRAkYi0RFQ6E+vv8X6W2W9RUXVejgwMb1fKOQbZPvn8s67Loe3eDLTyrekJisvTEO2+JIIh0zScv+H+ebDms80rLFpVVOfTM/LkRFZ2F/XRB+U5M++mHah65iQ==, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBQErghTngjZAFOH1eVE3C3AwLrAz1OuQqcGoPrSBXQeD5N3AF68SQHOHjNvLPCkaOtpdHmnrQClxBEHEc/ydOjRIKYtZTRtZj8HX8oG=AX0lTB5bpUDPmENjYkoZTHpHhOkzUsBPKBw313hv8OCBSDNCSLmQAnpweEC7aKFS5w3mv1DS0JZ4mC8=
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBQErghTngjZAFOH1eVE3C3AwLrAz1OuQqcGoPrSBXQeD5N3AF68SQHOHjNvLPCkaOtpdHmnrQClxBEHEc/ydOjRIKYtZTRtZj8HX8oG, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: __androidx_security_crypto_encrypted_prefs_key_keyset__=12a90176ef440c166f7660a32e8817a4cc0a85181a79c9f4f3fa4065449a1cb79c9df8ac29c9b48b03dba53d99e77c3588ac7de601865cfc3b271c0815df738312e648ccf10cae4afce1a5dfd843f1f7f48ad82a651465233db2afce897121057ad8258de3a70c8b2c4675f660cf6043fe3af8345e34773b60c971b1d7148c41f619c31fed1c8e8e0cd38d539e1cc232869d6f0d80f6427f3247d9f5243ac5dd34e49ef6e67ec69615fd8d191a440894b8e2c605123c0a30747970652e676f6f676c65617069732e636f6d2f676f6f676c652e63727970746f2e74696e6b2e4165735369764b657910011894b8e2c6052001
D/SecureStorageAndroid(21551): keyWithPrefix: __androidx_security_crypto_encrypted_prefs_key_keyset__, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBQgQrkaZr0wJBakKqR4oJvYC8PbHDDauQjcv4C18SpnI4IG0YdnGycoihaKrD4R8kFsT2JD5B+a4Aw9YqEekXNuh6Ir9u5/bk+cQjvnP+NDukdVBg===AX0lTB6b28xouce+4iMs4PLiGKQgmDdhiyv7zbWv/el67EbWZlYKsQWkZI1p8w==
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBQgQrkaZr0wJBakKqR4oJvYC8PbHDDauQjcv4C18SpnI4IG0YdnGycoihaKrD4R8kFsT2JD5B+a4Aw9YqEekXNuh6Ir9u5/bk+cQjvnP+NDukdVBg==, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBSNMssdWM2CJhby2radSjXsn0OB18h/oWevHFhxup1ol0J2NmBQQjH1TvSfDqOIlqM0Rmxj4ojKnCZQspDyJv3POajSFEjQiFWOtQ===AX0lTB7nqy4oEFFWll/i3dsim19k+nO+4I+XB0W0g/bCku1UWfUjFT9smy+w
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBSNMssdWM2CJhby2radSjXsn0OB18h/oWevHFhxup1ol0J2NmBQQjH1TvSfDqOIlqM0Rmxj4ojKnCZQspDyJv3POajSFEjQiFWOtQ==, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBRHduhYHFKZTsmi8Gr2Py8Z/mQnGWK3W20RgVX7xxO2crvn9XYPZNmkCd1Dyr6SQWoUVvArKeAKnAipGyQjyVtfwFevKKDH4hcHmYeF=AX0lTB47cW3VHGY6O2BZAzQVsIJkGqbQxULCxpe0KsF1ZQ1rXontOb43CnmXRI3HurXKKIiisEG0V5VoN6l5MZDN4IuilkrfjaxCx/VHzYI4oy79vuEIBcqa8BsoNqmRF3aGJvDyf76ciDpdDdcxvKY5BNWkYle3FmSnTEUQ9mnHV1NyVGJ06WjixobIW1JFvPcVIkIKn+gL55W1/56yzWqBarxVsVR8PatL0N8qEpKGBQjiTM3wtNgoaWSxJtogwv/89Mc74SEfozl5q/pIQDdWDhbYe8BWlmn8CLKoImqG6rCXoUWJBcSByTUs5X6bFb8ALODSqs7RyMew58SIhKRGceJNG/EhZg61M/zQqabEVgXu9T6h7+snj4sS+fDgZ8PJy96s00vOGR8Dalmzz+FOEBewOQWPvVUF3tbYBlaROsD4j9aW4/4iatSFBnv/KGoq6UQL0+vssEW0UwwllczpGtd2dCtW+f9JPIqlE0FMjLhiWQRy3XCR4O82/WQFTgn/NmHH9llH2cZ1SuCNeKewEidm9VrH6/cNA97FJfiiSZbl6CpFScfrU5LF3GH1yI+bqV4oI0pKIxIFi+Dy1XsA4z1+MgE32DjomRTQFvourObzJQEOo02w5pJUaidSOYBy6nAIsKSIf5bDZD6OqrSmjm4KVdPoodODXZVysgkF9b8ARhPwtI0Gs1KlIputtKqIVwoGsmTG95TD6Uy3YiflKwgXUfwKrRoH3v7NKz554ExLZtiJFh/pMAiQJeK4wQsgtrIv1f5oxnVoYX5x5tvwXo/+MWx5O6v2YL0gyiti7de4OowOkit8ydJAPSf1g5WReQl6wpe089qcVfqyk4CQq6SJUeKUqf9h2T9SjJPY4JIn9KnUIzlPdAohUXt3jhwF8wFi5oV+qldLZU+ef6kg/9YdvV2vgBS2ebYY/40f8o/QhK4n7M2UDlEND1FlALmF7FdaXMt3Wswfe+15ZwCQNitd7XupkIxxLN4Mmyon7UOwE0y2GTQMRJs3mScaFRTl8SSrcuer/pHt7D6HyvXYbHMZXbxs35Befduk8Ag/1nk8fJ5mDShvC2um9tKwRcS+yLM6zqJPwWRTUaurR8vZPaXtx2Nd4sszFKrIHUM56fSsu5LTWdLQdnBDTSjr2ZQeGF2oeo7MSrtl8kdOZwDB64qmAKVMQo+IcJpzoL+G77HqGRGS5ggve6rXK6bs2XGEcXpl9+RZFSHweVTX5m696RjRLILRyKfli4qF3+5rF68VUmaVSsZ7AvP2S/C7w66uVENS/cJac8Qil3YNx5YBt2bKAA1dTA1owDbAvVs8zwYthqWEvPhu3fdWz0y+eupuyR3bNgH/fYnn4T7SxeA0oi6hRU0hAeOyiIYjyxMD5oTS4IKTGAJ5cQVWG/1mVhkB3Ec/7FaR6M4u6CvMeQ/AwD9tbdgMdWAfr5EW9JhSiFm/IxK03FWgVhusDH+AxaYsV66zc5UJlHkgonC8O/QlReq6AgGXNnJlXJDbXonvTMalk0/tJAWwGB9Dd1z73IfBWs6T/ByM2+a7sHgqM4sizs8w3qGB0+BPsOCo1FDXMlbu2PyN/qDcQd59VzrrtGcHVDwGdGvsL/b5NNpnxC8iaVG38tVdY47gA0/8z8YR1sDqAvZQvAD1MWwIa2ilxMsrhclmVP0RYm5Vex+XKBIGT8OObfMWHaeul+ZxklWHa+pBpGPhr9MGCfLSXBMsss8si93wOnaAp6rEJHfRqG+1UnZgMwHKFqsNAYG4fm1fTe0eptesa7oAbV8Z3MThnPo8ahSxvqG045lIrBkp11bcP0fwCg6ITVWs+8RziAqwZ8IcrOr6mC0Xs3aYk9kukfTOQN+XQIOLgOTYxSS92wXx0PkbBPGCIahrKvnBObxjx7AHOp5/rYvlSLKWy9kZ//8H4R0ARJVnpgDTGoTVkm0DpzdD22x3JsauupyuwTXbQEVuvvS3J34J+WSadC6XuP+kS8XVdn4ZzI05Q1e3vqybbncqako8Dc+ZW2o2YntXlyyTXLJ3K6n/LQY2/jue5STPRJZuBJ7rzVcPiZkkm9XPWQA9pdB04RSytZRFxt9o7UqL0bhle1+I82Aq7hM8lglaDXDMLJFWSAmAhJ0krblQTZsz+oZzctHroTZAO9zoT5/JA5e8UgabRUfax3HvMT0YgxHD6+rpjCv8Aob1PsKxvvFxZu/Bf+j+FQ+Qq5h2y3k9gK+8JCWXClf84JGwMgdDzg4dTtnQZwD+d0W+1+cM9+l2XWO9BIm+G9lG3RmjPiQMyYmLR2rFMMcjNY49U0mvGaUtL4IdLoQcKDlPxPaWhJd73w8+9FhzMMT5f3okbWq6/tuyU0geE5msYC7qyKEp++XSuFRgeFceyNMxk7f80cOh0XZUnIoeUYIR5k3ePLuPlewEhJgBxxTsJHsJO4+TnIUGNSINCOhUH1AO9TNUkeUch4qMQFcMpR+0pG5lbCrItzD4uS1qxApS0fs3KTLcx27bYAlRSrInkz6z4igHIdQYK/1tfaMH9nIuFJYvT8mP7FZGMUwyimPcjp2ZsRjT4pUa9+j1/w1fsfXUxtjQcIZ/rGsuCBD1sb3dJnH3YZr/V49/2kchbgscTqFf4PzEPi9HR+Yn32YOlYFb6yQF6eCKKnnrfH83n1JPWnD/GshnoPXgklxRoBzkzRZjpTvXafPTmkU9UI8Q5rSRkH5rv+36pXXnuVaysjq+SXrtzcaJm9aD6hngHCZjV25J4RP2Z9NGAWZwAMHx20AVzSQJrY6mFpOlBut6wQX2rbi5yX3/+3yt0MXSVxn0SFEiEITtKL39JenOYQzpS3npfYMfFqgCnKty4C77Yhg1JiwMriKsZB7ixMYMzNi1tv4bf+s1YkJZ1viN0zSQvdgUVHotFMiYPU695xFpaIOYoc6eUdABhtU2VglYShb78ItfkVb8osxCUY6dbDqaLGMlCsuvCb6PpkHpDuEeDfQMIRwxzcb8+x0ozD66U+WAol0BIf+s7gBUhclh6GMOJsNlUeFANpe0EgRj0vuf8EfperhodtXDWqllOunkI4/aoU2ZFCjJzSq4SfEp7fugb+L7w9GVoGacdJk9s2wbNSM6GDJz94l5YUhG4gniuyzZCt5K89yz/bLaP4yMk/FaBEsmzuwwFOF/bPXKFnl496qYMtHrujUXuCg6oDiM/+xYxJMcF85lgPezflJfhBhZmxpkoH12OMKmNOdxP0Fq/HwawFbkDNCRA9O2fQxBxcKclOtvRdv3XyxXCZiigaM8NPl6GVlvGF1x/dgF5OmETOQHC9zpwKn2BGIlkE1fi+a1kJg749fW01LKQ6iag8/Fq+Yh6sg3Eyhm69bMjcJ/AwESchVR2M0CmDd0YwBE1uWTIv0ZFfBFpwgSxE+p1dGI7VcTlgTZidpbu9m1ERQEqI/ZdWJgWC7jPsAf3b1LX75jS+be7pjX+ve4VLOV3Z7YC/oYsAA/xA2URGm0P8BcKYdwadXlfIR98VM7L3TERNCfdPWNDuWQF7got1q6E/I+lW7mVWI4nITHxBxLQ3j0ezwXyEoK6C6oWa45DVwk1dd6p97bfoSwgxhPXt9eFdujRysFE5U9gZpybPaqc13/OPaecTXwRs/2qrVu2ImnRTXEweF1V5bGVQoqd7EoiQFMQKtwWGCvPaSqLWNrLtOEtzUSI97lTF5Zu8hOecQQDBvkIcKmyV9fzcmc315t2EKro8rJDTjz3YaCUEg93SBioBVy2Q1CjDxmy7/Pa6qdOlEN/MWoa9TsP1Qzvq2ZR/k6kCRU0g9Qxcv+2aro6Dpei5TK9nmT4Jot2l/Sa/HzJlLnLPPNZmpJpgpnRVsBH4ytPjD3iqMWHm2hgZlL0PbxkVFxbCIJYABGNo7l65kgx3w2HBB9zNkrGb+76
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBRHduhYHFKZTsmi8Gr2Py8Z/mQnGWK3W20RgVX7xxO2crvn9XYPZNmkCd1Dyr6SQWoUVvArKeAKnAipGyQjyVtfwFevKKDH4hcHmYeF, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBTkFER/YUQCPjKlQOoK9l3QrtsvwqSDH8gvqXDGCsT7amREQAOwvN7XlVRLRQMSWTIzVJ0GIoedFOJiASBbgYGWxJjHQq1a/VoKKRdgkSHp0teSCpgEWPk==AX0lTB75hNjE4+XihEIsqsBs9f97D80jpUOpS1iaYc/y9hxA5CpIFmCh++1AEg==
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBTkFER/YUQCPjKlQOoK9l3QrtsvwqSDH8gvqXDGCsT7amREQAOwvN7XlVRLRQMSWTIzVJ0GIoedFOJiASBbgYGWxJjHQq1a/VoKKRdgkSHp0teSCpgEWPk=, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: __androidx_security_crypto_encrypted_prefs_value_keyset__=1288014f695320bf86a954fafd5a399b1de83b0ec7fa86dd7236ab68a936328088b09655cc338e9f3436ce72dad0321c7683c01aafdc6643ec350fba5a1f14e43fcb7276a127d3d2d1d7587fd853c143cb56d40579ac34aa1e4a93d95f193922c57f111c43c1d3ab204c1665008491d99c505ca57440c1ddd5b2a3f4913262c703415d43950a2ef26ab5ed1a44089e9895e907123c0a30747970652e676f6f676c65617069732e636f6d2f676f6f676c652e63727970746f2e74696e6b2e41657347636d4b65791001189e9895e9072001
D/SecureStorageAndroid(21551): keyWithPrefix: __androidx_security_crypto_encrypted_prefs_value_keyset__, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBTwsgPpIwl4vsEbwrEvOBtIqBpWGYpM2FpeB2gz5u5mJoOp9vaHibNZ7rrGkBTCGONKZwWj73ce0xvYuQKq41emH8Ea5YTX5zt8DVPZ/p1+GQ===AX0lTB6hUQZIncKExQWRg5hXL9Z6wBXtmlUVaaaBTb5iOgacHKQ+skPt
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBTwsgPpIwl4vsEbwrEvOBtIqBpWGYpM2FpeB2gz5u5mJoOp9vaHibNZ7rrGkBTCGONKZwWj73ce0xvYuQKq41emH8Ea5YTX5zt8DVPZ/p1+GQ==, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(21551): raw.entrySet(): entry: AVjYnBQrBYndNI36Q3jrIELlXAmix2udkW3exVUEhx5Qwbdg4tG2nTApBx2nQ5FFx/jNRPC3e3tTYPYm1LG3ndR7hTpd3oX8BnaAGWc9yuaik8c==AX0lTB4ELYDN+nr9XYMd38apLAXhpHwv6qC2VaVRO9a68fSmCs2W+4FeQMnfHg==
D/SecureStorageAndroid(21551): keyWithPrefix: AVjYnBQrBYndNI36Q3jrIELlXAmix2udkW3exVUEhx5Qwbdg4tG2nTApBx2nQ5FFx/jNRPC3e3tTYPYm1LG3ndR7hTpd3oX8BnaAGWc9yuaik8c=, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(21551): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
`

After adding `editor.commit();`in the end of write() method, the read() returns correct data, but enumeration still contains also the invalid "AVjY..." entries:

`D/SecureStorageAndroid(29903): keyWithPrefix: AVjYnBQgQrkaZr0wJBakKqR4oJvYC8PbHDDauQjcv4C18SpnI4IG0YdnGycoihaKrD4R8kFsT2JD5B+a4Aw9YqEekXNuh6Ir9u5/bk+cQjvnP+NDukdVBg==, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(29903): ELSE !keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(29903): raw.entrySet(): entry: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg_welcome=twv+zrn1pRPG2zqTQ3zESNfPf3dr2tVST+3AcUfYnGM=
D/SecureStorageAndroid(29903):
D/SecureStorageAndroid(29903): keyWithPrefix: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg_welcome, ELEMENT_PREFERENCES_KEY_PREFIX: VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIHNlY3VyZSBzdG9yYWdlCg
D/SecureStorageAndroid(29903): keyWithPrefix.contains(ELEMENT_PREFERENCES_KEY_PREFIX)
D/SecureStorageAndroid(29903): decodeRawValue(): twv+zrn1pRPG2zqTQ3zESNfPf3dr2tVST+3AcUfYnGM=
D/SecureStorageAndroid(29903):
D/SecureStorageAndroid(29903): - result: false`

**Comment by petri-lipponen-movesense** [comment]
I managed to fix the issue in our app by:
- setting "encryptedSharedPreferences=true" for Android options
- making sure that I use shared instance of FlutterSecureSettings (probably was not needed)

**Comment by Pursoth1815** [comment]
Finally, I fixed it. is there any one still facing this issue ?? ping me

**Comment by rajeshzmoke** [comment]
@Pursoth1815 how did you fix it?

**Comment by lovelyelfpop** [comment]
@Pursoth1815 how did you fix it?

**Comment by lovelyelfpop** [comment]
Mine is android 12, also not working when build release.
Flutter 3.24.5
flutter_secure_storage: ^9.2.2
