### ISSUE TITLE
[iOS] Native app update

### ISSUE THREAD

**Issue by pawelballo99** [mogol/flutter_secure_storage#692]
I'm trying to get keychain data from native app after upadating it with flutter app. Flutter app has bundleID and accountName for keychain the same as native app, but `final data = await FlutterSecureStorage().readAll();` is always empty.

**Comment by SERDUN** [comment]
Hi, I have the same issue after updating the plugin from 
flutter_secure_storage: 9.0.0 
to 
flutter_secure_storage: 9.2.1


`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
`

Try calling .readAll() immediately after the WidgetsFlutterBinding.ensureInitialized(); and before runApp(...).


<img width="653" alt="Screenshot 2024-05-19 at 12 36 06" src="https://github.com/mogol/flutter_secure_storage/assets/26858237/4a088db8-44af-4c31-9b31-00a7b2d3a6e1">

**Comment by techouse** [comment]
This was fixed in #719

**Comment by sureshprokraya** [comment]
Hi, 
I am using flutter_secure_storage: 9.0.0 version in flutter application. But when ever i closed the app and reopen again , 
After splash screen  i am getting data null in IOS, but in Android works fine. 

How to fix this issue,  please any one help me on this.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
