### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by vbrandl** [mogol/flutter_secure_storage#699]
It seems like this project isn't maintained anymore. Are there alternatives or forks?

**Comment by Daniel-Cong** [comment]
It's been 7 months, and I can't update my js package to newer version because of this.

**Comment by himanshu-newstok** [comment]
@vbrandl I don't think so. There are  only 2 days remaining and they have not added the privacy manifest yet for ios

**Comment by vbrandl** [comment]
Du you know of any alternative libraries that are still maintained?

**Comment by himanshu-newstok** [comment]
No @vbrandl . I am frustrated due to this. I think I should directly use shared_preference for storing data and encrypt and decrypt data on my own.

**Comment by vbrandl** [comment]
Hm that kinda sucks. Maybe we have to look into someting like that, too

**Comment by Daniel-Cong** [comment]
The maintainer is MIA, he won't even approve a simple pull request such as adding a privacy manifest. This project is officially dead.

**Comment by juliansteenbakker** [comment]
Hi all, i am back and will update a new version asap. My apologies for the delay.

**Comment by vbrandl** [comment]
Can anything be done to prevent this from happening again? Could you maybe add another trusted maintainer (I know this is a big ask after the xz debacle)?

I can't use a dependency in good conscience at work that goes completely silent for many months.

**Comment by vbrandl** [comment]
Do you have a way to contact the owner?

If not, then maybe a fork is the way to go? The current situation doesn't make me feel comfortable using this...

**Comment by juliansteenbakker** [comment]
I don't have any other contact info of the owner. You are ofcourse free to setup your own fork.
