### ISSUE TITLE
IOS - readAll() never returns results. 

### ISSUE THREAD

**Issue by dgriffith0** [mogol/flutter_secure_storage#70]
On IOS, after adding a key/value pair, readAll() will not return the result. If I pull the value with a read() it works fine. In the Objective C code the SecItemCopyMatching returns an OSSTATUS of -50.

**Comment by joshuaferguson** [comment]
From Apple Docs:

> Note
> You can't combine the `kSecReturnData` and `kSecMatchLimitAll` options when copying password items (items of class `kSecInternetPasswordItemClass` or `kSecGenericPasswordItemClass`), because copying each password item could require additional authentication. Instead, request a reference or persistent reference to the items, then request the data for only the specific passwords that you actually require.

Removing `kSecReturnData` from `readAll` will return all the keys, but no data, so it looks like you'll have to search with just the `kSecReturnAttributes` and `kSecMatchLimitAll`, then iterate through the results individually to build up a dictionary to return.
