### ISSUE TITLE
Error when updating the flutter_secure_storage_platform_interface 1.1.0

### ISSUE THREAD

**Issue by romaCaldeira** [mogol/flutter_secure_storage#707]
../../../../../.pub-cache/hosted/pub.dev/flutter_secure_storage-9.0.0/lib/test/test_flutter_secure_storage_platform.dart:3:7: Error: The non-abstract class 'TestFlutterSecureStoragePlatform' is missing implementations for these members:
- FlutterSecureStoragePlatform.isCupertinoProtectedDataAvailable
- FlutterSecureStoragePlatform.onCupertinoProtectedDataAvailabilityChanged

**Comment by juliansteenbakker** [comment]
You guys are too fast for me 😄 , i have just released v9.1.0 which incorporates the new features.

**Comment by kupresk14** [comment]
Amazing TY!!!

**Comment by mfurkanyuceal** [comment]
Same problem

**Comment by clintpurser** [comment]
Thank you for the quick fix, Julian!
