### ISSUE TITLE
Flutter secure storage 8.1.0 no longer works

### ISSUE THREAD

**Issue by RobMW** [mogol/flutter_secure_storage#708]
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_secure_storage-8.1.0/lib/test/test_flutter_secure_storage_platform.dart:3:7: Error: The non-abstract class 'TestFlutterSecureStoragePlatform' is missing implementations for these members:
 - FlutterSecureStoragePlatform.isCupertinoProtectedDataAvailable
 - FlutterSecureStoragePlatform.onCupertinoProtectedDataAvailabilityChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class TestFlutterSecureStoragePlatform extends FlutterSecureStoragePlatform {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_secure_storage_platform_interface-1.1.0/lib/flutter_secure_storage_platform_interface.dart:36:16: Context: 'FlutterSecureStoragePlatform.isCupertinoProtectedDataAvailable' is defined here.
  Future<bool> isCupertinoProtectedDataAvailable();
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_secure_storage_platform_interface-1.1.0/lib/flutter_secure_storage_platform_interface.dart:34:20: Context: 'FlutterSecureStoragePlatform.onCupertinoProtectedDataAvailabilityChanged' is defined here.
  Stream<bool> get onCupertinoProtectedDataAvailabilityChanged;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Progetti\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command 'D:\Progetti\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

No longer works since the update to flutter_secure_storage_platform_interface: 1.1.0 is marked as compatible via the ^ (caret) in the pubspec of flutter_secure_storage

https://dart.dev/tools/pub/dependencies#version-constraints

**Comment by RoarGronmo** [comment]
Experiencing the same issue,but a slightly different version scheming:

```
[ +282 ms] /C:/Users/[...]/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_secure_storage-9.0.0/lib/test/test_flutter_secure_storage_platform.dart:3:7: Error: The non-abstract class 'TestFlutterSecureStoragePlatform' is missing implementations for these members:
[        ]  - FlutterSecureStoragePlatform.isCupertinoProtectedDataAvailable
[        ]  - FlutterSecureStoragePlatform.onCupertinoProtectedDataAvailabilityChanged
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class TestFlutterSecureStoragePlatform extends FlutterSecureStoragePlatform {
[        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] /C:/Users/[...]/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_secure_storage_platform_interface-1.1.0/lib/flutter_secure_storage_platform_interface.dart:36:16: Context: 'FlutterSecureStoragePlatform.isCupertinoProtectedDataAvailable' is defined here.
[        ]   Future<bool> isCupertinoProtectedDataAvailable();
[        ]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] /C:/Users/[...]/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_secure_storage_platform_interface-1.1.0/lib/flutter_secure_storage_platform_interface.dart:34:20: Context: 'FlutterSecureStoragePlatform.onCupertinoProtectedDataAvailabilityChanged' is defined here.
[        ]   Stream<bool> get onCupertinoProtectedDataAvailabilityChanged;
[        ]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+1700 ms] > Task :app:compileFlutterBuildDebug
[        ] Caching disabled for task ':app:compileFlutterBuildDebug' because:
[        ]   Build cache is disabled
[        ] Task ':app:compileFlutterBuildDebug' is not up-to-date because:
[        ]   Task has failed previously.


```
`[...]` = Obfuscating names above

Any short term remedy ?

**Comment by juliansteenbakker** [comment]
I was fearing this already, you can override the interface version for now. I will fix this in a few hours.

**Comment by RoarGronmo** [comment]
> I was fearing this already, you can override the interface version for now. I will fix this in a few hours.

I seems that this library was used in dependent libraries in my project, I'll rather watch a football game until fixed... ;)

**Comment by banksAcc** [comment]
I also experience the same problem...
I also almost saw a football game... ahahaha ;)

**Comment by marcoconceicao** [comment]
Same issue here

**Comment by Yonkokilasi** [comment]
Just experienced this when pushing to production 😢 .. Does upgrading fix the issue ?

**Comment by RobMW** [comment]
> Just experienced this when pushing to production 😢 .. Does upgrading fix the issue ?

Add this to your pubspec if you can't wait for the fix:
flutter_secure_storage_platform_interface: 1.0.2

**Comment by banksAcc** [comment]
This didn't solve the problem for me @RobMW 
<img width="1382" alt="Screenshot 2024-05-08 alle 18 16 42" src="https://github.com/mogol/flutter_secure_storage/assets/143713040/618afc6c-b816-4b10-a90a-05d046ffef85">

**Comment by RobMW** [comment]
> This didn't solve the problem for me @RobMW <img alt="Screenshot 2024-05-08 alle 18 16 42" width="1382" src="https://private-user-images.githubusercontent.com/143713040/328963156-618afc6c-b816-4b10-a90a-05d046ffef85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODU2NjAsIm5iZiI6MTcxNTE4NTM2MCwicGF0aCI6Ii8xNDM3MTMwNDAvMzI4OTYzMTU2LTYxOGFmYzZjLWI4MTYtNGIxMC1hOTBhLTA1ZDA0NmZmZWY4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNjIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTFlMmU2NjZjMThjNzc1M2M3N2NmNGRjYTdhYzkwZjA4MjljNmVmOGM3Y2JmYjE2Y2YyY2NlZTEzNmYyNWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._BDAHm-VMH1vRdoxmvPgYdyPWnQNfc0ZS7hI6EIKiaM">

Write it without the ^ (caret)

**Comment by Yonkokilasi** [comment]
Upgrading it to 9.0.0 seems to work

**Comment by juliansteenbakker** [comment]
Okay so because of the carret, all older versions are failing right now. I am going to revert the breaking changes, and republish them under a new major version. It takes me a few minutes to do this so please hold on. This package is a bit of a dependency disaster.

**Comment by banksAcc** [comment]
Alright, thanks for the support and help....have a good coding session

**Comment by Luismi74** [comment]
Just experienced this and our apps are halted for prod release, hope it gets solved soon. thanks in advance @juliansteenbakker!

**Comment by juliansteenbakker** [comment]
I have removed the breaking feature from all but the core package, which i am testing right now

**Comment by banksAcc** [comment]
Hi, just tested and works fine...Thanks for the support and fixing things...

Ps. if you need support for these things, 2 extra hands come in handy, don't hesitate to contact me

**Comment by juliansteenbakker** [comment]
Thank you for your offer! I have tried to add this package to the flutter community (https://github.com/fluttercommunity/community/issues/93) however i never really got an answer. I think i'm gonna try this again, and hope we can get more support via the community.

**Comment by giann** [comment]
> I will be releasing a new major versions with the new features somewhere in the next days.
@juliansteenbakker Will you release this soon? Turns out we experience quite a lot of data temprary loss du to iOS device being unlocked and `isCupertinoProtectedDataAvailable` would help us a lot

**Comment by lauroboeni** [comment]
version `9.1.1` does not solve the issue for me. I had to go back to `9.0.0` - that works as expected
