### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by schroedermatthias** [mogol/flutter_secure_storage#71]
Environment:
```
- Flutter version 1.9.6-pre.4 at /usr/local/Caskroom/flutter/latest/flutter
- Framework revision 17813975a9 (20 hours ago), 2019-08-24 17:06:36 -0400
- Engine revision deca2c0da8
- Dart version 2.5.0
```

I am trying to use flutter_secure_storage (version 3.2.1+1) in a macOS application. Is this platform supported at all? When trying to write to the storage

`await secureStorage.write(key: 'token', value: response['access_token']);`

I get:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)`

Thanks for support.

**Comment by mogol** [comment]
Hi @schroedermatthias 
The plugin doesn't support macOS.

**Comment by schroedermatthias** [comment]
@mogol Do you think it's possible to implement using macOS Keychain?

**Comment by mogol** [comment]
I haven't yet tried to write a plugin for macOS, but [at first glance](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/example_plugin/macos/Classes/ExamplePlugin.swift) it's possible and as simple as the original ones.

**Comment by ChaseGuru** [comment]
I get a missing plugin exception running it on a pixel 2xl emulator

**Comment by 5hirish** [comment]
I have also been getting the **MissingPluginException**.
Device: Pixel 2 API 27 Emulator
```
info flutter.tools E/flutter (15715): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
```
Uninstalling and installing the app only works.

**Comment by mogol** [comment]
It should be possible only if host app isn’t rebuild if a plugin was added. 
Pls try stop the app, do flutter clean and launch

**Comment by 5hirish** [comment]
@mogol flutter clean doesn't work. Only uninstalling and installing works.

**Comment by Baqaisooo** [comment]
> @mogol flutter clean doesn't work. Only uninstalling and installing works.

do you mean by that is uninstalling app from the mobile and then run `flutter run` ?

**Comment by Mohammad-ezzidden** [comment]
still not work on android 6.0 and bellow.

**Comment by Ignusmart** [comment]
Hey, I'm having the same issue, what do you mean with `uninstall` the app?

**Comment by EMINBARI** [comment]
I got the same problem and clearing all data in app or uninstallation the app was a real worked solution but not perfect( Then I realized what I did wrong. My application uses API and tokens is storing in secure storage. I didn't make refresh token API function, since I fixed that there is no exception like that

**Comment by darab-singh93** [comment]
I am also facing this issue with this package: flutter_secure_storage: ^3.3.3 and flutter version: Channel stable, v1.17.5,

**Comment by donkii** [comment]
I am having the same problem on my Windows laptop device. My colleague on her Mac is able to run it. Not sure if that is affecting it somehow

**Comment by qianxuechao** [comment]
http://blog.z7ge.com/archives/flutter-missingpluginexception-bu-yao-huang 希望能帮到你

**Comment by faraz-ahmad** [comment]
I am facing the exact same issue. I also uninstalled the app but It did not work. Can anyone please tell me the solution.

**Comment by juliansteenbakker** [comment]
The missing plugin exception will be tracked in #136 and #152. macOS support is tracked in #106 and will be implemented with #257.

**Comment by blackbeario** [comment]
flutter_secure_storage: ^5.0.2

Restarted application in 1,027ms.
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
#0      MethodChannel._invokeMethod
<asynchronous suspension>
#1      Cart.getCart
<asynchronous suspension>
#2      Cart.addToCart
<asynchronous suspension>
#3      _ProductDetailState._itemAddToCart
<asynchronous suspension>

**Comment by felipecastrosales** [comment]
I was able to get the test run and improve my coverage that way. ⬇️ 

- ![image](https://user-images.githubusercontent.com/59374587/202589208-c8b43ba0-b03c-416d-8d1c-dd3a4ff8487f.png)

Source code: 

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import 'package:good_app/data/data.dart';

import '../../../fixtures/fixtures.dart';

void main() async {
  TestWidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();

  late LocalSecureStorage localSecureStorageImpl;
  late MockLocalSecureStorage mockLocalSecureStorage;

  setUp(() {
    localSecureStorageImpl = FlutterSecureStorageLocalStorageImpl();
    mockLocalSecureStorage = MockLocalSecureStorage();
  });

  group('Should call in FlutterSecureStorageLocalStorageImpl the method', () {
    test('clear', () async {
      when(() => mockLocalSecureStorage.clear()).thenAnswer((_) async => true);
      final result = await localSecureStorageImpl.clear();
      expect(() => result, returnsNormally);
    });

    test('contains', () async {
      when(
        () => mockLocalSecureStorage.contains(any()),
      ).thenAnswer((_) async => true);
      final result = await localSecureStorageImpl.contains('key');
      expect(() => result, returnsNormally);
    });

    test('read', () async {
      when(
        () => mockLocalSecureStorage.read(any()),
      ).thenAnswer((_) async => 'value');
      final result = await localSecureStorageImpl.read('key');
      expect(() => result, returnsNormally);
    });

    test('remove', () async {
      when(
        () => mockLocalSecureStorage.remove(any()),
      ).thenAnswer((_) async => true);
      final result = await localSecureStorageImpl.remove('key');
      expect(() => result, returnsNormally);
    });

    test('write', () async {
      when(
        () => mockLocalSecureStorage.write(any(), any()),
      ).thenAnswer((_) async => true);
      final result = await localSecureStorageImpl.write('key', 'value');
      expect(() => result, returnsNormally);
    });
  });

  const MethodChannel('plugins.it_nomads.com/flutter_secure_storage')
      .setMockMethodCallHandler((MethodCall methodCall) async {
    if (methodCall.method == 'clear') {
      return true;
    } else if (methodCall.method == 'containsKey') {
      return true;
    } else if (methodCall.method == 'read') {
      return 'value';
    } else if (methodCall.method == 'write') {
      return true;
    } else if (methodCall.method == 'remove') {
      return true;
    } else if (methodCall.method == 'write') {
      return true;
    }
    return null;
  });
}

```

**Comment by wfgm5k2d** [comment]
Oddly enough, deleting the application also helped me
I develop on macOS and use the simulator built into Android Studio
Simulator included on Iphone 15 Pro Max
My steps to fix it

1. Stop the application
2. Turn off the emulator
3. `flutter clean`
4. `flutter upgrade`
5. Pull back all dependencies (Android Studio suggested doing this via a button)

I checked, everything works
