### ISSUE TITLE
A problem occurred configuring project ':flutter_secure_storage'.

### ISSUE THREAD

**Issue by devnoaman** [mogol/flutter_secure_storage#723]
I am trying to build app after updating my project to latest version of flutter and an error just occurs , the error message tells that :

> A problem occurred configuring project ':flutter_secure_storage'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/noaman/.pub-cache/hosted/pub.dev/flutter_secure_storage-4.2.1/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by juliansteenbakker** [comment]
You are using a very old version of this plugin. `flutter_secure_storage-4.2.1` The current version is 9.2.2.

**Comment by WieFel** [comment]
I just had the same problem.
Kind of funny, when running `flutter pub add flutter_secure_storage`, it installs version `4.2.1`. Maybe this is a bug?
Manually setting it to the latest version solves the problem...

**Comment by vaspadi** [comment]
I was in the same situation as [@WieFel ](https://github.com/juliansteenbakker/flutter_secure_storage/issues/723#issuecomment-2709772585)

**Comment by MoustafaHarounCompad** [comment]
Same issue as @WieFel and @vaspadi , fixed it by just copying the latest version inside of my pubspec.yaml

**Comment by jokardariush600-cmd** [comment]
I'm having the same issue and haven't been able to fix it.

In my `pubspec.yaml`, I'm using the latest version of `flutter_secure_storage` (`10.3.1`), but during the Gradle build it tries to download Android Gradle Plugin version **8.13.2**, which doesn't exist.

When I run:

```bash
./gradlew clean
```

I get the following error:

```text
> Configure project :gradle
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `2.0.21` that might work differently than in the requested version `2.2.20`.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_secure_storage'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not find com.android.tools.build:gradle:8.13.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.13.2/gradle-8.13.2.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.13.2/gradle-8.13.2.pom
     Required by:
         project :flutter_secure_storage
```

Has anyone else run into this issue? Why is Gradle trying to resolve AGP **8.13.2** when I'm using the latest `flutter_secure_storage` package? Any help would be greatly appreciated.
