### ISSUE TITLE
Beware the androidx.security:security-crypto is deprecated

### ISSUE THREAD

**Issue by talamaska** [mogol/flutter_secure_storage#729]
Info found here:
[Jetpack security crypto library](https://developer.android.com/privacy-and-security/cryptography#jetpack_security_crypto_library)
also found some info on how to proceed in the future for the maintainers and users
[securing-the-future-navigating-the-deprecation-of-encrypted-shared-preferences](https://proandroiddev.com/securing-the-future-navigating-the-deprecation-of-encrypted-shared-preferences-91ce3c20ae8d)
I don't mean this Issue to be a spam or something.

**Comment by juliansteenbakker** [comment]
The fix for this issue will be discussed in #769
