### ISSUE TITLE
[WEB] Wasm support

### ISSUE THREAD

**Issue by rokk4** [mogol/flutter_secure_storage#732]
Do not hinder `wasm` compilation.
```
    Context: The unavailable library 'dart:html' is imported through these packages:
    
    web_plugin_registrant.dart => package:flutter_secure_storage_web => dart:html

```

**Describe the solution you'd like**
Move away from `dart:html` and `dart:js`

> [package:web](https://pub.dev/packages/web), which replaces dart:html (and other web libraries)
> [dart:js_interop](https://api.dart.dev/stable/dart-js_interop), which replaces package:js and dart:js

https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm

**Comment by ThomasAunvik** [comment]
https://github.com/mogol/flutter_secure_storage?tab=readme-ov-file#wasm-support

**Comment by hermankravchenko-ama** [comment]
> https://github.com/mogol/flutter_secure_storage?tab=readme-ov-file#wasm-support

Wow that was quick

**Comment by sk92129** [comment]
I generated a simple flutter app and then cursor IDE led me thru all the changes to make it compatible for a wasm build.
https://github.com/sk92129/secure-storage-web-wasm-simple

**Comment by alvarogabrielgomez** [comment]
Im wating this

**Comment by WilliamAndreuRudo** [comment]
Version 10.0.0 is now compatible with wasm.
