### ISSUE TITLE
Recording with encrypted data

### ISSUE THREAD

**Issue by mat20s23** [mogol/flutter_secure_storage#746]
Following the code below, the plugin automatically records encrypted data on Android and iOS. Or do I need to pass some options parameter?

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
final storage = FlutterSecureStorage();
await storage.write(key: 'username', value: 'example@domain.com');

**Comment by juliansteenbakker** [comment]
Hi, this will indeed work out of the box.
