### ISSUE TITLE
After reopen application, getting null values in IOS. But working in Android. 

### ISSUE THREAD

**Issue by sureshprokraya** [mogol/flutter_secure_storage#752]
Hi,
I am using flutter_secure_storage: 9.0.0 version in flutter application. But when ever i closed the app and reopen again ,
After splash screen i am getting data null in IOS, but in Android works fine.

How to fix this issue, please any one help me on this.

**Comment by sureshprokraya** [comment]
class SecureStorage {
  // Create storage
  late FlutterSecureStorage _storage;

  static final SecureStorage _instance = SecureStorage._internal();

  factory SecureStorage() {
    return _instance;
  }

  SecureStorage._internal() {
    _storage = FlutterSecureStorage();
  }

  // Read value
  Future<bool> isSet({required String key}) async {
    var val = await _storage.containsKey(key: key);
    return val;
  }

// Read value
  Future readSecureData({required String key}) async {
    var readData = await _storage.read(key: key);
    return readData;
  }

// Read all values
  Future readAllSecureData() async {
    Map<String, String> allValues = await _storage.readAll();
    return allValues;
  }

// Write value
  Future writeSecureData({required String key, required String value}) async {
    var writeData =
        await _storage.write(key: key, value: value);
    return writeData;
  }

  // Delete value
  Future deleteSecureData({required String key}) async {
    var deleteData = await _storage.delete(key: key);
    return deleteData;
  }

  // Delete value
  Future deleteAllSecureData() async {
    var deleteData = await _storage.deleteAll();
    return deleteData;
  }
}
//This is I am using in my app, but still issue is not fixed.

**Comment by sureshprokraya** [comment]
Every time i am calling the Login API for token update, and deleting all Secure Stotage data, then again saving fresh data in secure storage. 

So when ever reopen the application in IOS app, 
When ever try to save data in secure storage below error occurred
 How to solve this.

**Comment by kkh975** [comment]
Same here, is there a size limit?

**Comment by sureshprokraya** [comment]
It is a flutter_secure_storage library issue, Just replace with flutter_key_chain library.

Its similar functionality.  I am using it. Its working as expected.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by huvi8161** [comment]
I have the same problem.

**Comment by kieranmccwayleadr** [comment]
We have this issue along with the BadPaddingException: https://github.com/mogol/flutter_secure_storage/issues/541 I feel we need to personally remove the Flutter Secure Storage. It's causing weird issues. Might look into `flutter_keychain` @sureshprokraya what has been your experience so far using this package across android and ios?

**Comment by rddewan** [comment]
value is always null

**Comment by sureshprokraya** [comment]
As of now I don't have any issue while using flutter_keychain.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rddewan** [comment]
Look like it only support string as a value. I tries to store a int and got error but after storing as string its working
