### ISSUE TITLE
SHA-1 is a weak hash known to have hash collisions. 

### ISSUE THREAD

**Issue by ftopacho** [mogol/flutter_secure_storage#758]
I have this issue around use of weak Hashes for Huawei proprietary libraries. Would upgrading the libraries help remediate the vulnerability?
The huawei libraries am using are being flagged for weak hashing algorithms.

View attachment for assistance

**Comment by juliansteenbakker** [comment]
Hi, a possible fix for this issue will be discussed in #769

**Comment by ftopacho** [comment]
Have you tested the solution and fully confirm that it addresses the vulnerability.  Because I thought this is being flagged from Huawei libraries that am using.

**Comment by juliansteenbakker** [comment]
Hi, i have not tested anything yet since it is still a work in progress. Do you have any more information for me? I don't see any attachments.

**Comment by ftopacho** [comment]
Let me get information and share
