### ISSUE TITLE
After reopen application, getting null values in IOS. But working in Android

### ISSUE THREAD

**Issue by huvi8161** [mogol/flutter_secure_storage#760]
Hi,
I am using flutter_secure_storage: 9.2.2 version in flutter application. But when ever i closed the app and reopen again ,
After splash screen i am getting data null in IOS, but in Android works fine. On version 9.0.0 everything is working correctly.

How to fix this issue, please any one help me on this.

**Comment by paulking86** [comment]
I would assume you are suffering from this issue!

https://github.com/mogol/flutter_secure_storage/issues/711

There is a PR here which should fix the issue, although I think some discussions surrounding it are ongoing!

https://github.com/mogol/flutter_secure_storage/pull/751

All the best

**Comment by juliansteenbakker** [comment]
The fixes mentioned are merged and will be released asap.
