### ISSUE TITLE
Datas are not removed when app is uninstalled - I0S

### ISSUE THREAD

**Issue by aswinsubhash** [mogol/flutter_secure_storage#765]
When an app is uninstalled on iPhone, the data stored once is not removed from the phone local storage
Why???

**Comment by muhamedRadwan** [comment]
any solution to that?

**Comment by koji-1009** [comment]
Duplicate of https://github.com/mogol/flutter_secure_storage/issues/125

**Comment by juliansteenbakker** [comment]
Please see this fix https://github.com/mogol/flutter_secure_storage/issues/88#issuecomment-613168109
