### ISSUE TITLE
data is restored after reinstalling the application in IOS

### ISSUE THREAD

**Issue by Catsys** [mogol/flutter_secure_storage#82]
ios 12 and 13. 
1. i saving data in storage
2. i delete app
3. i install app by xcode 10, 11 or flutter
4. I read my data and see that they are still alive
This is abnormal behavior. I will be grateful for the help

**Comment by Catsys** [comment]
This happens because the data is stored in a keychain that is not cleared after the application is uninstalled. But still, the behavior is not very good and may not be safe for the user.

**Comment by taz1208** [comment]
me too :(

**Comment by nate-eisner** [comment]
This is standard behavior when using the Keychain. The recommended work around is to prefix any keys you use in secure storage with a specific identified for that installed version.

**Comment by Catsys** [comment]
I was rejected for a review indicating this as a reason when I wrote this. after the conversation, they nevertheless let me through. Yes, this is not a bug, this is the standard keychain behavior.
