### ISSUE TITLE
doesn't work on api level 23

### ISSUE THREAD

**Issue by CalmAndCoDe** [mogol/flutter_secure_storage#85]
hello, i recently used this package with my app it works well on android 8.0 that i use but when i install my app on huawei device with android 6 it throws an exception that secure storage isn't supported.
if its the device issue, please force it to fallback to the simple shared preference not the Keychain.
thanks.

**Comment by jonataslaw** [comment]
Same problem heme

**Comment by Gnpiwano** [comment]
Same here

**Comment by Baqaisooo** [comment]
got the same Issue 
it works for other devices with different API level but on API level 23 keep getting me this error

what should I do to fix this?

```
E/flutter (17605): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter (17605): MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
E/flutter (17605): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (17605): <asynchronous suspension>
E/flutter (17605): #1      FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:20:16)
E/flutter (17605): #2      MyApp.build (package:otagu/main.dart:15:13)
E/flutter (17605): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
E/flutter (17605): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
E/flutter (17605): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (17605): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
E/flutter (17605): #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
E/flutter (17605): #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (17605): #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (17605): #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (17605): #11     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
E/flutter (17605): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (17605): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (17605): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (17605): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (17605): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter (17605): MissingPluginException(No implementation found for method readAll on channel plugins.it_nomads.com/flutter_secure_storage)
```

**Comment by CalmAndCoDe** [comment]
> got the same Issue
> it works for other devices with different API level but on API level 23 keep getting me this error
> 
> what should I do to fix this?
> 
> ```
> E/flutter (17605): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
> E/flutter (17605): MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
> E/flutter (17605): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> E/flutter (17605): <asynchronous suspension>
> E/flutter (17605): #1      FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:20:16)
> E/flutter (17605): #2      MyApp.build (package:otagu/main.dart:15:13)
> E/flutter (17605): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
> E/flutter (17605): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
> E/flutter (17605): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
> E/flutter (17605): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
> E/flutter (17605): #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
> E/flutter (17605): #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
> E/flutter (17605): #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
> E/flutter (17605): #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
> E/flutter (17605): #11     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
> E/flutter (17605): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
> E/flutter (17605): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
> E/flutter (17605): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
> E/flutter (17605): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> E/flutter (17605): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
> E/flutter (17605): MissingPluginException(No implementation found for method readAll on channel plugins.it_nomads.com/flutter_secure_storage)
> ```

hey, did u installed it without restarting, if yes, you should rebuild ur app again bcz its not like the unsupported error, you will need rebuild ur app if u installed a plugin that communicates through method channel.

**Comment by Baqaisooo** [comment]
> > got the same Issue
> > it works for other devices with different API level but on API level 23 keep getting me this error
> > what should I do to fix this?
> > ```
> > E/flutter (17605): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
> > E/flutter (17605): MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
> > E/flutter (17605): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> > E/flutter (17605): <asynchronous suspension>
> > E/flutter (17605): #1      FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:20:16)
> > E/flutter (17605): #2      MyApp.build (package:otagu/main.dart:15:13)
> > E/flutter (17605): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
> > E/flutter (17605): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
> > E/flutter (17605): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
> > E/flutter (17605): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
> > E/flutter (17605): #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
> > E/flutter (17605): #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
> > E/flutter (17605): #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
> > E/flutter (17605): #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
> > E/flutter (17605): #11     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
> > E/flutter (17605): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
> > E/flutter (17605): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
> > E/flutter (17605): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
> > E/flutter (17605): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> > E/flutter (17605): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
> > E/flutter (17605): MissingPluginException(No implementation found for method readAll on channel plugins.it_nomads.com/flutter_secure_storage)
> > ```
> 
> hey, did u installed it without restarting, if yes, you should rebuild ur app again bcz its not like the unsupported error, you will need rebuild ur app if u installed a plugin that communicates through method channel.

yes, I did restart, I did uninstall and install the app and nothing happen, as I said before, I think the problem is with this version of android bcz it works with another version

**Comment by Mohammad-ezzidden** [comment]
not resolved yet ?

**Comment by Baqaisooo** [comment]
> not resolved yet ?

I think it still not working on sdk 6 and below

**Comment by dsp1589** [comment]
Android 10. Its not working.

**Comment by juliansteenbakker** [comment]
I have tested this with a LG G4 running android 6 and can confirm that it is working.
