### ISSUE TITLE
[iOS] Does not work when keychain accessed when app is in background

### ISSUE THREAD

**Issue by fvisticot** [mogol/flutter_secure_storage#94]
I need to access the keychain on iOS to get the token to send HTTP request when app is in background.

Seems the same issue to: https://github.com/mogol/flutter_secure_storage/issues/50

**Comment by fvisticot** [comment]
any update ?

**Comment by mogol** [comment]
Hi @fvisticot 
So far no updates, but I will try my best to update the plugin over the weekends

**Comment by mogol** [comment]
The feature was added in v3.3.2
