### ISSUE TITLE
How to access the key from different pages?

### ISSUE THREAD

**Issue by henryla92** [mogol/flutter_secure_storage#97]
Hi there,

I'm just wondering how I would use a value that I saved(wrote) from one page, on a different page?

Is setting a global storage variable and passing it into different pages the correct way to do it?

Thanks in advance!

**Comment by mogol** [comment]
Hi @henryla92 
You could use any of state management patterns available in Flutter. Please check these guidelines https://flutter.dev/docs/development/data-and-backend/state-mgmt/intro
