### ISSUE TITLE
Default Insecure Data Storage

### ISSUE THREAD

**Issue by Fallenstedt** [mogol/flutter_secure_storage#98]
Is it ridiculous of me to ask for clarification on how tokens are stored currently? I have a suspicion this package performs insecure Data Storage. 

https://github.com/mogol/flutter_secure_storage/blob/master/ios/Classes/FlutterSecureStoragePlugin.m#L66

When we `write` we are adding a new KeyChain item. When adding a new keychain item, we have the option of adding the key with with 6 accessibility options.

- kSecAttrAccessibleWhenUnlocked
- kSecAttrAccessibleAfterFirstUnlock
- kSecAttrAccessibleAlways
- kSecAttrAccessibleWhenUnlockedThisDeviceOnly
- kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
- kSecAttrAccessibleAlwaysThisDeviceOnly

There are *vulnerable* security options when adding a key to our keychain. Specifically **kSecAttrAccessibleAlways** and **kSecAttrAccessibleAlwaysThisDeviceOnly**. The risk is that a user's key may be exposed to other applications on JailBroken devices or attackers with physical access when writing to KeyChain with the following above options.

What is the default accessibility option this package uses when adding a token to a keychain? Is there any way to customize this?

**Comment by wszeborowskimateusz** [comment]
Any information about this Issue ? This is also a security concern in my case.

**Comment by doc-rj-celltrak** [comment]
The iOS default seems to be kSecAttrAccessibleWhenUnlocked. I don't think this plugin specifies the kSecAttrAccessible key, so we get the default. [reference ](https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility)

**Comment by mogol** [comment]
Default value is used. 
From v3.3.2 you can use [accessibility options](https://pub.dev/documentation/flutter_secure_storage/latest/flutter_secure_storage/IOSAccessibility-class.html). Thanks to @negator
